import type { Spot } from '../spots';
import type { AreaSlug } from '../area';

/** スポット拡充バッチ2（北関東・甲信越）。SPOTS に name 単位でマージされる。 */
export const SPOTS_EXTRA_2: Partial<Record<AreaSlug, Spot[]>> = {
  ibaraki: [
    { name: '国営ひたち海浜公園', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: 'ひたちなか市', note: '四季の花畑と観覧車のあるプレジャーガーデンが楽しめる広大な国営公園', budget: 'low' },
    { name: 'ミュージアムパーク茨城県自然博物館', category: 'museum', place: 'mixed', ages: ['2-3', '4-6'], city: '坂東市', note: '恐竜展示と屋外広場・トランポリンで学びと体遊びが両立する自然博物館', budget: 'low', hiddenTip: '屋外のドコドコランドは晴れた日が狙い目',
      summerCool: true, },
    { name: '笠間芸術の森公園', category: 'park', place: 'outdoor', ages: ['2-3', '4-6'], city: '笠間市', note: '全長160mのローラー滑り台や雲のトランポリンがある芸術と遊びの公園', budget: 'free' },
    { name: 'こもれび森のイバライド', category: 'farm', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '稲敷市', note: '動物とのふれあいやパン・ソーセージ作り体験ができる体験型ファーム', budget: 'mid' },
    { name: '日立市かみね動物園', category: 'zoo', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '日立市', note: '太平洋を望む高台にあり、入園料も手頃で小さな子と回りやすい動物園', budget: 'low' },
    { name: 'キッズユーエスランド 牛久店', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '牛久市', note: 'ボールプールや大迷路など遊具が充実し、天候を気にせず遊べる屋内施設', budget: 'low',
      summerCool: true,
      waterPlay: true, },
  ],
  tochigi: [
    { name: 'とちのきファミリーランド', category: 'amusement', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '宇都宮市', note: '入園無料の遊園地で、0歳から乗れる乗り物や大観覧車が楽しめる', budget: 'low' },
    { name: '宇都宮動物園', category: 'zoo', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '宇都宮市', note: '動物とのふれあいや餌やりに加え、遊園地も併設された複合施設', budget: 'mid' },
    { name: '壬生町おもちゃ博物館', category: 'museum', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '壬生町', note: 'とちぎわんぱく公園に隣接、室内でも屋外でもたっぷり遊べる遊べる博物館', budget: 'low',
      summerCool: true, },
    { name: 'みかも山公園', category: 'park', place: 'outdoor', ages: ['2-3', '4-6'], city: '栃木市', note: '三毳山にあり、わんぱく広場や冒険砦など子ども向け遊具が充実した公園', budget: 'free' },
    { name: 'なかがわ水遊園', category: 'aquarium', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '大田原市', note: '栃木県唯一の水族館。無料で遊べる大型アスレチックコーナーも併設', budget: 'low',
      summerCool: true,
      waterPlay: true, },
    { name: '那須高原りんどう湖ファミリー牧場', category: 'farm', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '那須町', note: '動物とのふれあいや展示が充実し、大型室内遊具ゾーンもある牧場', budget: 'mid' },
    { name: '那須サファリパーク', category: 'zoo', place: 'outdoor', ages: ['2-3', '4-6'], city: '那須町', note: 'ホワイトライオンなど約50種の動物を車内から間近に見られるサファリ', budget: 'mid' },
  ],
  gunma: [
    { name: 'ぐんまこどもの国児童会館', category: 'indoor', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '太田市', note: 'プレイルームや図書室があり、小さな子から小学生まで一日楽しめる施設', budget: 'free',
      summerCool: true, },
    { name: '前橋市中央児童遊園 るなぱあく', category: 'amusement', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '前橋市', note: '入場無料で乗り物は10〜50円、小さな子向けの乗り物が揃う児童遊園', budget: 'low' },
    { name: '伊香保グリーン牧場', category: 'farm', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '渋川市', note: '動物とのふれあいや乳しぼり体験ができ、濃厚ソフトクリームも人気の牧場', budget: 'mid' },
    { name: '華蔵寺公園', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '伊勢崎市', note: '小さな子も楽しめるアトラクションのある遊園地を併設した総合公園', budget: 'free' },
    { name: '神津牧場', category: 'farm', place: 'outdoor', ages: ['2-3', '4-6'], city: '下仁田町', note: '日本初の洋式牧場。動物とのふれあい広場や牛の帰り行列が見られる', budget: 'low' },
    { name: 'フレーベル館 Kinder Platz ガーデン前橋店', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '前橋市', note: 'ボールプールやエア遊具など動と静の遊び場がそろう広い屋内遊戯施設', budget: 'low',
      summerCool: true,
      waterPlay: true, },
  ],
  yamanashi: [
    { name: '山梨県立科学館', category: 'museum', place: 'indoor', ages: ['2-3', '4-6'], city: '甲府市', note: 'プラネタリウムや体験展示が充実、体を動かせるあそびの部屋もある科学館', budget: 'low', hiddenTip: '隣接の愛宕山こどもの国とセットで一日遊べる',
      summerCool: true, },
    { name: '愛宕山こどもの国', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '甲府市', note: '2023年リニューアル。アスレチックやローラー滑り台で思いきり遊べる公園', budget: 'free' },
    { name: '山梨県立リニア見学センター', category: 'museum', place: 'indoor', ages: ['2-3', '4-6'], city: '都留市', note: 'リニアモーターカーの実験線を間近に見学できる体験型の博物館', budget: 'low',
      summerCool: true, },
    { name: '曽根丘陵公園', category: 'park', place: 'outdoor', ages: ['2-3', '4-6'], city: '甲府市', note: 'ローラー滑り台やターザンロープ、広い芝生広場で遊べる丘陵公園', budget: 'free' },
    { name: '山梨県立考古博物館', category: 'museum', place: 'indoor', ages: ['4-6'], city: '甲府市', note: '火起こしや勾玉作りなど古代の体験メニューが充実した博物館', budget: 'low',
      summerCool: true, },
  ],
  nagano: [
    { name: '須坂市動物園', category: 'zoo', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '須坂市', note: 'コンパクトでベビーカーでも回りやすく、イベントが充実した動物園', budget: 'low' },
    { name: '城山動物園', category: 'zoo', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '長野市', note: 'ウサギやモルモットとのふれあいができ、ベビーカー入場もしやすい動物園', budget: 'free' },
    { name: '飯田市立動物園', category: 'zoo', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '飯田市', note: '40種以上を飼育する無料の動物園。ヤギやモルモットの餌やりも楽しめる', budget: 'free' },
    { name: '忍者の里 チビッ子忍者村', category: 'amusement', place: 'mixed', ages: ['2-3', '4-6'], city: '長野市', note: '忍者修行をテーマにした体験型施設。屋内のからくり屋敷で雨でも楽しめる', budget: 'mid' },
    { name: 'かざこし子どもの森公園', category: 'park', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '飯田市', note: '大型遊具や芝生広場に加え、室内施設や体験プログラムもある公園', budget: 'free' },
    { name: '佐久平ハイウェイオアシス パラダ', category: 'park', place: 'mixed', ages: ['2-3', '4-6'], city: '佐久市', note: '冬は雪遊び、夏はアスレチックや動物ふれあいと四季を通じて遊べる施設', budget: 'mid' },
  ],
  toyama: [
    { name: '富山県こどもみらい館', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '射水市', note: '太閤山ランド内。球体遊具や全長100mのトンネルがある屋内体験施設', budget: 'low',
      summerCool: true, },
    { name: '県民公園太閤山ランド', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '射水市', note: '複合遊具やターザンロープ、広い芝生があり入場無料で一日遊べる公園', budget: 'free' },
    { name: '富山あそびマーレ', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '射水市', note: '0〜12歳向けに30種以上の遊具がそろう北陸最大規模の室内遊園地', budget: 'mid',
      summerCool: true, },
    { name: '富山市科学博物館', category: 'museum', place: 'indoor', ages: ['2-3', '4-6'], city: '富山市', note: 'ナウマンゾウの大型展示や、風を体験できる装置、プラネタリウムが楽しめる', budget: 'low',
      summerCool: true, },
    { name: '魚津水族館', category: 'aquarium', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '魚津市', note: '日本海側で最初に開館した水族館。富山湾の魚を中心に約330種を展示', budget: 'low', hiddenTip: '土日は富山湾大水槽のネット遊具で遊べる',
      summerCool: true,
      waterPlay: true, },
    { name: 'ほたるいかミュージアム', category: 'museum', place: 'indoor', ages: ['2-3', '4-6'], city: '滑川市', note: 'ホタルイカをテーマにした博物館。春は発光ショーも見られる', budget: 'low',
      summerCool: true, },
    { name: '高岡おとぎの森公園', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '高岡市', note: 'ドラえもんの空き地を再現した広場がある、入園無料の大型公園', budget: 'free' },
  ],
  ishikawa: [
    { name: 'のとじま水族館', category: 'aquarium', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '七尾市', note: 'ペンギンのお散歩など生き物との距離が近い、体験型の水族館', budget: 'mid',
      summerCool: true,
      waterPlay: true, },
    { name: 'いしかわ動物園', category: 'zoo', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '能美市', note: '約200種を飼育、自然の地形を活かした広大な敷地でゆったり回れる動物園', budget: 'low' },
    { name: 'こどもっちパークかなざわ', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '金沢市', note: '空調完備の全天候型室内公園。ハンモックや芝のお山など独自遊具が充実', budget: 'low',
      summerCool: true, },
    { name: 'あそびの森 かほっくる', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: 'かほく市', note: '高さ10mの屋内立体ツリー遊具やボールプールで天候を気にせず遊べる', budget: 'low',
      summerCool: true,
      waterPlay: true, },
    { name: '手取フィッシュランド', category: 'amusement', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '能美市', note: '小さな子向けから本格的なものまで20のアトラクションがそろう遊園地', budget: 'mid' },
    { name: '銀河の里キゴ山', category: 'museum', place: 'mixed', ages: ['2-3', '4-6'], city: '金沢市', note: 'プラネタリウムや体験展示で自然や宇宙について楽しく学べる施設', budget: 'low',
      summerCool: true, },
  ],
};
