import type { Spot } from '../spots';
import type { AreaSlug } from '../area';

/**
 * スポット拡充バッチ7（東京23区+近郊のじゃぶじゃぶ池・無料水遊び場・噴水広場 30件）。
 * 営業期間は例年6月下旬〜9月中旬が多いが、施設ごとに大きく差があるため hiddenTip に明記。
 * 開放日・時間は年により変動するので、訪問前に公式サイトで再確認推奨。
 */
export const SPOTS_EXTRA_7: Partial<Record<AreaSlug, Spot[]>> = {
  tokyo: [
    {
      name: '林試の森公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '目黒区/品川区', ward: '目黒区',
      note: '森に囲まれた都立公園内の水場。木陰が多く真夏でも比較的涼しく遊べる。',
      budget: 'free',
      nearestStation: 'musashi-koyama',
      walkMinutes: 10,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜30cm',
      hiddenTip: '例年7月中旬〜8月末、10:00-11:50/13:00-14:50の2部制。木曜休園、60名定員で午後の回が狙い目',
    },
    {
      name: '戸山公園 箱根山地区 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '新宿区', ward: '新宿区',
      note: '山手線内側の貴重な無料水遊び場。箱根山西口側、幼児〜未就学児向け。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜20cm',
      hiddenTip: '例年7月中旬〜8月末の夏休み期間のみ開放。水着必須、オムツ着用児は入水不可',
    },
    {
      name: '上柚木公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '八王子市', ward: '八王子市',
      note: '南大沢駅近くの総合公園。陸上競技場や芝生広場と組み合わせて1日遊べる。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜20cm',
      hiddenTip: 'GWと夏休み期間限定で開放。清掃日は休止になるため公園公式サイトで事前確認を',
    },
    {
      name: '清水池公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '目黒区', ward: '目黒区',
      note: 'ジグザグに流れる水路を移動しながら遊べる。区内唯一の無料釣り堀も併設。',
      budget: 'free',
      nearestStation: 'gakugei-daigaku',
      walkMinutes: 8,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10cm前後',
      hiddenTip: '例年7月中旬〜9月初旬、9:00-16:30運転。学芸大学駅または武蔵小山駅から徒歩圏',
    },
    {
      name: '檜町公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '港区', ward: '港区',
      note: '東京ミッドタウン北側の区立公園。芝生広場と中央の噴水で水遊びができる。',
      budget: 'free',
      nearestStation: 'roppongi',
      walkMinutes: 3,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜15cm',
      hiddenTip: '6〜9月の開放期間中、毎時0-10分と30-40分の20分間放水。六本木駅徒歩3分でアクセス良',
    },
    {
      name: '駒沢オリンピック公園 ジャブジャブ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '世田谷区/目黒区', ward: '世田谷区',
      note: 'リニューアル後はベンチや木陰が増え、付き添う大人も快適に過ごせる広場。',
      budget: 'free',
      nearestStation: 'komazawa-daigaku',
      walkMinutes: 15,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜20cm',
      hiddenTip: '例年7月中旬〜8月末、10:00-16:00。小3以下対象、外気温25℃未満や雨天は休止',
      popular: true,
      facilities: {
        bathroom: 'yes',
        diaperChange: 'yes',
      },
    },
    {
      name: '和田堀公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '杉並区', ward: '杉並区',
      note: '善福寺川沿いの武蔵野の自然が残る都立公園。木陰の多いせせらぎで遊べる。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜20cm',
      hiddenTip: '例年7月〜8月末の開放。西永福駅から徒歩圏、京王バス「都立和田堀公園」下車',
    },
    {
      name: '光が丘公園 水景施設',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '練馬区', ward: '練馬区',
      note: 'けやき広場の水景施設で水遊びOK。広大な芝生広場や遊具とセットで楽しめる。',
      budget: 'free',
      nearestStation: 'hikarigaoka',
      walkMinutes: 8,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜15cm',
      hiddenTip: '2025年は7/23〜8/31稼働。例年7月中旬〜8月末、清掃のため平日午前は休止日もあり',
    },
    {
      name: '平和の森公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '大田区', ward: '大田区',
      note: '階段状の水路で高低差のある水遊びができる。水温が高めでオムツの子も安心。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜20cm',
      hiddenTip: '例年4月末〜9月末と長期稼働で他より早めに開放。京急平和島駅から徒歩約10分',
    },
    {
      name: '新宿中央公園 ジャブジャブ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '新宿区', ward: '新宿区',
      note: 'ちびっこ広場隣の浅く広い池。都庁を背景に水遊び、ベビーカー置き場あり。',
      budget: 'free',
      nearestStation: 'tochomae',
      walkMinutes: 1,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜15cm',
      hiddenTip: '例年7月上旬〜8月末、平日11:00-16:00/土日祝10:30-16:00。都庁前駅A5徒歩1分',
    },
    {
      name: '舎人公園 じゃぶじゃぶ池（浮球の池）',
      category: 'park', place: 'outdoor', ages: ['2-3', '4-6'],
      city: '足立区', ward: '足立区',
      note: '足立区最大級のじゃぶじゃぶ池。スライダー・滝・噴水で全身遊び。2026年は7/3〜9/29開催（水曜休止）。',
      budget: 'free',
      nearestStation: 'toneri-koen',
      walkMinutes: 1,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜30cm',
      hiddenTip: '2026年は7/3〜9/29・10-16時（水曜と8/13・9/17休止）。小3以下対象・おむつ着用児は入水不可。舎人公園駅直結',
      popular: true,
      officialUrl: 'https://www.tokyo-park.or.jp/park/toneri/',
      relatedArticleSlugs: [
        'toneri-koen-jabujabuike',
        'mizuasobi-adachi-tokyo',
        'jabujabuike-mizuasobi-tokyo-30',
        'jabujabu-ike-mizuasobi-zenkoku-2026natsu',
      ],
      facilities: {
        bathroom: 'yes',
        diaperChange: 'yes',
      },
    },
    {
      name: '武蔵野公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '小金井市/府中市', ward: '小金井市',
      note: '小金井公園の隣接エリア。大人の足首程度の浅さで乳幼児の初水遊びに最適。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜10cm',
      hiddenTip: '夏季のみ流水。横に大型遊具広場あり1日コースに。木陰も多くピクニック向き',
    },
    {
      name: '井の頭自然文化園 ジャブジャブ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '武蔵野市', ward: '武蔵野市',
      note: '自然文化園(動物園)内の浅い水遊び場。動物見学とセットで真夏のおでかけに。',
      budget: 'low',
      waterPlay: true,
      waterDepth: '約20cm',
      hiddenTip: '例年7月〜8月末開放、文化園入園料が別途必要(中学生以下無料)。水着or濡れてOKな服必須',
    },
    {
      name: '大横川親水公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '墨田区', ward: '墨田区',
      note: '川を埋め立てた細長い親水公園。橋や岩のオブジェで川遊び気分が味わえる。',
      budget: 'free',
      nearestStation: 'oshiage',
      walkMinutes: 5,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜15cm',
      hiddenTip: '7・8月は毎日、9月は土日祝のみ稼働。スカイツリー観光と組み合わせも',
    },
    {
      name: '水元公園 水遊び場',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '葛飾区', ward: '葛飾区',
      note: '23区最大級の都立公園。水元スポーツセンター公園側の階段状水場で水遊び。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜20cm',
      hiddenTip: '2025年は7/5〜9/15、10:00-16:30稼働。大型複合遊具が隣接、無料駐車場あり(夏は混雑)',
    },
    {
      name: '葛西海浜公園 西なぎさ',
      category: 'park', place: 'outdoor', ages: ['2-3', '4-6'],
      city: '江戸川区', ward: '江戸川区',
      note: '葛西臨海公園の南、人工渚で海水に触れて遊べる。潮干狩りや磯遊びも可能。',
      budget: 'free',
      nearestStation: 'kasai-rinkai-koen',
      walkMinutes: 10,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '足首〜膝程度（潮による）',
      hiddenTip: '海水浴は7月中旬〜8月末の10:00-16:00のみ。コインロッカー・更衣室あり、潮位確認推奨',
    },
    {
      name: '上野恩賜公園 竹の台広場 噴水',
      category: 'park', place: 'outdoor', ages: ['2-3', '4-6'],
      city: '台東区', ward: '台東区',
      note: '大噴水は30分ごとに演出が変わるショー型。夏は周囲で涼む家族連れが多い。',
      budget: 'free',
      nearestStation: 'ueno',
      walkMinutes: 5,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '入水不可（鑑賞・ミスト浴のみ）',
      hiddenTip: '入水できる池はないが、夏は噴水の風で涼を取れる。動物園・科学博物館とセットで',
    },
    {
      name: '錦糸公園 噴水',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '墨田区', ward: '墨田区',
      note: '錦糸町駅徒歩3分、地面から水が噴き上がる噴水で水深ゼロでも涼が取れる。',
      budget: 'free',
      nearestStation: 'kinshicho',
      walkMinutes: 3,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '0cm（地面噴出型）',
      hiddenTip: '例年7〜9月の11:00-16:00、10分おきに5分放水。中央の鑑賞噴水には入らないこと',
    },
    {
      name: '日暮里南公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '荒川区', ward: '荒川区',
      note: '駅近の区立公園。冒険遊具とじゃぶじゃぶ池がセットになった都会のオアシス。',
      budget: 'free',
      nearestStation: 'nippori',
      walkMinutes: 5,
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜20cm',
      hiddenTip: '例年7月〜9月初旬の夏期のみ稼働、日暮里駅徒歩5分。区内の他公園と巡る人も',
    },
    {
      name: '烏山川緑道 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '世田谷区', ward: '世田谷区',
      note: '暗渠化された川の上の遊歩道。浅い池で乳児からのデビュー水遊びに向く。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜15cm',
      hiddenTip: '例年7〜8月の夏季のみ流水。蘆花恒春園と組み合わせて夏のおでかけコースに',
    },
  ],
  kanagawa: [
    {
      name: 'こどもの国 アクアシスパーク',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '横浜市青葉区', ward: '横浜市',
      note: '60周年記念で2025年新設の屋外プール群。幼児用浅瀬や噴水プールで安心。',
      budget: 'low',
      waterPlay: true,
      waterDepth: '幼児用は20cm前後',
      hiddenTip: '夏期7月〜9月のみ。入園料(大人600円・小中200円・3歳〜100円)＋プール利用料。土日朝が比較的空く',
      popular: true,
      facilities: {
        bathroom: 'yes',
        diaperChange: 'yes',
      },
    },
    {
      name: '辻堂海浜公園 ジャンボプール',
      category: 'amusement', place: 'outdoor', ages: ['2-3', '4-6'],
      city: '藤沢市', ward: '藤沢市',
      note: '流れるプール・波のプール・スライダーが揃う県立公園内の大型レジャープール。',
      budget: 'low',
      pricing: { adult: '850円', elementary: '210円', preschool: '無料(未就学児)' },
      waterPlay: true,
      waterDepth: '幼児プール約20cm',
      hiddenTip: '7月中旬〜9月中旬の9:00-18:00。15:30以降は大人520円の午後割あり。水温22℃未満は休業',
    },
    {
      name: '県立四季の森公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '横浜市緑区', ward: '横浜市',
      note: '里山の起伏を活かした池とせせらぎ。岩の中で川遊び気分が味わえる無料スポット。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜30cm',
      hiddenTip: '5/1〜9/30は8:30-18:00。オムツ(水遊び用含む)着用不可、足元が岩場でマリンシューズ推奨',
    },
  ],
  chiba: [
    {
      name: 'ふなばしアンデルセン公園 にじの池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '船橋市', ward: '船橋市',
      note: 'ワンパク王国の中心にある水遊び場(通称じゃぶじゃぶ池)。アルキメデスの泉も隣接。',
      budget: 'low',
      pricing: { adult: '900円', elementary: '200円', preschool: '100円(4歳〜)' },
      waterPlay: true,
      waterDepth: '大人の膝程度',
      hiddenTip: 'GWと7〜9月入水可。オムツが取れていない子は入水不可、更衣室あり水着持参を',
      popular: true,
      facilities: {
        bathroom: 'yes',
        diaperChange: 'yes',
      },
    },
    {
      name: '県立青葉の森公園 水の広場',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '千葉市中央区', ward: '千葉市',
      note: '泉・雲・波をイメージした3種の噴水で違う水の感触を体験できる。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '約20cm',
      hiddenTip: '例年7月中旬〜8月下旬の10:00-16:00。オムツ着用児は入水不可、近くにつくしんぼの家あり',
    },
    {
      name: '袖ケ浦公園 じゃぶじゃぶ池',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '袖ケ浦市', ward: '袖ケ浦市',
      note: '4か所の遊具エリアを持つ大型公園内の天然小川。水温低めで真夏に気持ちいい。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜20cm',
      hiddenTip: '例年6月下旬〜9月初旬。展望台や池の散策路と組み合わせて1日コースに',
    },
    {
      name: '柏の葉公園 噴水広場',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '柏市', ward: '柏市',
      note: '噴水がそのままじゃぶじゃぶ池に。冒険のトリデなど大型遊具と組み合わせて遊べる。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜15cm',
      hiddenTip: '夏季のみ稼働、駐車場は有料。柏の葉キャンパス駅から徒歩・バスで',
      playgroundFeatures: ['athletic'],
    },
  ],
  saitama: [
    {
      name: '水とやすらぎの広場（大宮配水場内）',
      category: 'park', place: 'outdoor', ages: ['2-3', '4-6'],
      city: 'さいたま市大宮区', ward: 'さいたま市',
      note: 'さいたま市水道局管轄の無料水遊び場。ひょうたん形の池と噴水で長時間遊べる。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '10〜30cm',
      hiddenTip: '7/1〜9/30の9:00-17:00(池は16:30まで)。オムツ・水遊び用パンツ着用児は入水不可',
    },
    {
      name: '所沢航空記念公園 むさしの川',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: '所沢市', ward: '所沢市',
      note: '園内を流れる人工小川。とても浅く乳児の足浸しから幼児の川遊びまで対応。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '5〜10cm',
      hiddenTip: '例年6月上旬〜9月末まで流水(GWも稼働の年あり)。広大な芝生と航空発祥記念館で1日',
    },
    {
      name: '大宮花の丘農林公苑 親水広場',
      category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'],
      city: 'さいたま市西区', ward: 'さいたま市',
      note: '160m×最大19mの細長い水路。井戸水を使い水温は低めで真夏に涼しい。',
      budget: 'free',
      waterPlay: true,
      freeWaterPlay: true,
      waterDepth: '約10cm',
      hiddenTip: '例年7/20〜8/31の9:00-16:00。広い芝生と花畑も併設、駐車場250台で車アクセス向き',
    },
  ],
};
