import type { Spot } from '../spots';
import type { AreaSlug } from '../area';

/** スポット拡充バッチ1（北海道・東北）。SPOTS に name 単位でマージされる。 */
export const SPOTS_EXTRA_1: Partial<Record<AreaSlug, Spot[]>> = {
  hokkaido: [
    { name: '札幌市円山動物園', category: 'zoo', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '札幌市', note: '多彩な動物に加え、体を動かして遊べる遊具広場「まるっぱ」も併設。', budget: 'low' },
    { name: 'おたる水族館', category: 'aquarium', place: 'mixed', ages: ['2-3', '4-6'], city: '小樽市', note: 'イルカショーや、海を仕切った自然プールでの海獣展示が見どころ。', budget: 'mid',
      summerCool: true,
      waterPlay: true, },
    { name: 'AOAO SAPPORO', category: 'aquarium', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '札幌市', note: '商業施設内の都市型水族館。全室内展示で雨や雪の日も安心して遊べる。', budget: 'mid',
      summerCool: true,
      waterPlay: true, },
    { name: 'サンピアザ水族館', category: 'aquarium', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '札幌市', note: '新さっぽろ駅近くの小型水族館。コンパクトで小さい子と回りやすい。', budget: 'low',
      summerCool: true,
      waterPlay: true, },
    { name: '国営滝野すずらん丘陵公園', category: 'park', place: 'outdoor', ages: ['2-3', '4-6'], city: '札幌市', note: 'ロングローラー滑り台や大型複合遊具がそろう広大な国営公園。', budget: 'low',
      playgroundFeatures: ['long-slide', 'athletic'], },
    { name: 'モエレ沼公園', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '札幌市', note: '彫刻のような遊具と噴水ショー。夏はモエレビーチで水遊びが楽しめる。', budget: 'free',
      waterPlay: true, },
    { name: 'ファンタジーキッズリゾート新さっぽろ', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '札幌市', note: '駅近の大型室内遊園地。約750坪に遊具やアミューズメントが充実。', budget: 'mid',
      summerCool: true, },
  ],
  miyagi: [
    { name: '仙台うみの杜水族館', category: 'aquarium', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '仙台市', note: 'イルカ・アシカのパフォーマンスと三陸の海を再現した大水槽が見どころ。', budget: 'mid',
      summerCool: true,
      waterPlay: true, },
    { name: '国営みちのく杜の湖畔公園', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '川崎町', note: '1日では遊びきれない広さの大型国営公園。遊具や花畑が充実。', budget: 'low' },
    { name: '感性の森', category: 'indoor', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '仙台市', note: '木のぬくもりを感じる体験型施設。テーマごとのゾーンで感性を育む。', budget: 'mid',
      summerCool: true, },
    { name: 'キッズワールド名取店', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '名取市', note: '全天候型の屋内遊戯施設。体を動かす遊具や0〜3歳向け知育コーナーも。', budget: 'mid',
      summerCool: true, },
    { name: '蔵王ハートランド', category: 'farm', place: 'outdoor', ages: ['2-3', '4-6'], city: '蔵王町', note: 'ヒツジやヤギとふれあえる牧場。チーズやアイス作り体験もできる。', budget: 'free' },
  ],
  iwate: [
    { name: '小岩井農場', category: 'farm', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '雫石町', note: '遊びの広場に遊具やアスレチック。じゃぶじゃぶ池で水遊びもできる。', budget: 'mid',
      waterPlay: true, },
    { name: '岩手サファリパーク', category: 'zoo', place: 'mixed', ages: ['2-3', '4-6'], city: '一関市', note: 'バスやマイカーで猛獣に大接近。草食動物への餌やりも体験できる。', budget: 'mid' },
    { name: '岩山パークランド', category: 'amusement', place: 'outdoor', ages: ['2-3', '4-6'], city: '盛岡市', note: '小さな子向け遊具から絶叫マシンまでそろう小さな遊園地。観覧車が目印。', budget: 'low' },
    { name: '歴史公園えさし藤原の郷', category: 'museum', place: 'outdoor', ages: ['4-6'], city: '奥州市', note: '平安時代の街並みを再現したテーマパーク。お城や貴族の館を散策できる。', budget: 'mid',
      summerCool: true, },
    { name: '花巻おもちゃ美術館', category: 'museum', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '花巻市', note: '岩手県産の木材を使った屋内体験型ミュージアム。雨の日でも遊べる。', budget: 'low',
      summerCool: true, },
  ],
  akita: [
    { name: '秋田市大森山動物園ミルヴェ', category: 'zoo', place: 'outdoor', ages: ['2-3', '4-6'], city: '秋田市', note: '動物を間近に見ながら遊具でも遊べる動物園。園内をSLが走る。', budget: 'low' },
    { name: '鳥海山 木のおもちゃ館', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '由利本荘市', note: '秋田杉を使った木造校舎の施設。ツリーハウスなど木の遊具がたくさん。', budget: 'low',
      summerCool: true, },
    { name: 'ワンダーキャッスル', category: 'indoor', place: 'indoor', ages: ['2-3', '4-6'], city: '横手市', note: 'トリックアートやデジタル体験のアミューズメント施設。大型アスレチックも。', budget: 'mid',
      summerCool: true, },
    { name: 'サイエンスパーク・能代市子ども館', category: 'museum', place: 'indoor', ages: ['2-3', '4-6'], city: '能代市', note: '入場無料の科学館。プラネタリウムは中学生以下無料で楽しめる。', budget: 'free',
      summerCool: true, },
    { name: '能代エナジアムパーク', category: 'museum', place: 'mixed', ages: ['2-3', '4-6'], city: '能代市', note: '入場無料。発電所の排熱を利用した熱帯植物園やエネルギー学習施設。', budget: 'free',
      summerCool: true, },
    { name: 'ポンポコ山公園', category: 'park', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '八峰町', note: '迫力のローラースライダーが目印。乳幼児向け屋内遊具のパークセンターも。', budget: 'free' },
  ],
  yamagata: [
    { name: 'べにっこひろば', category: 'indoor', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '山形市', note: '年齢別に分かれた施設。屋内のべにっこホールに大型遊具がそろう。', budget: 'free',
      summerCool: true, },
    { name: 'ザ・キッズ 山形イオンモール三川店', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '三川町', note: '0歳から遊べる全天候型の室内遊び場。幼児から小学生まで楽しめる。', budget: 'mid',
      summerCool: true, },
    { name: 'ホースガーデンむらやま', category: 'farm', place: 'mixed', ages: ['2-3', '4-6'], city: '村山市', note: '屋内馬場があり雨や雪でも乗馬体験OK。スタッフが引くひき馬が初心者向け。', budget: 'mid' },
    { name: '月山あさひサンチュアパーク', category: 'park', place: 'outdoor', ages: ['4-6'], city: '鶴岡市', note: 'ブナの森を背景にしたフィールド。ピザ焼きや夏野菜もぎとり体験ができる。', budget: 'low' },
  ],
  fukushima: [
    { name: 'アクアマリンふくしま', category: 'aquarium', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: 'いわき市', note: '「潮目の海」がテーマ。ガラス張りの館内で自然環境を再現した展示が魅力。', budget: 'mid',
      summerCool: true,
      waterPlay: true, },
    { name: 'スパリゾートハワイアンズ', category: 'amusement', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: 'いわき市', note: '東京ドーム6個分の大型屋内レジャー施設。わんぱく広場は未就学児も楽しめる。', budget: 'high',
      summerCool: true, },
    { name: '安達ヶ原ふるさと村', category: 'park', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '二本松市', note: '屋内の元気キッズパークは入場無料。屋外のふわふわドームも人気。', budget: 'free',
      playgroundFeatures: ['fuwafuwa'], },
    { name: '三春の里 田園生活館', category: 'park', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '三春町', note: '滝桜近くの農業公園。芝生の広場やグラウンドゴルフ、体験施設がそろう。', budget: 'free' },
  ],
  niigata: [
    { name: '上越市立水族博物館 うみがたり', category: 'aquarium', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '上越市', note: '日本海をテーマにした大水槽と海中トンネル。マゼランペンギンの数は日本一。', budget: 'mid',
      summerCool: true,
      waterPlay: true, },
    { name: '国営越後丘陵公園', category: 'park', place: 'outdoor', ages: ['0-1', '2-3', '4-6'], city: '長岡市', note: '北陸地方唯一の国営公園。芝生広場や巨大トランポリン、木製遊具が充実。', budget: 'low' },
    { name: 'いくとぴあ食花', category: 'park', place: 'mixed', ages: ['0-1', '2-3', '4-6'], city: '新潟市', note: 'こども創造センターを中心に、花や動物とふれあえる複合施設。', budget: 'free' },
    { name: 'ザ・キッズ 新潟イオン白根店', category: 'indoor', place: 'indoor', ages: ['0-1', '2-3', '4-6'], city: '新潟市', note: '0歳から遊べる全天候型の室内遊び場。幼児から小学生まで対応。', budget: 'mid',
      summerCool: true, },
    { name: 'Jump862', category: 'indoor', place: 'indoor', ages: ['4-6'], city: '新発田市', note: '新潟地区最大級の屋内アスレチックパーク。体を動かす遊具がそろう。', budget: 'mid',
      summerCool: true, },
    { name: '悠久山公園', category: 'park', place: 'outdoor', ages: ['2-3', '4-6'], city: '長岡市', note: '「お山」の愛称で親しまれる公園。小動物園や遊具で1日遊べる。', budget: 'free' },
  ],
};
