// チェーン周辺条件フラグメント（baby-chair/stroller/omutsu/rinyushoku-mochikomi/morning-kosodate）を
// 内容を包含する [chain]-kodzure-koryaku へ 301 統合。死蔵ページの被リンク資産を勝ちページに集約する目的。
// 2026-06-25 記事棚卸し監査に基づき生成（scripts/seo-article-audit.mjs）。
export const ARTICLE_REDIRECTS: { from: string; to: string }[] = [
  { from: 'cocoichi-stroller', to: 'cocoichi-kodzure-koryaku' },
  { from: 'nakau-stroller', to: 'nakau-kodzure-koryaku' },
  { from: 'anrakutei-stroller', to: 'anrakutei-kodzure-koryaku' },
  { from: 'bamiyan-baby-chair', to: 'bamiyan-kodzure-koryaku' },
  { from: 'bamiyan-omutsu', to: 'bamiyan-kodzure-koryaku' },
  { from: 'bamiyan-rinyushoku-mochikomi', to: 'bamiyan-kodzure-koryaku' },
  { from: 'cocoichi-baby-chair', to: 'cocoichi-kodzure-koryaku' },
  { from: 'cocoichi-omutsu', to: 'cocoichi-kodzure-koryaku' },
  { from: 'cocoichi-rinyushoku-mochikomi', to: 'cocoichi-kodzure-koryaku' },
  { from: 'cocos-baby-chair', to: 'cocos-kodzure-koryaku' },
  { from: 'cocos-omutsu', to: 'cocos-kodzure-koryaku' },
  { from: 'cocos-rinyushoku-mochikomi', to: 'cocos-kodzure-koryaku' },
  { from: 'cocos-stroller', to: 'cocos-kodzure-koryaku' },
  { from: 'costco-baby-chair', to: 'costco-kodzure-koryaku' },
  { from: 'costco-stroller', to: 'costco-kodzure-koryaku' },
  { from: 'doutor-morning-kosodate', to: 'doutor-kodzure-koryaku' },
  { from: 'gusto-baby-chair', to: 'gusto-kodzure-koryaku' },
  { from: 'gusto-omutsu', to: 'gusto-kodzure-koryaku' },
  { from: 'gyukaku-baby-chair', to: 'gyukaku-kodzure-koryaku' },
  { from: 'gyukaku-omutsu', to: 'gyukaku-kodzure-koryaku' },
  { from: 'jonathan-omutsu', to: 'jonathan-kodzure-koryaku' },
  { from: 'jonathan-rinyushoku-mochikomi', to: 'jonathan-kodzure-koryaku' },
  { from: 'matsuya-rinyushoku-mochikomi', to: 'matsuya-kodzure-koryaku' },
  { from: 'matsuya-stroller', to: 'matsuya-kodzure-koryaku' },
  { from: 'nakau-omutsu', to: 'nakau-kodzure-koryaku' },
  { from: 'nakau-rinyushoku-mochikomi', to: 'nakau-kodzure-koryaku' },
  { from: 'ohsho-omutsu', to: 'ohsho-kodzure-koryaku' },
  { from: 'royal-host-morning-kosodate', to: 'royal-host-kodzure-koryaku' },
  { from: 'royal-host-omutsu', to: 'royal-host-kodzure-koryaku' },
  { from: 'royal-host-rinyushoku-mochikomi', to: 'royal-host-kodzure-koryaku' },
  { from: 'starbucks-morning-kosodate', to: 'starbucks-kodzure-koryaku' },
  { from: 'sukiya-omutsu', to: 'sukiya-kodzure-koryaku' },
  { from: 'sukiya-rinyushoku-mochikomi', to: 'sukiya-kodzure-koryaku' },
  { from: 'sukiya-stroller', to: 'sukiya-kodzure-koryaku' },
  { from: 'sushiro-omutsu', to: 'sushiro-kodzure-koryaku' },
  { from: 'sushiro-rinyushoku-mochikomi', to: 'sushiro-kodzure-koryaku' },
  { from: 'sushiro-stroller', to: 'sushiro-kodzure-koryaku' },
  { from: 'yakiniku-king-baby-chair', to: 'yakiniku-king-kodzure-koryaku' },
  { from: 'yakiniku-king-omutsu', to: 'yakiniku-king-kodzure-koryaku' },
  { from: 'yakiniku-king-stroller', to: 'yakiniku-king-kodzure-koryaku' },
  { from: 'yayoiken-baby-chair', to: 'yayoiken-kodzure-koryaku' },
  { from: 'yoshinoya-omutsu', to: 'yoshinoya-kodzure-koryaku' },
  { from: 'yoshinoya-rinyushoku-mochikomi', to: 'yoshinoya-kodzure-koryaku' },
  { from: 'yoshinoya-stroller', to: 'yoshinoya-kodzure-koryaku' },
  // 「いつから」完全重複ペアの統合（牛肉・国内旅行）
  { from: 'kodomo-gyu-itsukara', to: 'kodomo-gyuniku-itsukara' },
  { from: 'kodomo-kokunai-ryokou-itsukara', to: 'kodomo-kokunai-ryoko-itsukara' },
];
