/**
 * チェーン×子連れ設備の構造化DB（単一データソース）。
 *
 * 戦略(docs/strategy-2026-07.md §15): 「記事の束」でなく「チェーン×設備の
 * 構造化データを持つメディア」になるための土台。判定ボックス・比較表・
 * 構造化データをここから自動生成し、記事ごとの手書き表の不整合と鮮度切れを
 * 構造的に無くす。
 *
 * データの出自: 各チェーン攻略記事の子連れチェックリスト表を 2026-07-02 に
 * 集約・相互照合したもの。値の根拠は公式サイト・店舗公開情報。
 * 値を更新したら該当チェーンの verifiedAt も必ず更新すること。
 *
 * 注意(2026-07-27): verifiedMethod は以前「編集部調査(実訪問・公式サイト照合)の集約」と
 * 表示していたが、裏付けのない実訪問の主張だったため「公式サイト・店舗公開情報の照合」に修正した。
 * **実際に運営者が訪問して確認した内容に限り** verifiedMethod に実訪問を明記してよい
 * (2026-08-11 追記)。行っていないチェーンに実地調査の主張を書き戻さないこと。
 * スポット(施設)側の実訪問レポートは従来どおり lib/kid-reports.ts が正。
 *
 * チェーンの /spot/[slug] は lib/chain-spot-redirects.ts で記事へ 301 するため、
 * チェーンの一次情報が読者に届く場所は**記事本文**。ここのデータは記事の判定ボックスを
 * 駆動するだけなので、体験談そのものは該当記事の「我が家のリアル」節に書くこと。
 */

export type FacilityKey =
  | 'stepFree'
  | 'zashiki'
  | 'boxSeat'
  | 'kidsChair'
  | 'kidsMenu'
  | 'kidsCutlery'
  | 'diaperTable'
  | 'nursingRoom'
  | 'babyFoodBringIn'
  | 'toriwake'
  | 'strollerToSeat'
  | 'allergenInfo';

export const FACILITY_LABELS: Record<FacilityKey, string> = {
  stepFree: '入口の段差なし',
  zashiki: '座敷席',
  boxSeat: 'ボックス席',
  kidsChair: 'キッズチェア',
  kidsMenu: 'キッズメニュー',
  kidsCutlery: '子供用カトラリー',
  diaperTable: 'おむつ替え台',
  nursingRoom: '授乳室',
  babyFoodBringIn: '離乳食持ち込み',
  toriwake: '取り分けOK',
  strollerToSeat: 'ベビーカーで席まで',
  allergenInfo: 'アレルゲン表示',
};

export type FacilityValue = {
  /** true=あり(✓) / 'partial'=条件付き・店舗差(△) / false=なし(—) */
  ok: boolean | 'partial';
  /** 補足(例: モール内店舗は施設の授乳室を利用) */
  note?: string;
};

export type ChainFacilities = {
  /** チェーン識別子(slug接頭辞のマッチにも使う) */
  key: string;
  /** 表示名 */
  name: string;
  /** 公式サイト(一次情報への発リンク)。確証がないチェーンは未設定=リンク非表示 */
  officialUrl?: string;
  /** 攻略記事slug(このページで判定ボックスをDB駆動に差し替える) */
  koryakuSlug: string;
  /** データの最終確認日(YYYY-MM-DD)。値を変えたら必ず更新 */
  verifiedAt: string;
  /** 確認手段の明示(E-E-A-T) */
  verifiedMethod: string;
  /** 標準12項目。調査未了の項目は省略可(表示されない) */
  items: Partial<Record<FacilityKey, FacilityValue>>;
  /** チェーン固有の追加行(例: ビッくらポン、低アレルゲンメニュー)。md表からの移行時に情報を落とさないため */
  extras?: Array<{ label: string; value: string }>;
};

const V = (ok: boolean | 'partial', note?: string): FacilityValue => (note ? { ok, note } : { ok });

export const CHAIN_FACILITIES: ChainFacilities[] = [
  {
    key: 'ohsho',
    name: '餃子の王将',
    officialUrl: 'https://www.ohsho.co.jp/',
    koryakuSlug: 'ohsho-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(false, '店舗差が大きい'),
      zashiki: V(false),
      boxSeat: V(false, '店舗による'),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false, '店舗による'),
      diaperTable: V(false, '店舗による'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(false, '店舗差が大きい'),
      allergenInfo: V(true),
    },
  },
  {
    key: 'saizeriya',
    name: 'サイゼリヤ',
    officialUrl: 'https://www.saizeriya.co.jp/',
    koryakuSlug: 'kodzure-saize-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false, 'モール内店舗は施設の授乳室を利用'),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'gusto',
    name: 'ガスト',
    officialUrl: 'https://www.skylark.co.jp/gusto/',
    koryakuSlug: 'gusto-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'bamiyan',
    name: 'バーミヤン',
    officialUrl: 'https://www.skylark.co.jp/bamiyan/',
    koryakuSlug: 'bamiyan-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'yayoiken',
    name: 'やよい軒',
    officialUrl: 'https://www.yayoiken.com/',
    koryakuSlug: 'yayoiken-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(false, '店舗による'),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(false, '店舗による'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(false, '店舗差が大きい'),
      allergenInfo: V(true),
    },
  },
  {
    key: 'cocos',
    name: 'ココス',
    officialUrl: 'https://www.cocos-jpn.co.jp/',
    koryakuSlug: 'cocos-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'hama-sushi',
    name: 'はま寿司',
    officialUrl: 'https://www.hama-sushi.co.jp/',
    koryakuSlug: 'hama-sushi-kodzure-koryaku',
    verifiedAt: '2026-08-11',
    verifiedMethod: '公式サイト・店舗公開情報の照合＋運営者の実訪問',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true, '運営者が訪問した店舗では股下ベルト付きのハイチェアを使用。別店舗ではテーブル固定タイプもあった。型・ベルトの有無はチェーンとして公式に規定されておらず店舗差あり。腰すわり後が目安'),
      kidsMenu: V(true),
      kidsCutlery: V(false, '店舗による'),
      diaperTable: V('partial', '店舗差が大きい。商業施設内の店舗は施設のトイレ、ロードサイド店は店内トイレと条件が変わる'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '持ち込み可の利用報告あり。店内でのベビーフード販売はなく、温めの全店対応も確認できていないため、持参しておくのが安全'),
      toriwake: V(true),
      strollerToSeat: V('partial', '店舗・席次第'),
      allergenInfo: V(true),
    },
    extras: [
      { label: 'はまっこ3点セット', value: '460円（税込506円）／うどん・ポテト（ミニ）・専用コイン付き' },
      { label: 'はまっこラーメンセット', value: '400円（税込440円）／専用コイン付き' },
      { label: 'はまっこうどんセット', value: '360円（税込396円）／専用コイン付き' },
      { label: 'はまっこポテトセット', value: '290円（税込319円）／ミニサイズ・専用コイン付き' },
      { label: 'はまっこセットの対象年齢', value: '公式に「対象年齢：3歳以上」と明記。持ち帰り不可' },
      { label: '専用コイン', value: 'コイン1枚で店内のカプセルトイを1回。持ち帰り不可・当日使用。景品は店舗により異なる' },
      { label: '価格の注意', value: '店舗により価格が異なる場合あり' },
    ],
  },
  {
    key: 'sushiro',
    name: 'スシロー',
    officialUrl: 'https://www.akindo-sushiro.co.jp/',
    koryakuSlug: 'sushiro-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false, '店舗による'),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'kura-sushi',
    name: 'くら寿司',
    officialUrl: 'https://www.kurasushi.co.jp/',
    koryakuSlug: 'kura-sushi-kodzure-koryaku',
    verifiedAt: '2026-08-11',
    verifiedMethod: '公式サイト・店舗公開情報の照合＋運営者の実訪問',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true, '運営者が訪問した店舗ではソファ席に置くローチェア型で、腰と股を固定するベルト付き。テーブル固定タイプもあった。型・ベルトの有無・台数は店舗差。腰すわり後が目安（月齢はくら寿司公式の規定ではない）'),
      kidsMenu: V(true, '「◯歳以下限定のキッズプレート」ではなく、子どもが食べやすい単品とビッくらポン系が中心'),
      kidsCutlery: V(false, '店舗による'),
      diaperTable: V('partial', '公式の店舗検索で「多機能トイレ対応」を条件指定できる。ただし多機能トイレ＝おむつ交換台ありとは限らない。運営者の訪問では、新型店は多目的トイレ内に広めの折りたたみ交換台があり、旧型店は女性トイレに簡易台のみだった'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '持ち込み可の利用報告あり。専用のベビーフードは販売しておらず、温めの全店対応も確認できていない'),
      toriwake: V(true),
      strollerToSeat: V('partial', '店舗・席次第'),
      allergenInfo: V(true),
    },
    extras: [
      { label: '天然だしうどん', value: '250円' },
      { label: 'ミニころチキン', value: '170円' },
      { label: 'ビッくらポン！厳選6貫セット', value: '790円（まぐろ・ビントロ・サーモン・はまち・いか・えび／景品1個つき）' },
    ],
  },
  {
    key: 'jonathan',
    name: 'ジョナサン',
    officialUrl: 'https://www.skylark.co.jp/jonathan/',
    koryakuSlug: 'jonathan-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '温め依頼OK'),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'marugame',
    name: '丸亀製麺',
    officialUrl: 'https://www.marugame-seimen.com/',
    koryakuSlug: 'marugame-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(false),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(false),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'yoshinoya',
    name: '吉野家',
    officialUrl: 'https://www.yoshinoya.com/',
    koryakuSlug: 'yoshinoya-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial'),
      zashiki: V(false),
      boxSeat: V('partial'),
      kidsChair: V('partial'),
      kidsMenu: V(true),
      kidsCutlery: V('partial'),
      diaperTable: V(false),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V('partial'),
      allergenInfo: V(true),
    },
  },
  {
    key: 'veloce',
    name: 'ベローチェ',
    koryakuSlug: 'veloce-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial'),
      zashiki: V(false),
      boxSeat: V('partial'),
      kidsChair: V(false),
      kidsMenu: V(false),
      kidsCutlery: V(false),
      diaperTable: V(false),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V('partial'),
      allergenInfo: V('partial'),
    },
  },
  {
    key: 'steak-gusto',
    name: 'ステーキガスト',
    koryakuSlug: 'steak-gusto-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
    extras: [
      { label: 'サラダバー', value: '✓' },
      { label: 'カレーバー', value: '✓' },
      { label: '配膳ロボット', value: '✓' },
    ],
  },
  {
    key: 'zetteria',
    name: 'ゼッテリア',
    officialUrl: 'https://www.zetteria.jp/',
    koryakuSlug: 'zetteria-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V(true, 'おもちゃ付きあり'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, '公式サイトで栄養成分・アレルゲン情報を確認可'),
    },
    extras: [
      { label: 'テーブル席', value: '◯ 店舗による' },
      { label: 'おもちゃ／おまけ付き', value: '◯ キッズメニューに付く' },
      { label: '看板の絶品バーガー', value: '◎ ブランドの核' },
      { label: 'ふるポテ・シェーキ', value: '◯ 旧ロッテリアから引き継ぎ' },
    ],
  },
  {
    key: 'uotami',
    name: '魚民',
    koryakuSlug: 'uotami-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true, '店舗による'),
      zashiki: V(true),
      boxSeat: V(true),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V('partial', '店舗による'),
      kidsCutlery: V(true),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V('partial', '個室次第'),
      allergenInfo: V(true, '公式サイト'),
    },
    extras: [
      { label: '個室', value: '✓（半個室・完全個室）' },
    ],
  },
  {
    key: 'ootoya',
    name: '大戸屋',
    officialUrl: 'https://www.ootoya.com/',
    koryakuSlug: 'ootoya-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'misdo',
    name: 'ミスタードーナツ',
    officialUrl: 'https://www.misterdonut.jp/',
    koryakuSlug: 'misdo-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      kidsChair: V('partial', '店舗による'),
      kidsMenu: V(true, 'グッズ付きキッズセットあり'),
      kidsCutlery: V('partial', '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, 'プライスカード・公式サイトで確認可、準ずる品目はスタッフに依頼で印刷'),
    },
    extras: [
      { label: 'イートイン席', value: '◯ 多くの店舗にあり（テイクアウト中心の店もあり）' },
      { label: 'おもちゃ／グッズ付き', value: '◯ つよいこグラス・メラミンプレート等（時期で変わる）' },
      { label: 'もちもち系の窒息注意', value: '⚠ ポン・デ・リング等は小さくちぎって少量から' },
      { label: '低アレルゲン商品', value: '◯ ふかふか焼きドーナツ等・一部店舗・要確認' },
    ],
  },
  {
    key: 'kourakuen',
    name: '幸楽苑',
    officialUrl: 'https://www.kourakuen.co.jp/',
    koryakuSlug: 'kourakuen-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true, 'ロードサイド店は段差が少なめ（店舗による'),
      boxSeat: V(true, '郊外型はボックス席が多い'),
      kidsChair: V(true, '用意がある店が多い（店舗による'),
      kidsCutlery: V(true, '取り皿の用意あり（店舗による'),
      kidsMenu: V(true, 'お子様らーめん・お子様セットあり'),
      allergenInfo: V(true, '公式サイトでメニューごとに確認可'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨（店舗による'),
    },
    extras: [
      { label: 'おもちゃ', value: '◯ お子様セットにカプセルコイン付き（時期・店舗による）' },
      { label: '駐車場', value: '◎ ロードサイド店は駐車場あり' },
      { label: '熱々スープの温度', value: '⚠ 取り分けは薄めて冷ます（やけど注意）' },
      { label: '塩分', value: '⚠ スープは飲み干さない・薄める' },
      { label: '長い麺', value: '⚠ 短く切る・すすらせない' },
      { label: '卵・小麦・そばアレルギー', value: '⚠ 麺・スープ・トッピングで異なる。要確認' },
    ],
  },
  {
    key: 'kfc',
    name: 'ケンタッキー',
    officialUrl: 'https://www.kfc.co.jp/',
    koryakuSlug: 'kfc-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      kidsChair: V('partial', '店舗による'),
      kidsMenu: V(true, 'カーネルグッズ付きあり'),
      kidsCutlery: V('partial', '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, '公式サイトで栄養成分・アレルゲン情報（PDF）を確認可'),
    },
    extras: [
      { label: 'イートイン席', value: '△ 店舗による（テイクアウト中心の店もあり）' },
      { label: 'おもちゃ／おまけ付き', value: '◯ キッズセットにカーネルグッズが付く' },
      { label: '骨なしメニュー', value: '◎ 骨なしケンタッキー・カーネルクリスピー・ナゲット' },
      { label: '低アレルゲンチキンセット', value: '◯ 一部店舗・要確認' },
    ],
  },
  {
    key: 'mos-burger',
    name: 'モスバーガー',
    officialUrl: 'https://www.mos.jp/',
    koryakuSlug: 'mos-burger-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V(true, 'モスワイワイセットあり'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, '公式サイト・PDFで28品目を確認可'),
    },
    extras: [
      { label: 'テーブル席', value: '◯ 多め・落ち着ける' },
      { label: 'おもちゃ付き', value: '◯ ワイワイセットに付属' },
      { label: '低アレルゲンメニュー', value: '◎ 8大アレルゲン不使用メニューあり' },
    ],
  },
  {
    key: 'yumean',
    name: '夢庵',
    koryakuSlug: 'yumean-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(true),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V('partial', '座敷席は畳む'),
      allergenInfo: V(true),
    },
    extras: [
      { label: '和食お子様御膳', value: '✓' },
      { label: '法事・お祝い対応', value: '✓' },
    ],
  },
  {
    key: 'royal-host',
    name: 'ロイヤルホスト',
    officialUrl: 'https://www.royalhost.jp/',
    koryakuSlug: 'royal-host-kodzure-koryaku',
    verifiedAt: '2026-08-11',
    verifiedMethod: '公式サイト・店舗公開情報の照合＋運営者の実訪問',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true, 'テーブル取付型を使った利用事例あり。全店が同じ型ではないため腰すわり後が基本'),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V('partial', '店舗差が大きい'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '持ち込みに加えて店内でベビーフードを注文できる。運営者の訪問では食器に移して温かい状態で提供され、哺乳瓶用のお湯と子ども用エプロンも用意されていた'),
      toriwake: V(true),
      strollerToSeat: V(true, 'ボックス席・ソファ席の店舗が多く合わせやすい'),
      allergenInfo: V(true),
    },
    extras: [
      { label: 'ベビーフード かぼちゃのグラタン', value: '7か月頃から・税込253円' },
      { label: 'ベビーフード ひらめのリゾット', value: '9か月頃から・税込253円' },
      { label: 'ベビーフードの提供方法', value: '食器に移して温めて提供。運営者の訪問でも温かい状態で出てきた。哺乳瓶用のお湯と子ども用エプロンも用意されていた' },
      { label: 'おこさま煮込みハンバーグプレート', value: '968円' },
      { label: 'おこさまオムライス＆エビフライ', value: '1,078円' },
      { label: 'おこさまドリンクバー', value: '4歳〜小学生以下が対象。3歳以下は無料' },
      { label: 'そのほかのおこさまメニュー', value: '低アレルゲンカレー／パンケーキ／ラーメン' },
    ],
  },
  {
    key: 'matsuya',
    name: '松屋',
    officialUrl: 'https://www.matsuyafoods.co.jp/',
    koryakuSlug: 'matsuya-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial'),
      zashiki: V(false),
      boxSeat: V('partial'),
      kidsChair: V('partial'),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(false),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V('partial'),
      allergenInfo: V(true),
    },
  },
  {
    key: 'burger-king',
    name: 'バーガーキング',
    officialUrl: 'https://www.burgerking.co.jp/',
    koryakuSlug: 'burger-king-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V(true, 'キッズセット3種あり'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, '公式サイトで栄養成分・アレルゲン情報を確認可'),
    },
    extras: [
      { label: 'テーブル席', value: '◯ 広めの店舗が多い' },
      { label: 'おもちゃ／おまけ付き', value: '× 付かない（味重視）' },
      { label: '直火焼きの本格バーガー', value: '◎ フレームグリルが看板' },
    ],
  },
  {
    key: 'komeda',
    name: 'コメダ珈琲店',
    officialUrl: 'https://www.komeda.co.jp/',
    koryakuSlug: 'komeda-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'freshness-burger',
    name: 'フレッシュネスバーガー',
    officialUrl: 'https://www.freshnessburger.co.jp/',
    koryakuSlug: 'freshness-burger-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V(true, 'キッズセットあり（一部店舗除く'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, '公式サイト・PDFで28品目を確認可'),
    },
    extras: [
      { label: 'テーブル席', value: '◯ 多め・落ち着ける' },
      { label: 'おもちゃ／おまけ付き', value: '◯ 絵本コラボのおまけが付く時期あり' },
      { label: '北海道産ポテト・国産鶏', value: '◎ 素材にこだわり' },
    ],
  },
  {
    key: 'cocoichi',
    name: 'CoCo壱番屋',
    officialUrl: 'https://www.ichibanya.co.jp/',
    koryakuSlug: 'cocoichi-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      boxSeat: V(true, '店舗による・多め'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V(true, 'お子さまカレーあり'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      allergenInfo: V(true, '公式サイト・PDFで確認可'),
    },
    extras: [
      { label: '甘口対応', value: '◯ 甘口・お子さま向けあり' },
      { label: '量・辛さの調整', value: '◎ ライス量・辛さ・トッピングを調整可' },
    ],
  },
  {
    key: 'torikizoku',
    name: '鳥貴族',
    officialUrl: 'https://www.torikizoku.co.jp/',
    koryakuSlug: 'torikizoku-kodzure-koryaku',
    verifiedAt: '2026-07-31',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true, '店舗による'),
      zashiki: V('partial', '店舗による'),
      boxSeat: V(true),
      kidsChair: V('partial', '店舗による'),
      kidsCutlery: V(true),
      diaperTable: V('partial'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '要確認'),
      toriwake: V(true),
      strollerToSeat: V('partial', '時間帯・店舗による'),
      allergenInfo: V(true, '公式サイト'),
    },
    extras: [
      // 2026-08-01 に「トリキのお子様プレート」(A唐揚/B焼鳥ムネたれ・各税込390円)が
      // グランドメニュー入り。公式は「通常メニューと同じ味付け、大きさ」と明記。
      { label: 'キッズメニュー', value: '✓ お子様プレート390円（2026/8/1〜・味付けと大きさは大人と同じ）' },
    ],
  },
  {
    key: 'maido-ookini-shokudo',
    name: 'まいどおおきに食堂',
    officialUrl: 'https://www.shokudo.jp/',
    koryakuSlug: 'maido-ookini-shokudo-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V('partial', '店舗による'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V('partial', '取り分け前提'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '一声かけて'),
      toriwake: V(true, '自由度が高い'),
      strollerToSeat: V('partial', '店舗による'),
    },
    extras: [
      { label: 'テーブル席', value: '✓' },
      { label: 'アレルゲン確認', value: '店頭・公式で要確認' },
    ],
  },
  {
    key: 'gyukaku',
    name: '牛角',
    officialUrl: 'https://www.gyukaku.ne.jp/',
    koryakuSlug: 'gyukaku-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(true),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'denny-s',
    name: 'デニーズ',
    officialUrl: 'https://www.dennys.jp/',
    koryakuSlug: 'denny-s-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'shabuyou',
    name: 'しゃぶ葉',
    officialUrl: 'https://www.skylark.co.jp/shabu-you/',
    koryakuSlug: 'shabuyou-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'musashinomori-coffee',
    name: 'むさしの森珈琲',
    koryakuSlug: 'musashinomori-coffee-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true, 'ロードサイド店中心'),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true, '店舗による'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true, '広めボックス席なら横付け可'),
      allergenInfo: V(true, 'すかいらーく公式'),
    },
  },
  {
    key: 'baskin-robbins-31',
    name: 'サーティワン',
    officialUrl: 'https://www.31ice.co.jp/',
    koryakuSlug: 'baskin-robbins-31-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による（商業施設内は段差なしが多い'),
      kidsChair: V('partial', '店舗による'),
      kidsMenu: V(true, 'キッズサイズあり'),
      allergenInfo: V(true, '公式サイトでフレーバーごとに確認可'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨（店舗による'),
    },
    extras: [
      { label: 'イートイン席', value: '△ 店舗による（テイクアウト中心の店も多い）' },
      { label: '自分で味を選べる', value: '◎ 31種類から選べる' },
      { label: 'コーンかカップか選べる', value: '◯ 低年齢はカップ＋スプーンが安心' },
      { label: '冷たさ・糖分の注意', value: '⚠ 1歳以降から少量・ゆっくり' },
      { label: '乳・卵・小麦アレルギー', value: '⚠ コーンに小麦、多くのアイスに乳・卵。要確認' },
      { label: 'お湯サービス', value: '△ 店舗による（要確認）' },
      { label: 'ベビーカー置き場', value: '△ 店舗による' },
      { label: '誕生日ケーキ', value: '◯ アイスクリームケーキ・バラエティボックス' },
    ],
  },
  {
    key: 'mcdonalds',
    name: 'マクドナルド',
    officialUrl: 'https://www.mcdonalds.co.jp/',
    koryakuSlug: 'mcdonalds-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'kappa-sushi',
    name: 'かっぱ寿司',
    officialUrl: 'https://www.kappasushi.jp/',
    koryakuSlug: 'kappa-sushi-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true, '店舗による'),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true, '数少なめ・店舗による'),
      kidsMenu: V(true),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true, '店舗による'),
      allergenInfo: V(true, '公式で確認'),
    },
  },
  {
    key: 'bronco-billy',
    name: 'ブロンコビリー',
    officialUrl: 'https://www.bronco.co.jp/',
    koryakuSlug: 'bronco-billy-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(true),
      diaperTable: V(true),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
    extras: [
      { label: 'サラダバー', value: '✓' },
      { label: '誕生日サービス', value: '✓' },
    ],
  },
  {
    key: 'sukiya',
    name: 'すき家',
    officialUrl: 'https://www.sukiya.jp/',
    koryakuSlug: 'sukiya-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V(true),
      zashiki: V(false),
      boxSeat: V(true),
      kidsChair: V(true),
      kidsMenu: V(true),
      kidsCutlery: V(false),
      diaperTable: V(false),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V(true),
      allergenInfo: V(true),
    },
  },
  {
    key: 'hanamaru-udon',
    name: 'はなまるうどん',
    officialUrl: 'https://www.hanamaruudon.com/',
    koryakuSlug: 'hanamaru-udon-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      toriwake: V(true, 'うどんが主役。つゆを薄めて短く切ればOK'),
    },
    extras: [
      { label: 'お子さまメニュー', value: 'にこはなセット（うどん＋ゼリー＋おもちゃ）。かけ（小）も取り分けベースに便利' },
      { label: '提供スタイル', value: 'セルフ式（注文→受け取り→着席→食器返却を自分で）' },
      { label: '席のタイプ', value: 'テーブル席中心。モール内テナント店は比較的ゆったり' },
      { label: 'ベビーカー', value: '店舗による。モール内テナント店が入りやすい傾向' },
      { label: 'キッズチェア', value: 'ある店舗が多い（モール・ロードサイド型）。要確認' },
      { label: 'アレルギー情報', value: '公式サイトにカロリー・アレルギー・原産地情報を掲載' },
      { label: 'おむつ替え・授乳', value: '店内設備は基本なし。モール内なら館内設備を併用' },
      { label: '予算感', value: '低（かけ小なら数百円から取り分け可）' },
    ],
  },
  {
    key: 'bigboy',
    name: 'ビッグボーイ',
    officialUrl: 'https://www.bigboyjapan.co.jp/',
    koryakuSlug: 'bigboy-kids-menu',
    verifiedAt: '2026-08-11',
    verifiedMethod: '公式サイト・店舗公開情報の照合＋運営者の実訪問',
    items: {
      stepFree: V('partial', '店舗差あり'),
      zashiki: V(false),
      boxSeat: V(true, 'テーブル・ソファ席が中心'),
      kidsChair: V(true, 'ベルト付きか、ハイチェアかソファ用かは店舗差あり。腰すわり後が目安'),
      kidsMenu: V(true, '小学生以下向け。業態（ビッグボーイ／ビッグボーイダイニング）で価格・内容が違う'),
      kidsCutlery: V('partial', '店舗による'),
      diaperTable: V('partial', '店舗差が大きい'),
      nursingRoom: V(false),
      babyFoodBringIn: V(true, '運営者の訪問では持参した離乳食を店内で食べられた。店内でベビーフード（165円）も購入でき、そのときは未開封のまま提供された。持ち込み離乳食の温め対応は全店共通の公式ルールを確認できていないため、必要なら店舗確認を'),
      toriwake: V(true),
      strollerToSeat: V('partial', '店舗・席次第'),
      allergenInfo: V(true, '低アレルゲンおこさまハンバーグあり'),
    },
    extras: [
      { label: 'ベビーフード', value: '165円（税抜150円）。離乳食を忘れても店で買える。運営者の訪問では未開封のまま提供された（ロイヤルホストのように器へ移して温めた状態では出てこない）' },
      { label: 'キッズ手ごねハンバーグ', value: '539円（ビッグボーイダイニングの価格）' },
      { label: 'キッズチーズ手ごねハンバーグ', value: '649円（同上）' },
      { label: 'キッズパンケーキ／うどん／スパゲティ', value: '各429円（同上）' },
      { label: '低アレルゲンおこさまハンバーグ', value: '539円（同上）' },
      { label: '価格の注意', value: '「ビッグボーイ」と「ビッグボーイダイニング」は公式メニューページが別。価格・内容を混ぜないこと' },
    ],
  },
  {
    key: 'bikkuri-donkey',
    name: 'びっくりドンキー',
    officialUrl: 'https://www.bikkuri-donkey.com/',
    koryakuSlug: 'bikkuri-donkey-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial', '店舗による'),
      zashiki: V(false, '椅子席メイン'),
      boxSeat: V(true, '多め'),
      kidsChair: V(true, '店舗による'),
      kidsMenu: V(true, 'お子さまメニューあり'),
      kidsCutlery: V(true, '店舗による'),
      diaperTable: V('partial', '店舗による'),
      nursingRoom: V(false, '基本なし'),
      babyFoodBringIn: V(true, 'ひと声がけ推奨'),
      toriwake: V(true, 'ハンバーグは崩しやすい'),
      strollerToSeat: V(true, 'ロードサイド店は余裕あり'),
      allergenInfo: V(true, '公式サイトで確認可'),
    },
  },
  {
    key: 'nakau',
    name: 'なか卯',
    officialUrl: 'https://www.nakau.co.jp/',
    koryakuSlug: 'nakau-kodzure-koryaku',
    verifiedAt: '2026-07-02',
    verifiedMethod: '公式サイト・店舗公開情報の照合',
    items: {
      stepFree: V('partial'),
      zashiki: V(false),
      boxSeat: V('partial'),
      kidsChair: V('partial'),
      kidsMenu: V(true),
      kidsCutlery: V('partial'),
      diaperTable: V(false),
      nursingRoom: V(false),
      babyFoodBringIn: V(true),
      toriwake: V(true),
      strollerToSeat: V('partial'),
      allergenInfo: V(true),
    },
  },
];

/** 攻略記事slug → チェーンDB。該当なしは null。 */
export function getChainFacilitiesForArticle(slug: string): ChainFacilities | null {
  return CHAIN_FACILITIES.find((c) => c.koryakuSlug === slug) ?? null;
}

/** 比較ハブ等での一覧利用(将来の比較表自動生成用)。 */
export function getAllChainFacilities(): ChainFacilities[] {
  return CHAIN_FACILITIES;
}
