/**
 * 運営者ながみーが実際に子連れで訪問して記録した一次情報レポート集。
 *
 * ※ここに入るのは運営者本人の実体験のみ。口コミ等の二次情報は混ぜない。
 * ※スポット名（キー）は lib/spots.ts の SPOTS 内の name と完全一致させること。
 *   spots.ts 側で name 一致により kidReport が自動マージされる。
 *
 * 経緯: 2026-05 に運営者の写真・記憶をもとに聞き取り。
 *       AdSense スパムポリシー（スケーリングされたコンテンツ）を避け、
 *       E-E-A-T の Experience を強化するための独自一次情報。
 */
import type { KidReport } from './spots';

export const KID_REPORTS: Record<string, KidReport> = {
  // ===== 大きい公園・緑地（東京）=====
  代々木公園: {
    source: 'visited',
    visitAge: '0歳のベビーカー散歩〜2歳ごろ（歩き始めると芝生で少し遊ばせる感じ）',
    strollerNote: '中央広場側は舗装が広くかなり快適。ただし原宿側は人が多く、休日はかなり進みにくい。',
    crowdNote: '昼〜夕方はかなり混む。朝9〜10時台が一番楽。',
    diaperNote: '園内でも最低限できるが、原宿・渋谷側の商業施設を逃げ場にしておくと安心。',
    stayNote: '1〜3時間くらい。',
    cautionNote: 'イベント開催日はかなりカオス。ボール遊びや自転車も多いので動線に注意。',
  },
  新宿御苑: {
    source: 'visited',
    visitAge: '0歳〜2歳ごろの「静かに過ごしたい日」に使いやすい（歩き回るより、ベビーカー散歩と芝生ピクニック向き）',
    strollerNote: '園路が広く段差も少なくかなり回りやすい。レストランや休憩所まわりもベビーカーで入りやすい。',
    crowdNote: '普段は広く人が分散しているが、桜と紅葉シーズンはかなり混む。昼前から一気に増えるので朝イチ〜11時前が快適。',
    diaperNote: 'レストハウス周辺にまとまっていて最低限困らない。花見シーズンは埋まりやすいので授乳ケープがあると安心。',
    stayNote: '0歳なら2時間前後、1〜2歳なら芝生で休憩しながら3〜4時間くらい。',
    cautionNote: '遊具公園ではないので「のんびり過ごす」向き。夏は日陰の少ないエリアが結構暑い。',
  },
  光が丘公園: {
    source: 'visited',
    visitAge: '0歳〜5歳までかなり万能。兄弟連れでも使いやすい',
    strollerNote: '道幅が広くかなり押しやすい。ストレスが少ない。',
    crowdNote: '遊具エリアは昼にかなり混む。午前中はかなり快適。',
    diaperNote: 'サービスセンター周辺が使いやすい。お湯が使えるときもある。',
    stayNote: '2〜5時間。',
    cautionNote: '大型遊具は大きい子も多いので、1〜2歳は少し注意。',
  },
  石神井公園: {
    source: 'visited',
    visitAge: '0〜3歳ごろのお散歩向き（池を見ながらゆっくり過ごす感じ）',
    strollerNote: '基本は押しやすいが、池沿いに一部細道あり。',
    crowdNote: '比較的落ち着いている。午前中はかなり快適。',
    diaperNote: '園内は最低限。駅側の施設をセットで見ておくと安心。',
    stayNote: '1〜2時間。',
    cautionNote: '池沿いは歩き始めの子はかなり注意。',
  },
  善福寺公園: {
    source: 'visited',
    visitAge: '0歳〜2歳ごろの落ち着いたお散歩にちょうどいい（ガヤガヤしておらずベビーカー期に行きやすい）',
    strollerNote: '池の周りをぐるっと回れる。基本は押しやすいが、一部細道や少しガタつく場所あり。',
    crowdNote: 'かなり落ち着いている。午前中は特に静かで過ごしやすい。',
    diaperNote: '最低限の多目的トイレはあるが、授乳は近隣カフェや車内前提で考えておくと安心。',
    stayNote: '1〜2時間くらいがちょうどいい。',
    cautionNote: '池沿いは柵が低い場所があるので、歩き始めは少し注意。',
  },
  野川公園: {
    source: 'visited',
    visitAge: '0歳のピクニック〜4歳ごろまでかなり使いやすい',
    strollerNote: 'メイン園路は押しやすい。ただし芝生や自然エリアに入ると少し大変。',
    crowdNote: 'テントやピクニック客は多いが、公園自体が広いので圧迫感は少ない。午前が快適。',
    diaperNote: 'サービスセンター周辺で対応できる。完全装備ではないので、長時間なら準備して行く方が安心。',
    stayNote: '2〜5時間くらい。かなり長居しやすい。',
    cautionNote: '虫が結構いる。春夏は虫除けがほぼ必須。',
  },
  武蔵野公園: {
    source: 'visited',
    visitAge: '0〜3歳ごろのお散歩向き',
    strollerNote: '比較的押しやすい。自然感はあるが整備されている。',
    crowdNote: 'そこまで混まず、ゆったりしている。',
    diaperNote: '設備は最低限。',
    stayNote: '1.5〜3時間くらい。',
    cautionNote: '売店が少なめなので、飲み物や軽食は持参の方が楽。',
  },
  府中の森公園: {
    source: 'visited',
    visitAge: '1〜5歳ごろにかなり強い',
    strollerNote: '園路が広めでかなり快適、押しやすい。',
    crowdNote: '遊具エリアは昼にかなり人が増える。午前がおすすめ。',
    diaperNote: '多目的トイレあり。困る感じではない。',
    stayNote: '2〜4時間くらい。',
    cautionNote: '夏はかなり暑い。遊具周辺は日陰が少なめ。',
  },
  武蔵国分寺公園: {
    source: 'visited',
    visitAge: '0〜3歳ごろのお散歩向き',
    strollerNote: 'かなり押しやすい。芝生が広め。',
    crowdNote: '比較的穏やか。',
    diaperNote: '設備は最低限。',
    stayNote: '1〜3時間くらい。',
    cautionNote: '遊具目的だと少し物足りないかもしれない。',
  },
  神代植物公園: {
    source: 'visited',
    visitAge: '0〜2歳ごろの散歩にかなり向いている',
    strollerNote: 'とても回りやすい。舗装がきれい。',
    crowdNote: 'バラ園シーズンだけかなり混む。',
    diaperNote: '入口周辺で対応可能。',
    stayNote: '2〜4時間くらい。',
    cautionNote: '子ども向け遊具はないので、「遊ばせる」より自然を見に行く感覚。',
  },
  水元公園: {
    source: 'visited',
    visitAge: '0〜5歳までかなり万能',
    strollerNote: '道幅が広くかなり快適。',
    crowdNote: 'BBQエリア周辺は混むが、それ以外は広いので分散される。',
    diaperNote: '最低限あり。',
    stayNote: '3〜6時間くらいいける。',
    cautionNote: '蚊がかなり多い。夕方は特に強いので虫除け必須。',
  },
  舎人公園: {
    source: 'visited',
    visitAge: '1〜5歳でかなり遊ばせやすい',
    strollerNote: 'かなり良い。広くてストレスが少ない。',
    crowdNote: '大型遊具周辺は混雑する。',
    diaperNote: '比較的整っている。',
    stayNote: '2〜5時間。',
    cautionNote: '夏の照り返しが結構きつい。',
  },
  葛西臨海公園: {
    source: 'visited',
    visitAge: '0〜4歳までかなり行きやすい',
    strollerNote: 'スロープが多くかなり回りやすい。',
    crowdNote: '水族園側は昼にかなり混む。朝がおすすめ。',
    diaperNote: '設備がかなり整っている。',
    stayNote: '半日コースになりやすい。',
    cautionNote: '海風がかなり強い日がある。冬は寒い。',
  },
  '林試の森公園': {
    source: 'visited',
    visitAge: '0〜3歳ごろのお散歩向き',
    strollerNote: '木陰が多くかなり快適。園内に少し坂がある。',
    crowdNote: '比較的落ち着いている。',
    diaperNote: '設備は少なめ。',
    stayNote: '1〜3時間くらい。',
    cautionNote: '園内に少し坂があるので、ベビーカーは少し力がいる場所あり。',
  },

  // ===== 屋内遊び場・乳幼児施設 =====
  東京おもちゃ美術館: {
    source: 'visited',
    visitAge: '0歳後半〜3歳ごろが特にハマりやすい（木のおもちゃが多く、派手に遊ぶよりじっくり触る系。2歳前後がかなり楽しそう）',
    strollerNote: '入口でベビーカーを預ける人がかなり多い。館内はそこまで広くないので、抱っこ紐の方が動きやすい。',
    crowdNote: '土日は昼前からかなり混む。午後は人気エリアの人密度が高い。朝イチ入館がかなり快適。',
    diaperNote: 'しっかり整っていて困らない。赤ちゃん連れが多くスタッフも慣れている。',
    stayNote: '2〜4時間くらい。途中でランチを挟む人も多い。',
    cautionNote: 'ハイハイ期は休日少し気を使う。木のおもちゃを口に入れたがる時期は親がかなり付き添う感じになる。',
  },
  'リトルプラネット（複数）': {
    source: 'visited',
    visitAge: '2歳以降にかなり反応が良い',
    strollerNote: '基本は押せる。',
    crowdNote: '午後にかなり人が増える。',
    diaperNote: 'モールの設備が使えるので安心。',
    stayNote: '1〜2時間。',
    cautionNote: '暗い演出を怖がる子もいる。',
  },
  多摩六都科学館: {
    source: 'visited',
    visitAge: '2〜6歳ごろがかなり楽しい（0〜1歳だと少し早め）',
    strollerNote: 'かなり快適。',
    crowdNote: 'プラネタリウムの前後が混む。',
    diaperNote: '問題なし。',
    stayNote: '3〜5時間。',
    cautionNote: '0〜1歳には展示がやや難しめ。',
  },
  杉並アニメーションミュージアム: {
    source: 'visited',
    visitAge: '3歳以降向き',
    strollerNote: '通路が少し狭め。',
    crowdNote: '比較的空いている。',
    diaperNote: '最低限。',
    stayNote: '1〜2時間。',
    cautionNote: '乳幼児向けの要素は弱め。',
  },
  '0123吉祥寺・0123はらっぱ': {
    source: 'visited',
    visitAge: '0〜3歳にかなり強い',
    strollerNote: '館内はかなり使いやすい。',
    crowdNote: '午前が混みやすい。',
    diaperNote: 'かなり安心感がある。',
    stayNote: '1〜3時間。',
    cautionNote: '地域の利用条件があるので事前確認が必要。',
  },
  '京王あそびの森 HUGHUG': {
    source: 'visited',
    visitAge: '1〜5歳にかなり強い（特に「全力で体を動かしたい日」に良い）',
    strollerNote: '入口で置く人が多め。中は走り回る子が多く、ベビーカー移動メインではない。',
    crowdNote: '休日はかなり混み、昼前にはもう賑やか。朝イチに入ると遊具がかなり快適。',
    diaperNote: 'しっかり整っていて、赤ちゃんスペースもあり安心感が高い。',
    stayNote: '2〜4時間くらい。子によっては全然帰りたがらない。',
    cautionNote: '大型ネット遊具はかなりテンションが上がるので、1〜2歳は付き添い必須。休日午後はかなり体力を使う。',
  },

  // ===== 動物園・水族館・牧場 =====
  すみだ水族館: {
    source: 'visited',
    visitAge: '0歳でも行きやすい（暗い空間が平気なら水槽を見るだけでも反応あり）。1〜3歳ごろはかなり楽しそう',
    strollerNote: 'スロープや通路が広めでかなり回りやすい。置き場もあるが、そのまま押して回る人がかなり多い。',
    crowdNote: '昼前〜午後がかなり混む（特にペンギンエリア）。朝イチか夕方近くが楽。',
    diaperNote: 'ソラマチ全体の設備がかなり強いので安心感がある。館内だけで考えなくていいのが楽。',
    stayNote: '1.5〜3時間くらい。ソラマチを含めると半日コースになりやすい。',
    cautionNote: '休日はベビーカー同士ですれ違いづらい場所が少しある。暗いので最初は怖がる子もいる。',
  },
  'マクセル アクアパーク品川': {
    source: 'visited',
    visitAge: '1歳以降にかなり楽しめる',
    strollerNote: '回れるが館内は暗め。',
    crowdNote: 'イルカショーの前後がかなり混む。',
    diaperNote: '品川駅周辺も含めて安心。',
    stayNote: '2〜4時間。',
    cautionNote: '音と光が苦手な子は少し注意。',
  },
  しながわ水族館: {
    source: 'visited',
    visitAge: '0〜4歳',
    strollerNote: '比較的回りやすい。',
    crowdNote: '午前がかなり快適。',
    diaperNote: '問題なし。',
    stayNote: '1.5〜3時間。',
    cautionNote: '駅から少し遠い。',
  },
  板橋区立こども動物園: {
    source: 'visited',
    visitAge: '1〜4歳',
    strollerNote: '小規模でかなり楽。',
    crowdNote: 'そこまで混まない。',
    diaperNote: '最低限。',
    stayNote: '1〜2時間。',
    cautionNote: 'かなり小さめなので長時間向きではない。',
  },
  '江戸川区自然動物園（行船公園）': {
    source: 'visited',
    visitAge: '1〜5歳',
    strollerNote: 'かなり回りやすい。',
    crowdNote: '無料なので休日は人が多め。昼にかなり増える。',
    diaperNote: '行船公園側が使いやすい。',
    stayNote: '1〜3時間。',
    cautionNote: '昼はかなり人が増える。',
  },
  足立区生物園: {
    source: 'visited',
    visitAge: '1〜6歳',
    strollerNote: '館内はかなり楽。',
    crowdNote: '雨の日が混みやすい。',
    diaperNote: 'あり。',
    stayNote: '2〜4時間。',
    cautionNote: '昆虫エリアが苦手な子もいる。',
  },
  '羽村市動物公園': {
    source: 'visited',
    visitAge: '1〜5歳',
    strollerNote: '小規模で回りやすい。',
    crowdNote: '比較的穏やか。',
    diaperNote: '最低限。',
    stayNote: '2〜3時間。',
    cautionNote: '夏はかなり暑い。',
  },
  マザー牧場: {
    source: 'visited',
    visitAge: '1歳半以降にかなり楽しみやすい（動物への反応がしっかり出てくる頃だと満足度が高い）',
    strollerNote: '想像より坂がかなり多く、ベビーカーを押していると親が普通に疲れる。軽いベビーカーの方が楽。',
    crowdNote: '連休や春はかなり混む。羊イベント前後は人が集中しやすい。朝から行く方が動きやすい。',
    diaperNote: '広い施設だが、主要エリアにはちゃんとある。困る感じではなかった。',
    stayNote: '普通に半日〜1日。昼寝を挟みながら過ごす人が多い。',
    cautionNote: '夏はかなり暑い。広すぎて「全部回ろう」とすると親の体力が先に切れるので、エリアを絞った方が楽。',
  },

  // ===== 博物館・科学館・体験 =====
  日本科学未来館: {
    source: 'visited',
    visitAge: '2歳以降はかなり反応が良い（0〜1歳だと「親が見る場所」寄り）',
    strollerNote: 'かなり快適。エレベーターも広め。',
    crowdNote: '企画展エリアは混む。午前中はかなり回りやすい。',
    diaperNote: 'かなり安心感がある。',
    stayNote: '3〜5時間。',
    cautionNote: '内容によっては幼児には難しい展示も多い。',
  },
  国立科学博物館: {
    source: 'visited',
    visitAge: '3歳以降はかなり楽しみやすい（恐竜好きだとかなり強い）',
    strollerNote: '基本は回れるが、人が多い日は少し大変。',
    crowdNote: 'かなり混む。朝イチ推奨。',
    diaperNote: '問題なし。',
    stayNote: '3〜6時間。',
    cautionNote: '館内がかなり広く、全部見ようとすると親が疲れる。',
  },
  江戸東京たてもの園: {
    source: 'visited',
    visitAge: '1〜5歳ごろ、散歩感覚で楽しめる',
    strollerNote: '屋外はかなり快適だが、古民家の内部は段差が多い。',
    crowdNote: '比較的落ち着いている。',
    diaperNote: '最低限はある。',
    stayNote: '2〜4時間。',
    cautionNote: '夏はかなり暑い。',
  },
  鉄道博物館: {
    source: 'visited',
    visitAge: '2〜6歳でかなり強い（電車好きだと帰りたがらない）',
    strollerNote: 'かなり整っている。',
    crowdNote: '休日はかなり混雑。開館直後がおすすめ。',
    diaperNote: 'かなり安心感がある。',
    stayNote: '半日〜1日。',
    cautionNote: '人気のシミュレーター系は早めの行動が必要。',
  },
  '地下鉄博物館（葛西）': {
    source: 'visited',
    visitAge: '2〜5歳ごろがかなり楽しそう',
    strollerNote: '比較的回りやすい。',
    crowdNote: '鉄道博物館よりかなり穏やか。',
    diaperNote: '最低限あり。',
    stayNote: '2〜4時間。',
    cautionNote: '電車に興味がないと少し早めに飽きる。',
  },
  府中市郷土の森博物館: {
    source: 'visited',
    visitAge: '1〜5歳ごろ',
    strollerNote: '園内が広くて押しやすい。',
    crowdNote: '梅やプラネタリウムの時期は混む。',
    diaperNote: '問題なし。',
    stayNote: '3〜5時間。',
    cautionNote: '自然が多いので虫対策があると安心。',
  },
  // ===== テーマパーク・キャラクター系 =====
  サンリオピューロランド: {
    source: 'visited',
    visitAge: '2〜6歳でかなり強い',
    strollerNote: '回れるが休日はかなり人が多い。ベビーカー置き場を利用する人が多め。',
    crowdNote: '開園直後がかなり重要。',
    diaperNote: 'かなり整っている。',
    stayNote: '半日〜1日。',
    cautionNote: '休日はショー待ちでかなり体力を使う。',
  },
  京王れーるランド: {
    source: 'visited',
    visitAge: '1〜5歳',
    strollerNote: 'かなり楽。',
    crowdNote: '午前がかなり快適。',
    diaperNote: '問題なし。',
    stayNote: '2〜4時間。',
    cautionNote: '規模はそこまで大きくない。',
  },
  '川崎市 藤子・F・不二雄ミュージアム': {
    source: 'visited',
    visitAge: '3歳以降向き',
    strollerNote: '回れるが少し狭め。',
    crowdNote: '予約時間の直後にかなり人が集中する。',
    diaperNote: '問題なし。',
    stayNote: '2〜4時間。',
    cautionNote: 'ドラえもんを知らないと親メインの感覚になりがち。',
  },
  横浜アンパンマンこどもミュージアム: {
    source: 'visited',
    visitAge: '1〜4歳に最強クラス',
    strollerNote: '休日はかなり混むのでベビーカー置き場の利用が多い。置き場の利用者もかなり多い。',
    crowdNote: '朝イチが重要。昼はかなり混雑する。',
    diaperNote: 'かなり安心感が高い。',
    stayNote: '3〜6時間。',
    cautionNote: 'アンパンマン期だと帰れなくなるほど夢中になる。',
  },
  キッザニア東京: {
    source: 'visited',
    visitAge: '3歳以降にかなり向いている',
    strollerNote: '基本はベビーカー置き場を利用。',
    crowdNote: 'かなり混む。予約が重要。',
    diaperNote: '豊洲の施設も含めて安心。',
    stayNote: '半日〜1日。',
    cautionNote: '人気の職業はすぐ埋まる。',
  },

  // ===== 商業施設・大型モール =====
  'グランベリーパーク（南町田）': {
    source: 'visited',
    visitAge: '0〜5歳までかなり使いやすい',
    strollerNote: 'かなり快適。',
    crowdNote: '昼はかなり混む。',
    diaperNote: 'かなり強い（充実している）。',
    stayNote: '半日〜1日。',
    cautionNote: '休日のランチはかなり並ぶ。',
  },
  ららぽーと立川立飛: {
    source: 'visited',
    visitAge: '0〜5歳',
    strollerNote: 'かなり回りやすい。',
    crowdNote: 'フードコートが昼に混雑。',
    diaperNote: 'かなり安心。',
    stayNote: '3〜6時間。',
    cautionNote: '休日は駐車場が混みやすい。',
  },
  'ダイバーシティ東京プラザ': {
    source: 'visited',
    visitAge: '0〜5歳',
    strollerNote: 'かなり回りやすい。',
    crowdNote: '観光客が多め。',
    diaperNote: 'かなり充実。',
    stayNote: '半日〜1日。',
    cautionNote: '休日はエレベーター待ちが長い。',
  },
  アクアシティお台場: {
    source: 'visited',
    visitAge: '0〜5歳',
    strollerNote: 'かなり回りやすい。',
    crowdNote: '観光客が多め。',
    diaperNote: 'かなり充実。',
    stayNote: '半日〜1日。',
    cautionNote: '休日はエレベーター待ちが長い。',
  },
  '大井町トラックス（OIMACHI TRACKS）': {
    source: 'visited',
    visitAge: '2歳と4歳の兄弟連れで、開業直後（2026年5月）に訪問',
    strollerNote: '通路自体は広くて移動しやすいが、施設が立体的でエレベーターを探すのが少し大変だった。うちはベビーカーより抱っこ紐・ヒップシートのほうが楽だと感じた。',
    crowdNote: '開業直後は施設自体がすごく混んでいて、平日11:30のシズラーでもすでに6組待ち・約30分待ちだった。開業から時間が経ったぶん、今はだいぶ落ち着いているはず。',
    diaperNote: '3Fフードコート内のベビー休憩室を実際に使った。おむつ台3台、授乳個室2室、給湯器・水道・おむつ用ゴミ箱があって困らなかった。',
    stayNote: '3時間ほど。施設の奥に芝生の場所があり、スタバを買ってのんびりしたりご飯を食べたりして過ごした。ショッピング目当てというより、この広場が主役。',
    cautionNote: '雨の日は要注意。吹き抜け部分に雨が入り込んで床が滑りやすかった。芝生も使えないので、雨天ならわざわざここを選ばなくてよいと思う。',
  },
  有明ガーデン: {
    source: 'visited',
    visitAge: '2歳と4歳の兄弟連れで訪問',
    strollerNote: 'キッズ有明ガーデンのある4Fは通路が広く、ベビーカーのままでも移動しやすい。2F・5Fにベビーカー置き場があるので、遊ばせている間は預けて身軽になれる。',
    crowdNote: '土曜は14時前に整理券を取って15:30の回に入れた。その15:30の時点では、すでに17時台の枠まで埋まっていた。平日のほうがかなり狙いやすい。',
    diaperNote: '館内に赤ちゃん休憩室・授乳室があり、ボーネルンド付近（4F）のものが広くて使いやすかった。',
    stayNote: '3時間。5Fにフードコートもあるので、遊ぶ→食べるで滞在が伸ばせる。',
    cautionNote: '土日祝は整理券の枠が思ったより早く埋まる。14時前に取った時点で17時台まで埋まっていたので、土日に行くなら着いてまず整理券を取りに行くほうが安全。',
  },
  '二子玉川ライズ・ショッピングセンター': {
    source: 'visited',
    visitAge: '0〜5歳までかなり強い（隣接の二子玉川公園とセットで）',
    strollerNote: 'かなり優秀。二子玉川公園とあわせて回りやすい。',
    crowdNote: '昼にかなり人が多い。',
    diaperNote: 'かなり安心感が高い。',
    stayNote: '半日コースになりやすい。',
    cautionNote: '休日はランチ難民になりやすい。',
  },
  '吉祥寺アトレ・キラリナ京王吉祥寺': {
    source: 'visited',
    visitAge: '0〜5歳（吉祥寺パルコ・コピス吉祥寺・アトレ吉祥寺あたりの子連れ利用）',
    strollerNote: 'コピス吉祥寺がかなり子連れ向き。',
    crowdNote: '吉祥寺全体が休日かなり混む。',
    diaperNote: 'かなり安心。',
    stayNote: '2〜5時間。',
    cautionNote: '駅周辺はベビーカーだと少し大変。',
  },

  // ===== 近県の定番 =====
  ふなばしアンデルセン公園: {
    source: 'visited',
    visitAge: '1〜6歳までかなり万能',
    strollerNote: '広いが押しやすい。',
    crowdNote: '休日はかなり人気で混む。',
    diaperNote: '問題なし。',
    stayNote: '半日〜1日。',
    cautionNote: '広すぎて親がかなり歩く。',
  },
  '横浜・八景島シーパラダイス': {
    source: 'visited',
    visitAge: '1〜6歳までかなり楽しめる',
    strollerNote: 'かなり回りやすい。',
    crowdNote: 'イルカショー周辺がかなり混む。',
    diaperNote: 'かなり整っている。',
    stayNote: '半日〜1日。',
    cautionNote: '全部回ろうとするとかなり疲れる。',
  },
};
