/**
 * スポットの最寄り駅・アクセスデータ（公開情報で確認済み）。
 *
 * ※ここは各施設の公式サイト・公式アクセスページ・公共交通の公開情報で
 *   確認できた事実のみを入れる。推測で駅名や徒歩分数を埋めない（捏造禁止）。
 * ※キー（スポット名）は lib/spots.ts の name と完全一致させること。
 *   spots.ts 側で name 一致により nearestStation / walkMinutes が自動マージされる。
 *   すでにインラインで nearestStation を持つスポットは尊重し、上書きしない。
 *
 * nearestStation: 日本語駅名（「駅」付き）。spot ページは findStationBySlug で
 *   slug 解決を試み、未解決時はこの値をそのまま表示する（どちらでも正しく表示）。
 * walkMinutes: 最寄り駅からの徒歩分数。バス併用などは accessNote に明記し省略。
 * accessNote: バス・直結・複数路線などの補足（任意）。
 *
 * バッチ（2026-06）: 公式確認スポット287件＋実質スポット343件を計26体の調査
 * エージェントが各施設の公式アクセスページ等でWeb裏取り。確認できなかったもの
 * （未確認・鉄道駅なし・複数店舗チェーン等）は意図的に未登録のまま。
 */

export type SpotAccess = {
  nearestStation: string;
  walkMinutes?: number;
  accessNote?: string;
};

export const SPOT_ACCESS: Record<string, SpotAccess> = {
  "0123吉祥寺・0123はらっぱ": { nearestStation: "吉祥寺駅", walkMinutes: 12, accessNote: "JR・京王吉祥寺駅北口から徒歩約12分" },
  "AOAO SAPPORO": { nearestStation: "大通駅", walkMinutes: 3, accessNote: "札幌市営地下鉄大通駅から徒歩約3分（moyuk SAPPORO内）" },
  "ASOBI PARK": { nearestStation: "宮崎駅", walkMinutes: 3, accessNote: "JR宮崎駅西口直近のKITEN（宮崎グリーンスフィア壱番館）3階。徒歩約3分" },
  "ATCあそびマーレ": { nearestStation: "トレードセンター前駅", walkMinutes: 2, accessNote: "Osaka Metroニュートラム トレードセンター前駅から徒歩約2分。" },
  "BOAT KIDS PARK Mooovi まるがめ": { nearestStation: "丸亀駅", accessNote: "JR丸亀駅から徒歩約27分とやや遠く、徒歩圏外。バス・車利用が便利。" },
  "BOAT KIDS PARK Moooviからつ": { nearestStation: "東唐津駅", walkMinutes: 23, accessNote: "JR筑肥線東唐津駅から徒歩約23分（車約5分、レース開催日は無料シャトルバスあり）" },
  "DMMかりゆし水族館": { nearestStation: "赤嶺駅", accessNote: "沖縄都市モノレール各駅からバス利用。那覇空港からバス約20分、最寄バス停「道の駅豊崎」徒歩約5分（バス利用）" },
  "IKEA Tokyo-Bay（船橋）": { nearestStation: "南船橋駅", walkMinutes: 5, accessNote: "JR京葉線・武蔵野線南船橋駅から徒歩約5分。駅直結に近い。" },
  "JAXA筑波宇宙センター": { nearestStation: "荒川沖駅", accessNote: "JR常磐線荒川沖駅から関鉄バスで「物質材料研究機構」下車徒歩1分。つくばエクスプレスつくば駅からもバス。徒歩は非現実的。" },
  "Jump862": { nearestStation: "西新発田駅", walkMinutes: 5, accessNote: "イオンモール新発田内。JR西新発田駅から徒歩約5分" },
  "LOGOS LAND（ロゴスランド）": { nearestStation: "城陽駅", accessNote: "JR奈良線・城陽駅または近鉄寺田駅から路線バス、「プラムイン城陽」下車" },
  "NACK5スタジアム大宮・大宮公園": { nearestStation: "大宮公園駅", walkMinutes: 10, accessNote: "東武アーバンパークライン大宮公園駅または北大宮駅から徒歩約10分。" },
  "NEWレオマワールド": { nearestStation: "岡田駅", accessNote: "ことでん琴平線岡田駅からタクシー約5分（無料シャトルバスあり）。徒歩圏外。" },
  "The Kids 熊本店": { nearestStation: "荒尾駅", accessNote: "実所在地は荒尾市ゆめタウンシティモール2F。JR大牟田駅からタクシー約25分。車アクセス中心" },
  "The Kids（ザ・キッズ）": { nearestStation: "筒井駅", walkMinutes: 22, accessNote: "青い森鉄道 筒井駅から徒歩約22分。CiiNA CiiNA青森2階。JR青森駅からバス「シーナシーナ青森前」下車も可" },
  "アイエム電子 鳥取砂丘こどもの国": { nearestStation: "鳥取駅", accessNote: "JR鳥取駅から砂丘・岩井行バス約15〜20分「こどもの国入口」下車徒歩10分" },
  "アクアスランド": { nearestStation: "波子駅", walkMinutes: 10, accessNote: "しまね海洋館アクアス敷地内。JR山陰本線波子駅から徒歩10分" },
  "アクアマリンふくしま": { nearestStation: "泉駅", accessNote: "JR常磐線泉駅から路線バスで約15分（バス利用）" },
  "アクアワールド茨城県大洗水族館": { nearestStation: "大洗駅", accessNote: "鹿島臨海鉄道大洗駅から循環バス海遊号で約12分、徒歩圏外" },
  "あぐりの丘": { nearestStation: "道ノ尾駅", accessNote: "周辺に駅はなくJR道ノ尾駅から車約10分、JR長崎駅から長崎バスで約40分（バス利用）" },
  "あしかがフラワーパーク": { nearestStation: "あしかがフラワーパーク駅", walkMinutes: 3, accessNote: "JR両毛線あしかがフラワーパーク駅から徒歩約3分" },
  "あそ☆ビバ": { nearestStation: "内牧駅", accessNote: "JR豊肥本線内牧駅から約4.5km・徒歩約58分。あそ☆ビバ前バス停から徒歩約2分。徒歩圏外" },
  "あそびの森 かほっくる": { nearestStation: "横山駅", walkMinutes: 17, accessNote: "IRいしかわ鉄道 横山駅から約1.4km・徒歩約17分" },
  "あそびパーク モラージュ佐賀店": { nearestStation: "佐賀駅", accessNote: "JR佐賀駅バスセンターからバス約15分（モラージュ佐賀内）" },
  "あそび王国ぴぃかぁぶぅ": { nearestStation: "電鉄出雲市駅", walkMinutes: 23, accessNote: "ゆめタウン出雲東館3F。電鉄出雲市駅から徒歩約23分。JR出雲市駅からゆめタウン出雲前へのバスも利用可。" },
  "アドベンチャーワールド": { nearestStation: "白浜駅", accessNote: "JR白浜駅から明光バス約10分「アドベンチャーワールド」下車" },
  "あぶくま洞": { nearestStation: "神俣駅", accessNote: "JR磐越東線神俣駅からタクシー約5分。路線バスなし、徒歩圏外。" },
  "あめるんパーク": { nearestStation: "磯部駅", walkMinutes: 14, accessNote: "北陸鉄道浅野川線磯部駅から徒歩約14分。金沢駅西口からバス便あり" },
  "いおワールドかごしま水族館": { nearestStation: "水族館口駅", walkMinutes: 8, accessNote: "鹿児島市電水族館口電停から徒歩約8分。" },
  "イオンモールむさし村山": { nearestStation: "武蔵砂川駅", accessNote: "西武拝島線武蔵砂川駅から南へ約1.8km、バス利用が便利" },
  "いくとぴあ食花": { nearestStation: "新潟駅", accessNote: "JR新潟駅南口からバス「いくとぴあ食花前」下車。最寄りの越後石山駅からは徒歩約57分で徒歩圏外" },
  "いしかわ動物園": { nearestStation: "能美根上駅", accessNote: "IRいしかわ鉄道能美根上駅からのみバス乗継等で約35分、徒歩圏外" },
  "いわき市石炭・化石館 ほるる": { nearestStation: "湯本駅", walkMinutes: 10, accessNote: "JR常磐線湯本駅から徒歩約10分。" },
  "うだ・アニマルパーク": { nearestStation: "榛原駅", accessNote: "近鉄榛原駅からバス約12分、五十軒下車徒歩約5分。徒歩圏外でバス利用。" },
  "うみたまご": { nearestStation: "別府駅", accessNote: "JR別府駅から大分交通バス約15分、「高崎山自然動物園前」下車徒歩3〜5分" },
  "えひめこどもの城": { nearestStation: "松山市駅", accessNote: "伊予鉄松山市駅3番のりばから伊予鉄バス「えひめこどもの城」行きで下車。徒歩圏外。" },
  "えひめ森林公園": { nearestStation: "いよ横田駅", accessNote: "JR予讃線いよ横田駅から約4km・徒歩約1時間。伊予市中心部から車約10分。徒歩圏外" },
  "おきなわワールド": { nearestStation: "旭橋駅", accessNote: "ゆいレール旭橋駅・那覇バスターミナルからバスで玉泉洞前下車。鉄道駅から徒歩不可。" },
  "おさかな館": { nearestStation: "松丸駅", walkMinutes: 3, accessNote: "JR予土線松丸駅から徒歩約3分。※施設は愛媛県松野町の虹の森公園内（入力locの大洲市は誤り）。" },
  "おたる水族館": { nearestStation: "小樽駅", accessNote: "JR小樽駅前から中央バス約20〜25分、終点おたる水族館下車" },
  "おやつタウン": { nearestStation: "久居駅", accessNote: "近鉄名古屋線 久居駅から三重交通バス約15分、おやつタウン前下車徒歩約5分（バス利用）" },
  "カクヒログループスーパーアリーナ キッズルーム": { nearestStation: "青森駅", accessNote: "JR青森駅から約2.3km。バス利用が一般的で徒歩圏外（徒歩約28分）。" },
  "かざこし子どもの森公園": { nearestStation: "飯田駅", walkMinutes: 23, accessNote: "JR飯田線飯田駅から徒歩約23分。飯田ICから車約9分" },
  "かにっこ館": { nearestStation: "鳥取駅", accessNote: "JR鳥取駅から日ノ丸バス賀露循環線で「かにっこ館前」下車（約40分）" },
  "カンドゥー（イオンモール幕張新都心）": { nearestStation: "幕張豊砂駅", walkMinutes: 1, accessNote: "JR京葉線幕張豊砂駅から徒歩約1分（イオンモール幕張新都心内）" },
  "キッザニア福岡": { nearestStation: "竹下駅", walkMinutes: 9, accessNote: "JR鹿児島本線「竹下駅」からららぽーと福岡まで徒歩約9分" },
  "キッズプラザ大阪": { nearestStation: "扇町駅", walkMinutes: 1, accessNote: "Osaka Metro堺筋線扇町駅2号出口すぐ、JR天満駅から徒歩約3分。" },
  "キッズユーエスランド 牛久店": { nearestStation: "ひたち野うしく駅", walkMinutes: 2, accessNote: "JRひたち野うしく駅から徒歩約2分（西友ひたち野うしく店2F）" },
  "キッズユーエスランド 佐賀大和店": { nearestStation: "佐賀駅", accessNote: "JR佐賀駅からバス約5分（イオンモール佐賀大和内）、徒歩圏外" },
  "キッズランドUS フジグラン山口店": { nearestStation: "大歳駅", walkMinutes: 17, accessNote: "JR山口線大歳駅から徒歩約17分。フジグラン山口店1F" },
  "キッズランドUS 大阪ベイタワー店": { nearestStation: "弁天町駅", walkMinutes: 2, accessNote: "JR・大阪メトロ弁天町駅直結の大阪ベイタワーイースト7F" },
  "キッズランドUS 大分由布挾間店": { nearestStation: "向之原駅", walkMinutes: 20, accessNote: "イオン挾間店2階。JR久大本線向之原駅から徒歩約20分" },
  "キッズランドUS 奈良香芝店": { nearestStation: "近鉄下田駅", walkMinutes: 4, accessNote: "近鉄大阪線「近鉄下田駅」より徒歩約4分" },
  "キッズランドUS南宮崎店": { nearestStation: "南宮崎駅", walkMinutes: 7, accessNote: "JR日豊本線南宮崎駅から徒歩約7分（イオン南宮崎3F）。" },
  "キッズワールド名取店": { nearestStation: "名取駅", walkMinutes: 5, accessNote: "JR名取駅西口から徒歩約5分（ホームセンタームサシ名取店2階）" },
  "キドキドよみうりランド店": { nearestStation: "京王よみうりランド駅", accessNote: "京王よみうりランド駅からゴンドラまたはバスで約10分（よみうりランド内）。直接の徒歩は困難。" },
  "ぎふワールド・ローズガーデン": { nearestStation: "可児駅", accessNote: "JR可児駅・名鉄新可児駅からバスまたはタクシー約10分" },
  "ぎふ清流里山公園": { nearestStation: "美濃太田駅", accessNote: "JR美濃太田駅からあい愛バスまたはタクシー約10分。徒歩圏外、バス・タクシー利用" },
  "グランパーク田町・キッズスペース": { nearestStation: "田町駅", walkMinutes: 5, accessNote: "JR田町駅芝浦口から徒歩約5分" },
  "グランベリーパーク（南町田）": { nearestStation: "南町田グランベリーパーク駅", walkMinutes: 1, accessNote: "東急田園都市線南町田グランベリーパーク駅直結" },
  "ぐりんぱ（富士山2合目）": { nearestStation: "御殿場駅", accessNote: "JR御殿場駅などから富士急行の直行バス利用。富士山2合目で徒歩は非現実的" },
  "ぐりんぱから一足のばして・羽村市動物公園": { nearestStation: "羽村駅", walkMinutes: 20, accessNote: "JR青梅線羽村駅東口から徒歩約20分。コミュニティバス「はむらん」利用も可。" },
  "ぐんまこどもの国": { nearestStation: "三枚橋駅", walkMinutes: 20, accessNote: "東武桐生線三枚橋駅から約1.6km、徒歩約20分" },
  "ぐんまこどもの国児童会館": { nearestStation: "三枚橋駅", walkMinutes: 20, accessNote: "東武桐生線三枚橋駅から約1.6km、徒歩約20分。金山総合公園内" },
  "けいはんな記念公園": { nearestStation: "新祝園駅", accessNote: "近鉄新祝園駅・JR祝園駅からバス約9分、けいはんな記念公園下車すぐ。徒歩圏外。" },
  "コクーンシティ（さいたま新都心）": { nearestStation: "さいたま新都心駅", walkMinutes: 1, accessNote: "JRさいたま新都心駅東口すぐ（駅直結）。" },
  "こどもっちパークかなざわ": { nearestStation: "金沢駅", accessNote: "JR金沢駅からバスで約25分。イオンタウン金沢示野内。" },
  "こどもの国 アクアシスパーク": { nearestStation: "こどもの国駅", walkMinutes: 3, accessNote: "こどもの国線こどもの国駅から徒歩約3分。アクアシスパークは園内施設" },
  "こどもの国（横浜・冬のスケート）": { nearestStation: "こどもの国駅", walkMinutes: 3, accessNote: "こどもの国線こどもの国駅から徒歩約3分。" },
  "こどもの国（横浜）": { nearestStation: "こどもの国駅", walkMinutes: 3, accessNote: "こどもの国線こどもの国駅から徒歩約3分。" },
  "こどもはっち": { nearestStation: "本八戸駅", walkMinutes: 10, accessNote: "JR八戸線本八戸駅から徒歩約10分。八戸中心街ターミナル（八日町）下車すぐ。" },
  "こども創造センター": { nearestStation: "越後石山駅", accessNote: "JR越後石山駅から徒歩約57分で徒歩圏外。新潟駅等から路線バス「いくとぴあ食花前」下車。" },
  "コミュタン福島（福島県環境創造センター交流棟）": { nearestStation: "三春駅", accessNote: "JR磐越東線三春駅から三春町町営バス（無料）で約13分。徒歩圏外でバス利用が基本。" },
  "こもれび森のイバライド": { nearestStation: "牛久駅", accessNote: "JR常磐線牛久駅から無料送迎バス約30分（土日祝のみ）。圏央道稲敷ICから車約10分。徒歩圏外" },
  "こんにゃくパーク": { nearestStation: "上州福島駅", accessNote: "上信電鉄上州福島駅からタクシー約5分。徒歩圏外" },
  "ザ・キッズ 山形イオンモール三川店": { nearestStation: "鶴岡駅", accessNote: "イオンモール三川2F。鶴岡駅から庄内交通バス約26分" },
  "サイエンスパーク・能代市子ども館": { nearestStation: "能代駅", walkMinutes: 20, accessNote: "JR能代駅から徒歩約20分、車で約10分。" },
  "ザキッズ 沖縄パレットくもじ店": { nearestStation: "県庁前駅", walkMinutes: 1, accessNote: "パレットくもじ7F。ゆいレール県庁前駅から徒歩約1分(2F連絡口直結)" },
  "ザキッズ 松山三越店": { nearestStation: "大街道駅", walkMinutes: 1, accessNote: "伊予鉄道城南線大街道停留場すぐ、松山三越内" },
  "ザキッズ 大分トキハ店": { nearestStation: "大分駅", walkMinutes: 5, accessNote: "JR大分駅府内中央口から徒歩約5分（トキハ本店6階）" },
  "さざえ堂": { nearestStation: "飯盛山下駅", walkMinutes: 5, accessNote: "ハイカラさん・あかべぇ「飯盛山下」下車徒歩5分。会津若松駅からは徒歩約15分" },
  "さぬきこどもの国": { nearestStation: "一宮駅", accessNote: "ことでん一宮駅から約8kmでバス利用、徒歩圏外（高松空港隣接）" },
  "サントピアワールド": { nearestStation: "水原駅", accessNote: "JR水原駅からバスで約25分。新潟駅・新津駅から無料シャトルバスや車利用が一般的" },
  "サンピアザ水族館": { nearestStation: "新さっぽろ駅", walkMinutes: 3, accessNote: "札幌市営地下鉄東西線新さっぽろ駅から徒歩約3分。JR新札幌駅からは徒歩約5分。" },
  "サンリオピューロランド": { nearestStation: "多摩センター駅", walkMinutes: 5, accessNote: "京王線・小田急線・多摩モノレール多摩センター駅から徒歩約5分。" },
  "ジブリパーク": { nearestStation: "愛・地球博記念公園駅", walkMinutes: 2, accessNote: "リニモ（東部丘陵線）愛・地球博記念公園駅下車すぐ" },
  "しろとり動物園": { nearestStation: "讃岐白鳥駅", accessNote: "JR高徳線讃岐白鳥駅から徒歩約30分（山道）でタクシー約10分推奨" },
  "スパリゾートハワイアンズ": { nearestStation: "湯本駅", accessNote: "JR常磐線湯本駅から無料送迎シャトルバス約10〜15分" },
  "スモールワールズTOKYO": { nearestStation: "有明テニスの森駅", walkMinutes: 3, accessNote: "ゆりかもめ有明テニスの森駅から徒歩3分。りんかい線国際展示場駅からは徒歩約9分" },
  "スリーエム仙台市科学館": { nearestStation: "旭ヶ丘駅", walkMinutes: 5, accessNote: "仙台市地下鉄南北線・旭ヶ丘駅から徒歩約5分" },
  "セーレンプラネット（福井市自然史博物館分館）": { nearestStation: "福井駅", walkMinutes: 1, accessNote: "JR福井駅前のハピリン5階、徒歩約1分" },
  "そらんぽ四日市（四日市市立博物館・プラネタリウム）": { nearestStation: "近鉄四日市駅", walkMinutes: 3, accessNote: "近鉄四日市駅・あすなろう四日市駅から西へ徒歩約3分。" },
  "タオル美術館": { nearestStation: "今治駅", accessNote: "JR予讃線 今治駅から車で約25分（鉄道駅からは徒歩圏外）" },
  "チームラボプラネッツTOKYO DMM": { nearestStation: "新豊洲駅", walkMinutes: 1, accessNote: "ゆりかもめ新豊洲駅から徒歩約1分。有楽町線豊洲駅からは徒歩約10分。" },
  "チームラボボーダレス（麻布台ヒルズ）": { nearestStation: "神谷町駅", walkMinutes: 2, accessNote: "東京メトロ日比谷線神谷町駅5番出口から徒歩2分（直結）。" },
  "ツインリンクもてぎ（モビリティリゾートもてぎ）": { nearestStation: "茂木駅", accessNote: "真岡鐵道茂木駅からバス約20分またはタクシー約15分。徒歩圏外。" },
  "つくばエキスポセンター": { nearestStation: "つくば駅", walkMinutes: 5, accessNote: "つくばエクスプレスつくば駅A2出口から徒歩約5分。" },
  "つやま自然のふしぎ館": { nearestStation: "津山駅", walkMinutes: 10, accessNote: "JR津山駅から徒歩約10分" },
  "テラスモール湘南": { nearestStation: "辻堂駅", walkMinutes: 1, accessNote: "JR東海道線辻堂駅北口直結" },
  "トーベ・ヤンソンあけぼの子どもの森公園": { nearestStation: "元加治駅", walkMinutes: 20, accessNote: "西武池袋線元加治駅から徒歩約20分" },
  "ときわ動物園": { nearestStation: "常盤駅", walkMinutes: 15, accessNote: "JR宇部線 常盤駅から徒歩約15分" },
  "とくしまファミリーランド": { nearestStation: "徳島駅", accessNote: "JR徳島駅から徳島市バスで約25分、とくしま動物園前下車、徒歩圏外" },
  "とくしま動物園": { nearestStation: "文化の森駅", accessNote: "JR徳島駅または文化の森駅からバスでとくしま動物園前下車（徳島駅から約25分）。徒歩圏外" },
  "とちのきファミリーランド": { nearestStation: "西川田駅", walkMinutes: 15, accessNote: "東武宇都宮線「西川田駅」から徒歩約15分" },
  "とっとり花回廊": { nearestStation: "米子駅", accessNote: "JR米子駅から無料シャトルバスで約25分。" },
  "とべ動物園": { nearestStation: "松山市駅", accessNote: "伊予鉄道松山市駅からバス約35分、とべ動物園前下車徒歩約5分。徒歩圏外でバス利用。" },
  "トリックアートミュージアム高尾山": { nearestStation: "高尾山口駅", walkMinutes: 1, accessNote: "京王高尾線 高尾山口駅から徒歩約1分" },
  "トリムパークかなづ": { nearestStation: "芦原温泉駅", walkMinutes: 15, accessNote: "JR芦原温泉駅から徒歩約15分（車で約5分）。" },
  "トンデミ愛媛": { nearestStation: "古泉駅", walkMinutes: 12, accessNote: "伊予鉄道郡中線「古泉駅」から徒歩約12分。駅から無料巡回バスもあり" },
  "なかがわ水遊園": { nearestStation: "西那須野駅", accessNote: "JR宇都宮線・西那須野駅から関東バス約40分、「田宿」下車徒歩5分" },
  "ナガシマスパーランド": { nearestStation: "桑名駅", accessNote: "桑名駅東口から長島温泉行きバスで約20分、長島温泉下車徒歩約1分。" },
  "なまはげ館": { nearestStation: "男鹿駅", accessNote: "JR男鹿駅から相乗タクシー（なまはげシャトル）約25分。徒歩圏外で要予約。" },
  "ニフレル": { nearestStation: "万博記念公園駅", walkMinutes: 2, accessNote: "大阪モノレール万博記念公園駅から徒歩約2分（EXPOCITY内）。" },
  "ヌマジ交通ミュージアム": { nearestStation: "長楽寺駅", walkMinutes: 5, accessNote: "アストラムライン長楽寺駅から徒歩約5分" },
  "ねぶたの家 ワ・ラッセ": { nearestStation: "青森駅", walkMinutes: 1, accessNote: "JR青森駅から徒歩約1分" },
  "のいち動物公園": { nearestStation: "のいち駅", walkMinutes: 20, accessNote: "土佐くろしお鉄道ごめん・なはり線 のいち駅から徒歩約20分" },
  "のぞみ公園": { nearestStation: "喜々津駅", accessNote: "JR喜々津駅から車で約5分、徒歩約40分で非現実的。" },
  "のとじま水族館": { nearestStation: "和倉温泉駅", accessNote: "JR和倉温泉駅からバスで約20〜30分。車利用が便利。徒歩圏外" },
  "のぼりべつクマ牧場": { nearestStation: "登別駅", accessNote: "JR登別駅からバスで約15分、登別温泉からロープウェイで約7分。" },
  "ハーモニーランド": { nearestStation: "杵築駅", accessNote: "JR杵築駅・暘谷駅・日出駅から路線バスで約10分。徒歩圏外" },
  "ハイジの村": { nearestStation: "韮崎駅", accessNote: "JR中央線韮崎駅からバス約30分またはタクシー約20分。徒歩圏外。" },
  "ハウステンボス": { nearestStation: "ハウステンボス駅", walkMinutes: 6, accessNote: "JR大村線「ハウステンボス駅」から徒歩約6分" },
  "はまぎん こども宇宙科学館": { nearestStation: "洋光台駅", walkMinutes: 3, accessNote: "JR京浜東北・根岸線洋光台駅から徒歩3分。" },
  "ピュアハートキッズランド フレスポしんかな": { nearestStation: "新金岡駅", walkMinutes: 3, accessNote: "大阪メトロ御堂筋線 新金岡駅から徒歩約3分、フレスポしんかな4階" },
  "ピュアハートキッズランド広島府中": { nearestStation: "天神川駅", walkMinutes: 5, accessNote: "イオンモール広島府中内。JR山陽本線天神川駅から徒歩約5分。" },
  "ピュアハートキッズランド大垣": { nearestStation: "美濃青柳駅", walkMinutes: 23, accessNote: "養老鉄道「美濃青柳駅」から徒歩約23分。JR大垣駅からは名阪近鉄バスで約17分が便利" },
  "ピュアハートキッズランド尼崎つかしん": { nearestStation: "稲野駅", walkMinutes: 5, accessNote: "阪急伊丹線稲野駅から約300m、JR宝塚線猪名寺駅から約400m。" },
  "ピュアハートキッズランド伏見桃山": { nearestStation: "六地蔵駅", walkMinutes: 8, accessNote: "JR奈良線・地下鉄東西線六地蔵駅から徒歩約8分（京阪宇治線六地蔵駅からは徒歩約10分）。" },
  "ひらかたパーク": { nearestStation: "枚方公園駅", walkMinutes: 3, accessNote: "京阪電車「枚方公園駅」下車徒歩約3分" },
  "ヒルゼン高原センター ジョイフルパーク": { nearestStation: "中国勝山駅", accessNote: "JR中国勝山駅から蒜山高原行きバス約80分、「蒜山高原センター前」下車すぐ" },
  "ファンタジーキッズリゾート新さっぽろ": { nearestStation: "新さっぽろ駅", walkMinutes: 3, accessNote: "地下鉄東西線新さっぽろ駅・JR新札幌駅から専用通路で徒歩約3分" },
  "ふくふくこども館": { nearestStation: "下関駅", walkMinutes: 3, accessNote: "JR山陽本線下関駅東口から徒歩約1〜3分（リピエ下関3F）" },
  "ふじさんのぬく森キポキポ": { nearestStation: "富士山駅", accessNote: "富士急行線富士山駅から車で約10分。明確な徒歩時間の記載なく徒歩圏外。" },
  "ふなばしアンデルセン公園": { nearestStation: "三咲駅", accessNote: "新京成線三咲駅等からバス「アンデルセン公園」下車。鉄道駅から徒歩圏外でバス利用が基本" },
  "ふなばしアンデルセン公園 にじの池": { nearestStation: "三咲駅", accessNote: "新京成線三咲駅から京成バス（セコメディック病院行き等）でアンデルセン公園下車徒歩1分。徒歩圏外でバス利用。" },
  "プラザ大村 地域子育て支援センター": { nearestStation: "大村駅", walkMinutes: 10, accessNote: "JR大村線「大村駅」から徒歩約10分（市民交流プラザおおむら内）" },
  "ブルーメの丘": { nearestStation: "日野駅", accessNote: "近江鉄道日野駅やJR近江八幡駅からバス、幅野町下車徒歩約10分。徒歩圏外でバス利用。" },
  "フレーベル館 Kinder Platz ガーデン前橋店": { nearestStation: "駒形駅", accessNote: "JR両毛線駒形駅からバス「ガーデン前橋」利用。徒歩は遠く車・バス利用が一般的。" },
  "べにっこひろば": { nearestStation: "羽前千歳駅", walkMinutes: 21, accessNote: "JR羽前千歳駅から約1.8km徒歩約21分。JR山形駅から車約20分やバス利用も可" },
  "ヘルストピア延岡": { nearestStation: "延岡駅", accessNote: "JR延岡駅・南延岡駅から約3.2kmで車で約10分。延岡バスセンターから方財線バス約17分「ヘルストピア延岡」下車。徒歩圏外。" },
  "ホースガーデンむらやま": { nearestStation: "村山駅", accessNote: "JR奥羽本線・山形新幹線村山駅から車で約15分" },
  "ほたるいかミュージアム": { nearestStation: "滑川駅", walkMinutes: 8, accessNote: "あいの風とやま鉄道 滑川駅から徒歩約8分" },
  "ポルトヨーロッパ": { nearestStation: "海南駅", accessNote: "JRきのくに線・海南駅から和歌山バス（マリーナシティ行き）約10分" },
  "ポンポコ山公園": { nearestStation: "鳥形駅", walkMinutes: 18, accessNote: "JR五能線鳥形駅から徒歩約18分" },
  "マザー牧場": { nearestStation: "佐貫町駅", accessNote: "JR内房線佐貫町駅または君津駅からバス約20分、徒歩圏外" },
  "マリホ水族館": { nearestStation: "新井口駅", walkMinutes: 3, accessNote: "2024年12月にアルパーク東棟へ移転し「シン・マリホ水族館」に。JR山陽本線新井口駅から徒歩約3分。" },
  "マリンピア日本海": { nearestStation: "新潟駅", accessNote: "JR新潟駅からバス約20分、水族館前下車すぐ" },
  "マリンワールド海の中道": { nearestStation: "海ノ中道駅", walkMinutes: 5, accessNote: "JR香椎線海ノ中道駅から徒歩約5分" },
  "みかも山公園": { nearestStation: "岩舟駅", accessNote: "JR両毛線岩舟駅から約4kmで徒歩圏外。栃木駅からふれあいバス利用。" },
  "ミキモト真珠島": { nearestStation: "鳥羽駅", walkMinutes: 5, accessNote: "近鉄・JR鳥羽駅から徒歩約5分" },
  "ミュージアムパーク茨城県自然博物館": { nearestStation: "守谷駅", accessNote: "つくばエクスプレス守谷駅西口から関鉄バス約30分「自然博物館入口」下車徒歩約10分。徒歩圏外でバス利用。" },
  "ミラージュランド": { nearestStation: "魚津駅", accessNote: "あいの風とやま鉄道魚津駅から車約10分" },
  "みろくの里": { nearestStation: "福山駅", accessNote: "JR福山駅南口からトモテツバス直行便で約30分（バス利用）" },
  "ムーミンバレーパーク": { nearestStation: "飯能駅", accessNote: "西武池袋線飯能駅北口からメッツァ行きバスで約13分。" },
  "むさしの村": { nearestStation: "南羽生駅", walkMinutes: 19, accessNote: "東武伊勢崎線南羽生駅から徒歩約19分。加須駅から日祝に無料送迎バス運行日あり。" },
  "メリッタKid's TAKEO": { nearestStation: "高橋駅", walkMinutes: 3, accessNote: "JR佐世保線高橋駅から徒歩約3分。" },
  "モエレ沼公園": { nearestStation: "環状通東駅", accessNote: "地下鉄環状通東駅からバス(東69・東79等)でモエレ沼公園東口下車。徒歩圏外、バス利用" },
  "モーリーファンタジー イオンモール大牟田": { nearestStation: "大牟田駅", walkMinutes: 20, accessNote: "西鉄・JR大牟田駅から西へ約1.5km、徒歩約18〜20分" },
  "モニュメントミュージアム 来待ストーン": { nearestStation: "来待駅", walkMinutes: 15, accessNote: "JR山陰本線来待駅から徒歩約10〜15分。" },
  "モヤヒルズ": { nearestStation: "青森駅", accessNote: "JR青森駅から市営バス・JRバス「モヤヒルズ」行きで約50分、終点下車" },
  "モリコロパーク": { nearestStation: "愛・地球博記念公園駅", walkMinutes: 2, accessNote: "リニモ愛・地球博記念公園駅下車すぐ" },
  "やまぎん県民ホール（やまぎんこども館）": { nearestStation: "山形駅", walkMinutes: 1, accessNote: "JR山形駅西口から東西連絡通路経由で徒歩約1分。" },
  "ヤンマーミュージアム": { nearestStation: "長浜駅", walkMinutes: 10, accessNote: "JR北陸本線長浜駅から徒歩約10分" },
  "ユウベルキッズランド熊本店": { nearestStation: "健軍交番前駅", walkMinutes: 19, accessNote: "熊本市電健軍交番前停留場から徒歩約19分" },
  "よこはま動物園ズーラシア": { nearestStation: "中山駅", accessNote: "JR/市営地下鉄中山駅などから「よこはま動物園」行きバスで約15分。" },
  "よみうりランド": { nearestStation: "京王よみうりランド駅", accessNote: "京王相模原線「京王よみうりランド駅」からゴンドラまたはバスで入園。小田急「読売ランド前駅」からは徒歩約10分" },
  "ラウンドワンスタジアム みえ・川越IC店": { nearestStation: "伊勢朝日駅", walkMinutes: 10, accessNote: "近鉄名古屋線伊勢朝日駅から徒歩約10分" },
  "ららぽーと富士見": { nearestStation: "鶴瀬駅", accessNote: "東武東上線鶴瀬駅東口からバス約6分。徒歩だと約21分のためバス利用が一般的。" },
  "ららぽーと立川立飛": { nearestStation: "立飛駅", walkMinutes: 2, accessNote: "多摩モノレール立飛駅とペデストリアンデッキで直結、徒歩約2分" },
  "リカちゃんキャッスル": { nearestStation: "小野新町駅", walkMinutes: 10, accessNote: "JR磐越東線 小野新町駅から徒歩約10分" },
  "リトルプラネット イオンモールKAGOSHIMA BAY": { nearestStation: "上塩屋駅", accessNote: "市電上塩屋駅から徒歩約19分。鹿児島中央駅や市電谷山駅からバス利用が一般的。" },
  "リナワールド": { nearestStation: "茂吉記念館前駅", accessNote: "JRかみのやま温泉駅等から山交バスでリナワールド前下車すぐ。最寄り茂吉記念館前駅から約1.1km。" },
  "りんどう湖ファミリー牧場": { nearestStation: "那須塩原駅", accessNote: "JR那須塩原駅から無料シャトルバス約30分（予約制）" },
  "ルミネ町田": { nearestStation: "町田駅", walkMinutes: 1, accessNote: "JR横浜線町田駅直結、小田急町田駅からも徒歩約5分" },
  "るるパーク（大分農業文化公園）": { nearestStation: "中山香駅", accessNote: "JR日豊本線 中山香駅からタクシー約20分（車・タクシー利用）" },
  "レゴランド・ジャパン": { nearestStation: "金城ふ頭駅", walkMinutes: 8, accessNote: "あおなみ線「金城ふ頭駅」から徒歩約8分" },
  "レゴランド・ディスカバリー・センター東京": { nearestStation: "お台場海浜公園駅", walkMinutes: 2, accessNote: "ゆりかもめお台場海浜公園駅から徒歩2分、りんかい線東京テレポート駅から徒歩5分" },
  "ロクハ公園": { nearestStation: "草津駅", accessNote: "JR草津駅東口から帝産バス（平日のみ）ロクハ荘下車徒歩5分、徒歩圏外" },
  "わらべ館": { nearestStation: "鳥取駅", walkMinutes: 20, accessNote: "JR鳥取駅から徒歩約20分、またはバス約6分" },
  "ワンダーキャッスル": { nearestStation: "横手駅", accessNote: "秋田ふるさと村内にあり所在地は横手市（入力の由利本荘市は誤りの可能性）。JR奥羽本線横手駅からバス約15分。" },
  "わんぱーくこうち": { nearestStation: "桟橋通五丁目駅", walkMinutes: 10, accessNote: "とさでん交通桟橋線桟橋通五丁目電停から徒歩約10分。" },
  "阿蘇 元気の森": { nearestStation: "赤水駅", accessNote: "所在は南阿蘇村。JR豊肥本線赤水駅から車約7分。徒歩圏外で車利用。" },
  "阿蘇カドリー・ドミニオン": { nearestStation: "阿蘇駅", walkMinutes: 20, accessNote: "JR豊肥本線阿蘇駅から徒歩約20分。都市間バス「カドリードミニオン前」下車も可。" },
  "阿蘇ファームランド": { nearestStation: "赤水駅", accessNote: "JR豊肥本線赤水駅から車で約7分（徒歩圏外）" },
  "愛知こどもの国": { nearestStation: "こどもの国駅", walkMinutes: 15, accessNote: "名鉄蒲郡線こどもの国駅から徒歩約15分。" },
  "愛知県児童総合センター": { nearestStation: "愛・地球博記念公園駅", walkMinutes: 6, accessNote: "リニモ・愛・地球博記念公園駅から徒歩約6分（愛・地球博記念公園内）" },
  "愛宕山こどもの国": { nearestStation: "甲府駅", accessNote: "JR甲府駅からタクシー約15分（土日祝・夏季はシャトルバスあり）" },
  "愛宕山ふくろう公園": { nearestStation: "南岩国駅", walkMinutes: 19, accessNote: "JR山陽本線南岩国駅が最寄り。地図上の徒歩ルートで約19分。" },
  "愛媛県総合科学博物館": { nearestStation: "新居浜駅", accessNote: "JR新居浜駅からせとうちバスで約20分、桜木下車。タクシー約15分。" },
  "愛媛県立とべ動物園": { nearestStation: "松山市駅", accessNote: "伊予鉄・松山市駅からバス約35分、「とべ動物園前」下車徒歩約5分" },
  "旭山動物園": { nearestStation: "旭川駅", accessNote: "JR旭川駅東口6番のりばからバス約35〜40分、徒歩圏外（車・バス利用）" },
  "旭川市旭山動物園": { nearestStation: "旭川駅", accessNote: "JR旭川駅東口6番のりばから旭川電気軌道バス約35〜40分、旭山動物園下車（バス利用）" },
  "安佐動物公園": { nearestStation: "上安駅", accessNote: "アストラムライン上安駅から約2.7km。バス「動物公園あさひが丘」下車が基本" },
  "安城産業文化公園デンパーク": { nearestStation: "安城駅", accessNote: "JR東海道本線「安城」駅からあんくるバス乗り継ぎでデンパーク下車。徒歩圏外" },
  "安達ヶ原ふるさと村": { nearestStation: "二本松駅", accessNote: "JR東北本線二本松駅からバス約10分、安達ヶ原下車、徒歩圏外" },
  "伊香保おもちゃと人形 自動車博物館": { nearestStation: "渋川駅", accessNote: "JR渋川駅からバス約16分、徒歩圏外。所在地は実際には吉岡町" },
  "伊香保グリーン牧場": { nearestStation: "渋川駅", accessNote: "JR上越線渋川駅から伊香保温泉行きバス約15分、グリーン牧場前下車徒歩1分。徒歩圏外。" },
  "伊勢シーパラダイス": { nearestStation: "鳥羽駅", accessNote: "JR/近鉄鳥羽駅から約7.4km。CANバス等のバスまたはタクシー利用" },
  "伊豆アニマルキングダム": { nearestStation: "伊豆稲取駅", accessNote: "伊豆急行伊豆稲取駅から東海バス（アニマルキングダム行き）で約10分。徒歩圏外。" },
  "伊豆ぐらんぱる公園": { nearestStation: "伊豆高原駅", accessNote: "伊豆急行線伊豆高原駅から東海バス約10〜20分、または車約10分" },
  "井の頭恩賜公園": { nearestStation: "井の頭公園駅", walkMinutes: 1, accessNote: "京王井の頭線井の頭公園駅から徒歩1分。JR吉祥寺駅からは徒歩5分。" },
  "井の頭自然文化園": { nearestStation: "吉祥寺駅", walkMinutes: 10, accessNote: "JR・京王井の頭線 吉祥寺駅から徒歩約10分" },
  "井の頭自然文化園 ジャブジャブ池": { nearestStation: "吉祥寺駅", walkMinutes: 10, accessNote: "JR・京王吉祥寺駅から徒歩約10分。井の頭公園駅からも徒歩約10分" },
  "茨城県フラワーパーク": { nearestStation: "石岡駅", accessNote: "現名称「いばらきフラワーパーク」。JR常磐線石岡駅からバスで約30分。徒歩圏外、バス利用" },
  "宇都宮市子ども総合科学館": { nearestStation: "西川田駅", walkMinutes: 20, accessNote: "東武宇都宮線西川田駅から徒歩約20分（約1.3km）。施設名は正式には栃木県子ども総合科学館" },
  "宇都宮動物園": { nearestStation: "宇都宮駅", accessNote: "JR宇都宮駅西口からバス約30分、下金井町下車徒歩約5分。東北道宇都宮ICから車約5分" },
  "烏山川緑道 じゃぶじゃぶ池": { nearestStation: "三軒茶屋駅", walkMinutes: 3, accessNote: "東急田園都市線三軒茶屋駅南口Aから徒歩約3分（太子堂付近）" },
  "浦安総合公園": { nearestStation: "備前西市駅", accessNote: "JR備前西市駅から約4.8kmで徒歩不向き。岡山駅から岡電バス約30分「浦安体育館前」下車徒歩5分" },
  "越前松島水族館": { nearestStation: "三国駅", accessNote: "えちぜん鉄道三国駅から京福バス東尋坊方面で約15分「越前松島水族館前」下車。徒歩圏外。" },
  "横浜・八景島シーパラダイス": { nearestStation: "八景島駅", walkMinutes: 8, accessNote: "シーサイドライン八景島駅から徒歩約8分" },
  "岡岳公園": { nearestStation: "松橋駅", walkMinutes: 15, accessNote: "JR鹿児島本線松橋駅から徒歩約15分（所在地は宇城市松橋町）。" },
  "岡山シティミュージアム": { nearestStation: "岡山駅", walkMinutes: 2, accessNote: "JR岡山駅西口向かい、東西連絡通路直結で徒歩約2分。" },
  "岡山県自然保護センター": { nearestStation: "和気駅", accessNote: "実所在地は和気郡和気町（入力locの備前市は誤り）。JR和気駅・熊山駅からタクシー約30分。徒歩圏外" },
  "下関市立しものせき水族館 海響館": { nearestStation: "下関駅", accessNote: "JR下関駅からバスで約7分、海響館前下車徒歩約3分。" },
  "下田海中水族館": { nearestStation: "伊豆急下田駅", accessNote: "伊豆急下田駅からバス約7分、徒歩だと約25分でバス推奨" },
  "加茂水族館": { nearestStation: "鶴岡駅", accessNote: "JR鶴岡駅から庄内交通バス湯野浜温泉行きで約40分、加茂水族館下車" },
  "花巻おもちゃ美術館": { nearestStation: "花巻駅", walkMinutes: 15, accessNote: "JR東北本線花巻駅から徒歩約15分（マルカンビル2階）" },
  "華蔵寺公園": { nearestStation: "伊勢崎駅", walkMinutes: 20, accessNote: "JR・東武伊勢崎駅から徒歩約20分。コミュニティバスでも約6〜14分。" },
  "海の中道海浜公園": { nearestStation: "海ノ中道駅", accessNote: "JR香椎線海ノ中道駅から海の中道駅口へ徒歩すぐ。大芝生広場側はJR西戸崎駅から徒歩約10分。" },
  "海岸公園冒険広場": { nearestStation: "荒井駅", accessNote: "仙台市地下鉄東西線荒井駅からバス約15分＋徒歩。徒歩圏外（バス利用）。" },
  "海響館（下関市立しものせき水族館）": { nearestStation: "下関駅", accessNote: "JR下関駅からバス約7分「海響館前」下車徒歩約3分。徒歩圏外（バス利用）。" },
  "海遊館": { nearestStation: "大阪港駅", walkMinutes: 5, accessNote: "大阪メトロ中央線大阪港駅1番出口から徒歩約5分" },
  "各務原市民公園": { nearestStation: "市民公園前駅", walkMinutes: 3, accessNote: "名鉄各務原線 市民公園前駅から徒歩約3分" },
  "掛川花鳥園": { nearestStation: "掛川駅", walkMinutes: 10, accessNote: "JR掛川駅南口から約800m、徒歩約10分" },
  "笠岡市立カブトガニ博物館・恐竜公園": { nearestStation: "笠岡駅", accessNote: "JR笠岡駅からバス約13〜20分、カブトガニ博物館前下車すぐ（約3.4km）" },
  "笠間芸術の森公園": { nearestStation: "笠間駅", accessNote: "JR水戸線笠間駅から車約5分・徒歩約40分。周遊バスも運行" },
  "橿原市昆虫館": { nearestStation: "香久山駅", accessNote: "近鉄大和八木駅から橿原市コミュニティバス約30分が便利。香久山駅からは徒歩35分でバス利用が基本" },
  "橿原市立こども科学館": { nearestStation: "畝傍御陵前駅", walkMinutes: 15, accessNote: "近鉄畝傍御陵前駅から徒歩約15分（かしはら万葉ホール地下1階）。八木駅等からバス「小房」下車すぐも可。" },
  "鴨川シーワールド": { nearestStation: "安房鴨川駅", accessNote: "JR安房鴨川駅西口から無料送迎バス約10分" },
  "感性の森": { nearestStation: "愛子駅", walkMinutes: 20, accessNote: "JR仙山線 愛子駅から徒歩約20分（バス約4分）。錦ケ丘ヒルサイドモール2F（仙台市青葉区錦ケ丘）" },
  "観音池公園": { nearestStation: "山之口駅", accessNote: "JR日豊本線山之口駅からタクシー約10分" },
  "岩山パークランド": { nearestStation: "盛岡駅", accessNote: "JR盛岡駅からバス約30〜35分、パークランド前下車徒歩約3分" },
  "岩手サファリパーク": { nearestStation: "花泉駅", accessNote: "JR東北本線花泉駅からタクシー約20分。一ノ関ICから車約45分" },
  "岩手県立児童館 いわて子どもの森": { nearestStation: "奥中山高原駅", accessNote: "IGRいわて銀河鉄道奥中山高原駅からバスで約17分。車利用が一般的" },
  "岩手県立児童館いわて子どもの森": { nearestStation: "奥中山高原駅", accessNote: "IGRいわて銀河鉄道奥中山高原駅から県北バス。滝沢ICより車約50分" },
  "岩手県立美術館": { nearestStation: "盛岡駅", walkMinutes: 20, accessNote: "JR盛岡駅西口から徒歩約20分。盛南ループ200バスで「県立美術館前」下車も可。" },
  "岐阜かかみがはら航空宇宙博物館": { nearestStation: "各務原市役所前駅", accessNote: "名鉄各務原市役所前駅からふれあいバスで約15分。車利用が一般的" },
  "岐阜県こどもの国": { nearestStation: "養老駅", walkMinutes: 10, accessNote: "養老鉄道養老駅から養老公園入口まで徒歩約10分（園内のこどもの国まではさらに歩く）。" },
  "亀鶴公園": { nearestStation: "造田駅", accessNote: "JR高徳線造田駅から車約10分。長尾駅からは約3kmで徒歩圏外。さぬき市コミュニティバス利用可。" },
  "吉香公園": { nearestStation: "川西駅", walkMinutes: 22, accessNote: "JR岩徳線川西駅から徒歩約20分強。JR岩国駅からバス約20分「錦帯橋」下車も可。" },
  "吉祥寺アトレ・キラリナ京王吉祥寺": { nearestStation: "吉祥寺駅", accessNote: "JR・京王井の頭線吉祥寺駅直結" },
  "吉野ヶ里歴史公園": { nearestStation: "吉野ヶ里公園駅", walkMinutes: 15, accessNote: "JR長崎本線吉野ヶ里公園駅から徒歩約15分" },
  "宮崎科学技術館": { nearestStation: "宮崎駅", walkMinutes: 2, accessNote: "JR宮崎駅東口から徒歩約2分" },
  "宮崎市フェニックス自然動物園": { nearestStation: "宮崎駅", accessNote: "宮崎駅・宮交シティからバス約30分。鉄道駅から徒歩圏外" },
  "宮城蔵王キツネ村": { nearestStation: "白石蔵王駅", accessNote: "JR白石蔵王駅・白石駅から車約20分。路線バスは火・金のみ運行で徒歩圏外。" },
  "魚津水族館": { nearestStation: "西魚津駅", walkMinutes: 15, accessNote: "富山地鉄本線西魚津駅から徒歩約15分（情報源により10〜20分）" },
  "京王あそびの森 HUGHUG": { nearestStation: "多摩動物公園駅", walkMinutes: 1, accessNote: "京王動物園線・多摩モノレール多摩動物公園駅から徒歩約1分（入力の高幡不動駅前は誤り）" },
  "京王れーるランド": { nearestStation: "多摩動物公園駅", walkMinutes: 1, accessNote: "京王線・多摩モノレール多摩動物公園駅前、徒歩約1分" },
  "京都市動物園": { nearestStation: "蹴上駅", walkMinutes: 5, accessNote: "京都市営地下鉄東西線蹴上駅から徒歩約5分。地下鉄東山駅からは徒歩約10分。" },
  "京都水族館": { nearestStation: "梅小路京都西駅", walkMinutes: 7, accessNote: "JR嵯峨野線梅小路京都西駅から徒歩約7分" },
  "京都鉄道博物館": { nearestStation: "梅小路京都西駅", walkMinutes: 2, accessNote: "JR嵯峨野線梅小路京都西駅から徒歩約2分。" },
  "京都府立 丹波自然運動公園": { nearestStation: "園部駅", accessNote: "JR嵯峨野線 園部駅から中京交通バスに乗換え「丹波自然運動公園」下車" },
  "京都府立植物園": { nearestStation: "北山駅", walkMinutes: 1, accessNote: "地下鉄烏丸線「北山駅」3番出口から徒歩すぐ（約1分）" },
  "響灘緑地（グリーンパーク）": { nearestStation: "二島駅", accessNote: "JR若松線 二島駅からタクシー約10分、またはバスで響灘緑地入口下車徒歩約15分（バス利用）" },
  "九州自然動物公園アフリカンサファリ": { nearestStation: "別府駅", accessNote: "JR別府駅から亀の井バス「アフリカンサファリ行き」で約50分。徒歩圏外。" },
  "九十九島水族館海きらら": { nearestStation: "佐世保駅", accessNote: "JR佐世保駅前からバス約25分「九十九島パールシーリゾート・九十九島水族館」下車" },
  "九十九島動植物園森きらら": { nearestStation: "佐世保駅", accessNote: "JR佐世保駅から市営バスで約30分、動植物園前下車。" },
  "串本海中公園": { nearestStation: "串本駅", accessNote: "JR串本駅から無料送迎シャトルバスまたは町営バスで約13分。" },
  "熊本市動植物園": { nearestStation: "動植物園入口駅", walkMinutes: 10, accessNote: "熊本市電健軍線「動植物園入口」電停から徒歩約10分。" },
  "群馬サファリパーク": { nearestStation: "上州富岡駅", accessNote: "上信電鉄上州富岡駅からタクシー約15分。最寄り駅からの路線バスはなく徒歩圏外" },
  "群馬県立 ぐんま昆虫の森": { nearestStation: "赤城駅", accessNote: "東武赤城駅・上毛電鉄新里駅から各3kmでタクシー約10分。徒歩圏外。" },
  "郡山市ふれあい科学館 スペースパーク": { nearestStation: "郡山駅", walkMinutes: 1, accessNote: "JR郡山駅西口直結のビッグアイ内（20〜24階）、徒歩約1分。" },
  "桂浜水族館": { nearestStation: "高知駅", accessNote: "JR高知駅等から桂浜行バス約30分、終点下車徒歩5分" },
  "軽井沢おもちゃ王国": { nearestStation: "軽井沢駅", accessNote: "軽井沢駅から路線バスで「プリンスランド」下車徒歩10分。徒歩圏外、バス利用" },
  "軽井沢絵本の森美術館（ムーゼの森）": { nearestStation: "中軽井沢駅", accessNote: "しなの鉄道中軽井沢駅から約2.4kmでバス・タクシー利用。徒歩は約29分で遠い" },
  "月見ヶ丘海浜公園": { nearestStation: "徳島駅", accessNote: "徳島駅から徳島バス（川内・松茂線）で「航空隊前」方面、徳島阿波おどり空港の南側" },
  "月見山こどもの森": { nearestStation: "香我美駅", walkMinutes: 20, accessNote: "土佐くろしお鉄道ごめん・なはり線香我美駅から徒歩約20分。loc「芸西村」は誤りで実際は香南市香我美町。" },
  "月山あさひサンチュアパーク": { nearestStation: "鶴岡駅", accessNote: "JR羽越本線 鶴岡駅から車約1時間（車利用、徒歩不可）" },
  "県民公園太閤山ランド": { nearestStation: "小杉駅", accessNote: "あいの風とやま鉄道小杉駅から車約10分、コミュニティバス利用、徒歩圏外" },
  "県立御所湖広域公園": { nearestStation: "雫石駅", accessNote: "JR田沢湖線 雫石駅から車約10分（車利用、徒歩不可）" },
  "県立四季の森公園 じゃぶじゃぶ池": { nearestStation: "中山駅", walkMinutes: 15, accessNote: "JR横浜線・市営地下鉄グリーンライン中山駅から公園北口まで徒歩約15分（約1.1km）" },
  "県立青葉の森公園 水の広場": { nearestStation: "千葉寺駅", walkMinutes: 10, accessNote: "京成千原線千葉寺駅から徒歩約10分（JR蘇我駅からも徒歩約10分）" },
  "戸山公園 箱根山地区 じゃぶじゃぶ池": { nearestStation: "早稲田駅", walkMinutes: 10, accessNote: "地下鉄東西線早稲田駅から徒歩10分。大江戸線若松河田駅からは徒歩15分" },
  "御殿場高原 時之栖 水中楽園AQUARIUM": { nearestStation: "岩波駅", accessNote: "御殿場線岩波駅からタクシー約5分、御殿場駅から無料シャトルバス約25分。徒歩圏外" },
  "広島市こども文化科学館": { nearestStation: "原爆ドーム前駅", walkMinutes: 5, accessNote: "広島電鉄(市内電車)原爆ドーム前電停から約300m、徒歩約5分。" },
  "広島市安佐動物公園": { nearestStation: "上安駅", accessNote: "アストラムライン 上安駅からバス約10分（駅から約2.5kmで徒歩圏外）。広島バスセンターから直通バス約50分" },
  "江ノ島水族館前ビーチ・片瀬東浜": { nearestStation: "片瀬江ノ島駅", walkMinutes: 2, accessNote: "小田急線片瀬江ノ島駅から徒歩約2分。江ノ電江ノ島駅からも徒歩約5分。" },
  "江戸川区自然動物園（行船公園）": { nearestStation: "西葛西駅", walkMinutes: 15, accessNote: "東京メトロ東西線 西葛西駅から徒歩約15分（行船公園内）" },
  "江戸東京たてもの園": { nearestStation: "武蔵小金井駅", accessNote: "JR武蔵小金井駅北口から西武バスで「小金井公園西口」下車徒歩5分" },
  "皇子原公園": { nearestStation: "高原駅", accessNote: "JR吉都線「高原駅」から車で約10分。徒歩は非現実的" },
  "航空科学博物館": { nearestStation: "空港第2ビル駅", accessNote: "空港第2ビル駅・成田駅から路線バスでバス停下車後徒歩。徒歩圏になく、バス利用。" },
  "香川県立ミュージアム": { nearestStation: "高松築港駅", walkMinutes: 4, accessNote: "ことでん高松築港駅から徒歩約4分" },
  "香美市立やなせたかし記念館 アンパンマンミュージアム": { nearestStation: "土佐山田駅", accessNote: "JR土讃線 土佐山田駅からJRバス約25分「美良布」下車徒歩約5分。徒歩圏外（バス利用）" },
  "高岡おとぎの森公園": { nearestStation: "新高岡駅", walkMinutes: 15, accessNote: "JR新高岡駅から約1.3km、徒歩約15分。" },
  "高崎山自然動物園": { nearestStation: "大分駅", accessNote: "JR大分駅から別府方面行きバスで約20分、高崎山自然動物園前下車。" },
  "高松市こども未来館": { nearestStation: "今橋駅", walkMinutes: 5, accessNote: "ことでん志度線今橋駅から徒歩約5分。" },
  "高知みらい科学館": { nearestStation: "大橋通駅", walkMinutes: 5, accessNote: "とさでん交通大橋通停留場から徒歩約5分（オーテピア5階）" },
  "高知県立牧野植物園": { nearestStation: "高知駅", accessNote: "五台山の山上に立地。JR高知駅から観光周遊バス「MY遊バス」で約30分「牧野植物園正門前」下車すぐ。徒歩圏外。" },
  "高尾山": { nearestStation: "高尾山口駅", walkMinutes: 5, accessNote: "京王線高尾山口駅から徒歩約5分でケーブルカー清滝駅・リフト山麓駅。" },
  "国営ひたち海浜公園": { nearestStation: "勝田駅", accessNote: "JR常磐線勝田駅から茨城交通バス約15分（海浜公園西口など）。鉄道駅から徒歩圏外。" },
  "国営ひたち海浜公園 大観覧車": { nearestStation: "勝田駅", accessNote: "JR常磐線勝田駅から茨城交通バスで約15分、海浜公園西口下車。徒歩圏外" },
  "国営みちのく杜の湖畔公園": { nearestStation: "仙台駅", accessNote: "仙台駅西口から秋保・仙台西部ライナーで約70分。徒歩圏の駅はなく、バスまたは車利用。" },
  "国営越後丘陵公園": { nearestStation: "長岡駅", accessNote: "長岡駅大手口から越後交通バスで約40分。徒歩圏の駅はなく、バスまたは車利用。" },
  "国営讃岐まんのう公園": { nearestStation: "琴平駅", accessNote: "JR・ことでん琴平駅から琴参バスで約15分「まんのう公園口」下車。徒歩圏外" },
  "国営昭和記念公園": { nearestStation: "西立川駅", walkMinutes: 2, accessNote: "JR青梅線西立川駅から西立川口まで徒歩約2分。立川駅からあけぼの口まで徒歩約10分。" },
  "国営滝野すずらん丘陵公園": { nearestStation: "真駒内駅", accessNote: "近くに鉄道駅なし。地下鉄南北線真駒内駅から中央バス滝野線で約35分「すずらん公園東口」下車徒歩5分。徒歩圏外。" },
  "佐賀県立宇宙科学館": { nearestStation: "武雄温泉駅", accessNote: "JR武雄温泉駅からタクシー約10分、または祐徳バス祐徳線「永島」下車徒歩15分（土日祝運行）。徒歩圏外でバス・タクシー利用が基本。" },
  "佐賀県立宇宙科学館「ゆめぎんが」": { nearestStation: "武雄温泉駅", accessNote: "JR武雄温泉駅からタクシー約10分、または祐徳バス利用" },
  "佐久平ハイウェイオアシス パラダ": { nearestStation: "佐久平駅", accessNote: "北陸新幹線佐久平駅から車・無料シャトルバスで約10分。徒歩圏外" },
  "佐川おもちゃ美術館": { nearestStation: "佐川駅", accessNote: "JR土讃線佐川駅から約2.6km、徒歩約33分。車利用が便利" },
  "沙弥島": { nearestStation: "坂出駅", accessNote: "JR坂出駅から坂出市営バス瀬居線で約15〜20分。徒歩圏外、バス利用" },
  "埼玉県こども動物自然公園": { nearestStation: "高坂駅", walkMinutes: 20, accessNote: "東武東上線高坂駅から徒歩20分。西口からバス約5分も利用可" },
  "札幌市円山動物園": { nearestStation: "円山公園駅", walkMinutes: 15, accessNote: "地下鉄東西線 円山公園駅から徒歩約15分、またはバス約5分「動物園前」下車すぐ" },
  "鯖江市西山動物園": { nearestStation: "西山公園駅", walkMinutes: 5, accessNote: "福井鉄道西山公園駅から徒歩約5分（西鯖江駅から徒歩約10分）" },
  "三重県総合博物館 MieMu": { nearestStation: "津駅", accessNote: "近鉄・JR・伊勢鉄道の津駅西口から三重交通バス89系統で約5分「総合文化センター前」下車すぐ。" },
  "三春の里 田園生活館": { nearestStation: "三春駅", accessNote: "磐越東線三春駅・舞木駅からタクシー、郡山駅から車で約20分。徒歩圏外" },
  "山口県立山口博物館": { nearestStation: "山口駅", walkMinutes: 20, accessNote: "JR山口駅から徒歩約20分（約1.5km）" },
  "山梨県笛吹川フルーツ公園": { nearestStation: "山梨市駅", accessNote: "JR中央本線 山梨市駅から車・市営バスで約7分（徒歩は約36分で徒歩圏外）" },
  "山梨県立リニア見学センター": { nearestStation: "大月駅", accessNote: "JR大月駅から富士急バス約15分、徒歩圏外" },
  "山梨県立科学館": { nearestStation: "甲府駅", accessNote: "JR甲府駅北口から上り坂徒歩約25〜30分。シャトルバス約20分が便利" },
  "山梨県立考古博物館": { nearestStation: "甲府駅", accessNote: "JR甲府駅から山梨交通バス豊富行で「県立考古博物館」下車。徒歩圏外でバス利用。" },
  "山梨県立富士湧水の里水族館": { nearestStation: "富士山駅", accessNote: "富士急行河口湖線富士山駅から富士急バス約20分、さかな公園下車すぐ。徒歩圏外" },
  "讃岐おもちゃ美術館": { nearestStation: "片原町駅", walkMinutes: 5, accessNote: "ことでん「片原町駅」から徒歩約5分（高松駅からは徒歩約10分）" },
  "四国水族館": { nearestStation: "宇多津駅", walkMinutes: 12, accessNote: "JR宇多津駅から徒歩約12分（うたづ臨海公園内）" },
  "志摩スペイン村": { nearestStation: "鵜方駅", accessNote: "近鉄・鵜方駅から直通バス約13分" },
  "滋賀県立びわ湖こどもの国": { nearestStation: "安曇川駅", accessNote: "JR湖西線安曇川駅から江若交通バスで「こどもの国前」下車徒歩約3分。徒歩圏外でバス利用が基本。" },
  "滋賀県立陶芸の森": { nearestStation: "信楽駅", walkMinutes: 20, accessNote: "信楽高原鐵道「信楽駅」から徒歩約20分" },
  "滋賀県立琵琶湖博物館": { nearestStation: "草津駅", accessNote: "JR草津駅西口から近江鉄道バス約25分「琵琶湖博物館」下車すぐ" },
  "滋賀農業公園ブルーメの丘": { nearestStation: "日野駅", accessNote: "近江鉄道・日野駅から近江バス約15分、「幅野町」下車徒歩10分" },
  "鹿児島ふれあいスポーツランド": { nearestStation: "谷山駅", accessNote: "JR谷山駅・市電谷山電停から約4.5kmで徒歩不可。天文館等から鹿児島交通バス8番系統「ふれあいスポーツランド」終点下車。" },
  "鹿児島市中央公園": { nearestStation: "天文館通駅", walkMinutes: 10, accessNote: "市電(鹿児島市電)「天文館通」電停から徒歩約10分" },
  "鹿児島市立科学館": { nearestStation: "鴨池駅", accessNote: "市電「鴨池電停」「郡元電停」から徒歩約10分。JR鴨池駅からは約6分との情報もあるが要確認のためバス/市電利用が無難" },
  "手取フィッシュランド": { nearestStation: "美川駅", accessNote: "JR美川駅から数km。JR金沢駅から北陸鉄道バスで約1時間「手取川橋」下車。徒歩圏外。" },
  "酒々井プレミアム・アウトレット": { nearestStation: "南酒々井駅", accessNote: "最寄りのJR南酒々井駅でも徒歩約41分と遠く、酒々井駅・京成酒々井駅からのバス利用が一般的。徒歩圏外。" },
  "秋吉台サファリランド": { nearestStation: "新山口駅", accessNote: "JR山陽本線・新山口駅からバス約60分、「サファリランド前」下車徒歩2分" },
  "秋吉台自然動物公園サファリランド": { nearestStation: "新山口駅", accessNote: "JR新山口駅から防長バスで秋芳洞乗換え約1時間、「サファリランド前」下車" },
  "秋田県児童会館 みらいあ": { nearestStation: "秋田駅", accessNote: "JR秋田駅からバス約15分「県立体育館前」下車徒歩約2分" },
  "秋田県立中央公園": { nearestStation: "和田駅", accessNote: "JR奥羽本線・和田駅から国際教養大学行きバス約15分、「国際教養大学前」下車" },
  "秋田県立博物館": { nearestStation: "追分駅", walkMinutes: 20, accessNote: "JR奥羽本線「追分駅」から徒歩約20分" },
  "秋田市大森山動物園": { nearestStation: "新屋駅", accessNote: "JR羽越線新屋駅から徒歩約30分（登り坂）。秋田駅西口や新屋駅からバス利用が基本" },
  "秋田市大森山動物園ミルヴェ": { nearestStation: "新屋駅", accessNote: "JR羽越本線新屋駅からバスで約8分（徒歩約30分・徒歩圏外）" },
  "渋川マリン水族館": { nearestStation: "宇野駅", accessNote: "JR宇野駅からバスで約15分、渋川一丁目下車徒歩約4分。" },
  "渋川動物公園": { nearestStation: "宇野駅", accessNote: "JR宇野駅または児島駅からタクシー約20分。徒歩圏外でバス・タクシー利用。" },
  "出雲科学館": { nearestStation: "出雲科学館パークタウン前駅", walkMinutes: 3, accessNote: "一畑電車出雲科学館パークタウン前駅から徒歩約3分" },
  "所沢航空記念公園 むさしの川": { nearestStation: "航空公園駅", walkMinutes: 5, accessNote: "西武新宿線航空公園駅に隣接、駅から徒歩すぐ" },
  "所沢航空発祥記念館": { nearestStation: "航空公園駅", walkMinutes: 8, accessNote: "西武新宿線航空公園駅東口から徒歩約8分（所沢航空記念公園内）。" },
  "小岩井農場": { nearestStation: "小岩井駅", accessNote: "盛岡駅前からまきば園行バス約35分。小岩井駅からもバス・徒歩で約10分" },
  "小金井公園": { nearestStation: "花小金井駅", walkMinutes: 18, accessNote: "西武新宿線花小金井駅から約1.4km、徒歩約18分。JR武蔵小金井駅等からバス利用も可" },
  "小田原こどもの森公園わんぱくらんど": { nearestStation: "小田原駅", accessNote: "JR小田原駅西口から箱根登山バス「いこいの森」行きで下車すぐ（徒歩圏外）" },
  "昭和記念公園 こどもの森レインボーハンモック": { nearestStation: "西立川駅", accessNote: "西立川駅から西立川口は徒歩2分だが、こどもの森は園内奥（砂川口ゲートから徒歩約25分）" },
  "松江フォーゲルパーク": { nearestStation: "松江フォーゲルパーク駅", walkMinutes: 2, accessNote: "一畑電車北松江線松江フォーゲルパーク駅下車すぐ、徒歩約2分" },
  "松山総合公園": { nearestStation: "衣山駅", walkMinutes: 15, accessNote: "伊予鉄高浜線衣山駅・西衣山駅から徒歩約15分（公園北入口）" },
  "沼津港深海水族館": { nearestStation: "沼津駅", accessNote: "JR沼津駅南口からバス約15分、沼津港下車すぐ" },
  "湘南台文化センターこども館": { nearestStation: "湘南台駅", walkMinutes: 5, accessNote: "小田急江ノ島線・相鉄いずみ野線・横浜市営地下鉄湘南台駅から徒歩約5分。" },
  "上越科学館": { nearestStation: "春日山駅", accessNote: "えちごトキめき鉄道春日山駅から徒歩約30分・タクシー10分。バスはリージョンプラザ下車すぐ。徒歩は非現実的。" },
  "上越市立水族博物館 うみがたり": { nearestStation: "直江津駅", walkMinutes: 15, accessNote: "JR・えちごトキめき鉄道直江津駅から徒歩約15分" },
  "上柚木公園 じゃぶじゃぶ池": { nearestStation: "南大沢駅", walkMinutes: 17, accessNote: "京王相模原線南大沢駅から徒歩約17分。京王バス「上柚木公園」下車も可。" },
  "城山動物園": { nearestStation: "善光寺下駅", walkMinutes: 20, accessNote: "長野電鉄善光寺下駅から徒歩約20分。長野駅からバス「動物園下」下車徒歩3分。" },
  "城島高原パーク": { nearestStation: "別府駅", accessNote: "JR別府駅西口から亀の井バス約35分、城島高原パーク前下車。徒歩圏外でバス利用。" },
  "城南島海浜公園": { nearestStation: "大森駅", accessNote: "JR大森駅から京急バス約30分（城南島四丁目下車）。鉄道駅から徒歩圏外。" },
  "新潟県立自然科学館": { nearestStation: "上所駅", accessNote: "上所駅から徒歩約26分。新潟駅南口からバス約20分が便利" },
  "新潟市水族館 マリンピア日本海": { nearestStation: "新潟駅", accessNote: "JR新潟駅からバス約20分「水族館前」下車すぐ、徒歩圏外" },
  "新江ノ島水族館": { nearestStation: "片瀬江ノ島駅", walkMinutes: 3, accessNote: "小田急江ノ島線片瀬江ノ島駅から徒歩約3分。江ノ電江ノ島駅からは徒歩約10分。" },
  "新青森県総合運動公園": { nearestStation: "野内駅", accessNote: "青い森鉄道野内駅から市民バス「滝沢」行きで約10分、新総合運動公園前下車すぐ。徒歩は約40分で非現実的。" },
  "森とリスの遊園地 メルヘン村": { nearestStation: "嬉野温泉駅", accessNote: "最寄りは西九州新幹線嬉野温泉駅だが徒歩圏外（車で約4～10分）" },
  "神戸アンパンマンこどもミュージアム&モール": { nearestStation: "神戸駅", walkMinutes: 8, accessNote: "JR神戸駅から徒歩約8分、市営地下鉄海岸線ハーバーランド駅から徒歩約8分" },
  "神戸どうぶつ王国": { nearestStation: "計算科学センター駅", walkMinutes: 1, accessNote: "ポートライナー計算科学センター（神戸どうぶつ王国・「富岳」前）駅から徒歩約1分。" },
  "神戸市立須磨離宮公園": { nearestStation: "須磨駅", accessNote: "JR須磨駅・山陽須磨駅からバス、離宮公園前下車徒歩約2分。地下鉄妙法寺駅からもバス。徒歩圏外。" },
  "神崎農村公園ヨーデルの森": { nearestStation: "生野駅", accessNote: "JR播但線生野駅から神姫グリーンバスで約8分「ヨーデルの森」下車。徒歩圏外。" },
  "神代植物公園": { nearestStation: "つつじヶ丘駅", accessNote: "京王線つつじヶ丘駅・調布駅などからバス約20分、神代植物公園前下車。鉄道駅から徒歩圏外でバス利用が基本。" },
  "神津牧場": { nearestStation: "下仁田駅", accessNote: "上信電鉄「下仁田駅」からバス約30分・市野萱下車後さらに徒歩。実質は車利用" },
  "神奈川県立 生命の星・地球博物館": { nearestStation: "入生田駅", walkMinutes: 3, accessNote: "箱根登山鉄道入生田駅から徒歩約3分。" },
  "神野公園こども遊園地": { nearestStation: "佐賀駅", accessNote: "JR佐賀駅から約2km。佐賀市営バス「神野公園・佐賀医大行」約8分下車すぐ" },
  "秦山公園": { nearestStation: "土佐山田駅", walkMinutes: 13, accessNote: "JR土讃線土佐山田駅から徒歩約10〜13分。所在地は実際には香美市土佐山田町" },
  "壬生町おもちゃ博物館": { nearestStation: "国谷駅", accessNote: "東武宇都宮線国谷駅から約1.7km（車約5分）、おもちゃのまち駅からコミュニティバス。徒歩は約35分で遠い" },
  "諏訪公園": { nearestStation: "大牟田駅", walkMinutes: 16, accessNote: "西鉄大牟田駅から徒歩約16分、JR大牟田駅から徒歩約17分" },
  "須坂市動物園": { nearestStation: "須坂駅", accessNote: "長野電鉄須坂駅から市営バス約7〜10分、臥竜公園入口下車徒歩約5分。徒歩圏外。" },
  "須磨シーワールド": { nearestStation: "須磨海浜公園駅", walkMinutes: 5, accessNote: "JR「須磨海浜公園」駅から徒歩約5分" },
  "水とやすらぎの広場（大宮配水場内）": { nearestStation: "北与野駅", walkMinutes: 19, accessNote: "JR北与野駅から徒歩約19分、大宮駅からも徒歩約20分" },
  "水のめぐみ館 アクア琵琶": { nearestStation: "石山駅", accessNote: "JR石山駅からバス約15分「南郷洗堰」下車徒歩5分、徒歩圏外" },
  "水元公園": { nearestStation: "金町駅", accessNote: "JR常磐線金町駅から京成バス「水元公園」下車徒歩7分。駅からの徒歩は遠くバス利用。" },
  "水元公園 水遊び場": { nearestStation: "金町駅", accessNote: "JR金町駅・京成金町駅から京成バスで水元公園下車徒歩7分。駅から園内まで徒歩圏外" },
  "杉並アニメーションミュージアム": { nearestStation: "荻窪駅", walkMinutes: 18, accessNote: "JR荻窪駅から徒歩約18分。北口より関東バス「荻窪警察署前」下車徒歩2分が便利。" },
  "世界淡水魚園水族館 アクア・トトぎふ": { nearestStation: "岐阜駅", accessNote: "JR岐阜駅から岐阜バス川島線でバス停下車後、徒歩圏外でバス利用。" },
  "清泉寮ジャージー牧場": { nearestStation: "清里駅", accessNote: "JR小海線清里駅から車で約3分。徒歩は距離があり非現実的。" },
  "生駒山上遊園地": { nearestStation: "生駒山上駅", accessNote: "生駒駅→鳥居前駅から生駒ケーブルで生駒山上駅下車すぐ（ケーブルカー利用）" },
  "生駒山麓公園 ふれあいセンター": { nearestStation: "生駒駅", accessNote: "近鉄生駒駅南口から送迎バス利用、徒歩圏外（ハイキングは約1時間）" },
  "盛岡市子ども科学館": { nearestStation: "盛岡駅", walkMinutes: 15, accessNote: "JR盛岡駅西口から徒歩約15分、またはバス利用。" },
  "盛岡市動物公園 ZOOMO": { nearestStation: "盛岡駅", accessNote: "JR盛岡駅東口からバス約40分、動物公園前下車。徒歩圏外でバス利用。" },
  "盛岡市動物公園ZOOMO": { nearestStation: "盛岡駅", accessNote: "JR盛岡駅東口から動物公園行きバス約40分、「動物公園前」下車" },
  "西山公園": { nearestStation: "西山公園駅", walkMinutes: 1, accessNote: "福井鉄道福武線西山公園駅から徒歩約1分" },
  "西蔵王公園": { nearestStation: "山形駅", accessNote: "JR山形駅からバス西蔵王（野草園）行終点下車後徒歩約30分。車利用が便利" },
  "西猪名公園": { nearestStation: "北伊丹駅", walkMinutes: 2, accessNote: "JR福知山線・北伊丹駅下車すぐ" },
  "青森県観光物産館アスパム": { nearestStation: "青森駅", walkMinutes: 8, accessNote: "JR青森駅東口から徒歩約8分。" },
  "青森県立三沢航空科学館": { nearestStation: "三沢駅", accessNote: "青い森鉄道・三沢駅から車約15分。コミュニティバス等を利用" },
  "静岡科学館る・く・る": { nearestStation: "静岡駅", walkMinutes: 1, accessNote: "JR静岡駅南口から徒歩約1分（エスパティオビル8〜10階）" },
  "静岡市立日本平動物園": { nearestStation: "東静岡駅", accessNote: "JR東静岡駅南口からバス約10分「動物園入口」下車徒歩約5分。徒歩は遠くバス利用。" },
  "石神井公園": { nearestStation: "石神井公園駅", walkMinutes: 7, accessNote: "西武池袋線石神井公園駅から徒歩約7分" },
  "石川県ふれあい昆虫館": { nearestStation: "鶴来駅", walkMinutes: 20, accessNote: "北陸鉄道石川線鶴来駅から徒歩約20分。市営バスめぐーる利用なら約5分＋徒歩2分。" },
  "石川県西田幾多郎記念哲学館": { nearestStation: "宇野気駅", walkMinutes: 20, accessNote: "JR七尾線 宇野気駅から徒歩約20分" },
  "石川県立航空プラザ": { nearestStation: "小松駅", accessNote: "JR小松駅から小松空港行きバス約12分、小松空港下車徒歩3分" },
  "仙台アンパンマンこどもミュージアム": { nearestStation: "宮城野通駅", walkMinutes: 7, accessNote: "地下鉄東西線宮城野通駅から徒歩7分、JR仙台駅東口から徒歩9分" },
  "仙台うみの杜水族館": { nearestStation: "中野栄駅", walkMinutes: 15, accessNote: "JR仙石線中野栄駅から徒歩約15分。無料シャトルバスも運行。" },
  "仙台市天文台": { nearestStation: "愛子駅", accessNote: "JR仙山線 愛子駅からバス約10分「錦ケ丘七丁目北・天文台入口」下車徒歩約5分" },
  "千葉市動物公園": { nearestStation: "動物公園駅", walkMinutes: 1, accessNote: "千葉都市モノレール 動物公園駅から徒歩約1分" },
  "川越まつり会館＆菓子屋横丁": { nearestStation: "本川越駅", walkMinutes: 14, accessNote: "西武新宿線本川越駅から徒歩約14分。バス「蔵の街」下車すぐ。" },
  "川越鉄道公園 西武園ゆうえんち": { nearestStation: "西武園ゆうえんち駅", walkMinutes: 7, accessNote: "西武山口線「西武園ゆうえんち駅」から徒歩約7分。西武園駅からは徒歩約9分" },
  "浅虫水族館": { nearestStation: "浅虫温泉駅", walkMinutes: 10, accessNote: "青い森鉄道浅虫温泉駅から徒歩約10分（約732m）。" },
  "前橋市中央児童遊園 るなぱあく": { nearestStation: "中央前橋駅", walkMinutes: 5, accessNote: "上毛電鉄中央前橋駅から徒歩約5分。" },
  "善福寺公園": { nearestStation: "西荻窪駅", accessNote: "JR西荻窪駅・荻窪駅からバス、「善福寺」下車徒歩5分。駅から徒歩は遠い" },
  "曽爾高原": { nearestStation: "名張駅", accessNote: "近鉄 名張駅西口から三重交通バスで約47分「曽爾高原」下車後徒歩約20分。徒歩圏外（季節運行バス）" },
  "創造広場アクトランド": { nearestStation: "のいち駅", walkMinutes: 10, accessNote: "土佐くろしお鉄道ごめん・なはり線のいち駅から徒歩約10分" },
  "倉吉パークスクエア": { nearestStation: "倉吉駅", accessNote: "JR倉吉駅から路線バスで約12分「倉吉パークスクエア」下車。徒歩圏外。" },
  "草津温泉 湯畑周辺": { nearestStation: "長野原草津口駅", accessNote: "JR長野原草津口駅からバス約25分で草津温泉バスターミナル、そこから湯畑まで徒歩約5分。鉄道駅から徒歩圏外。" },
  "草津市立水生植物公園みずの森": { nearestStation: "草津駅", accessNote: "JR草津駅西口から近江鉄道バス約25分、みずの森下車" },
  "蔵王ハートランド": { nearestStation: "白石蔵王駅", accessNote: "JR白石蔵王駅からバス約47分（遠刈田温泉下車）＋タクシー約5分。徒歩圏外。" },
  "蔵王温泉": { nearestStation: "山形駅", accessNote: "JR山形駅からバスで約40分、徒歩圏外" },
  "足羽山公園遊園地": { nearestStation: "福井駅", accessNote: "JR福井駅からバス「足羽山公園下」下車徒歩約10分、または駅から徒歩約25分。山上のため実質バス利用" },
  "足立区生物園": { nearestStation: "竹ノ塚駅", walkMinutes: 20, accessNote: "東武スカイツリーライン竹ノ塚駅東口から徒歩約20分、またはバス利用。" },
  "袖ケ浦公園 じゃぶじゃぶ池": { nearestStation: "袖ケ浦駅", accessNote: "JR袖ケ浦駅から日東交通ののぞみ野・平岡線のバスで約12分。徒歩圏外でバス利用が基本。" },
  "多摩動物公園": { nearestStation: "多摩動物公園駅", walkMinutes: 1, accessNote: "京王動物園線・多摩都市モノレール多摩動物公園駅から徒歩約1分（駅正面）" },
  "多摩六都科学館": { nearestStation: "花小金井駅", walkMinutes: 18, accessNote: "西武新宿線花小金井駅から徒歩約18〜20分。はなバス約6分も利用可" },
  "太地町立くじらの博物館": { nearestStation: "太地駅", accessNote: "JRきのくに線 太地駅から太地町営じゅんかんバス約5〜10分、くじら館前下車すぐ（バス利用）" },
  "台場海浜公園 ビーチ": { nearestStation: "お台場海浜公園駅", walkMinutes: 5, accessNote: "ゆりかもめ お台場海浜公園駅から徒歩約5分" },
  "大宮花の丘農林公苑 親水広場": { nearestStation: "上尾駅", accessNote: "JR上尾駅西口から上尾市内循環バス約25分「花の丘公苑」下車すぐ" },
  "大山まきばみるくの里": { nearestStation: "米子駅", accessNote: "JR米子駅からバス約50分「桝水」下車徒歩約10分、徒歩圏外（車推奨）" },
  "大洗わくわく科学館": { nearestStation: "大洗駅", walkMinutes: 20, accessNote: "鹿島臨海鉄道大洗鹿島線「大洗駅」から徒歩約20分" },
  "大谷焼 窯元 体験工房": { nearestStation: "阿波大谷駅", walkMinutes: 5, accessNote: "JR高徳線阿波大谷駅から徒歩約5分（大谷焼の里・森陶器など）。" },
  "大貞公園": { nearestStation: "東中津駅", accessNote: "最寄りの東中津駅でも約3.8km・徒歩約45分。JR中津駅から大交北部バス約20分（大貞公園下車徒歩5分）。徒歩圏外。" },
  "大分マリーンパレス水族館「うみたまご」": { nearestStation: "別府駅", accessNote: "別府駅前または大分駅からバス、「高崎山自然動物園前」下車徒歩約3〜5分" },
  "大牟田市動物園": { nearestStation: "大牟田駅", walkMinutes: 18, accessNote: "JR・西鉄 大牟田駅東口から徒歩約15〜20分、またはバス「延命公園・動物園前」下車徒歩約4分" },
  "滝沢牧場": { nearestStation: "野辺山駅", accessNote: "JR小海線野辺山駅からタクシー約5分。無料シャトルバスあり" },
  "谷山第二中央公園": { nearestStation: "慈眼寺駅", walkMinutes: 15, accessNote: "JR指宿枕崎線「慈眼寺駅」から徒歩約15分（noteの谷山駅近くより慈眼寺駅が至近）" },
  "男鹿水族館 GAO": { nearestStation: "男鹿駅", accessNote: "JR男鹿線男鹿駅から男鹿北線の路線バスで「男鹿水族館前」下車。徒歩圏外でバス・タクシー利用が基本。" },
  "男鹿水族館GAO": { nearestStation: "男鹿駅", accessNote: "JR男鹿駅から路線バス(男鹿北線)またはなまはげシャトルで約45分〜1時間。徒歩圏外、バス利用" },
  "知育玩具広場 そだて宇宿店": { nearestStation: "二軒茶屋駅", walkMinutes: 4, accessNote: "鹿児島市電二軒茶屋駅から徒歩約4分。JR南鹿児島駅からも徒歩約6分。" },
  "池袋防災館": { nearestStation: "池袋駅", walkMinutes: 5, accessNote: "JR・各線池袋駅から徒歩約5分。池袋消防署と同じ建物" },
  "池田動物園": { nearestStation: "岡山駅", accessNote: "JR岡山駅西口からバス、「京山入口」下車徒歩約12分" },
  "茶臼山動物園": { nearestStation: "篠ノ井駅", accessNote: "JR篠ノ井駅から約2.8km・徒歩約38分。同駅西口からシャトル/路線バスまたは車で約15分。徒歩圏外。" },
  "長岡市寺泊水族博物館": { nearestStation: "寺泊駅", accessNote: "JR越後線「寺泊駅」から越後交通バスで約10分、寺泊水族館前下車すぐ。徒歩は非現実的" },
  "長崎ペンギン水族館": { nearestStation: "長崎駅", accessNote: "JR長崎駅前から長崎県営バス約30分、「ペンギン水族館前」下車徒歩約4分" },
  "長崎県立総合運動公園": { nearestStation: "諫早駅", walkMinutes: 24, accessNote: "JR・島原鉄道諫早駅から約2.0km、徒歩約20〜25分" },
  "長崎市科学館": { nearestStation: "大橋駅", walkMinutes: 10, accessNote: "長崎電気軌道（路面電車）大橋電停から徒歩約10分。" },
  "長門おもちゃ美術館": { nearestStation: "仙崎駅", walkMinutes: 5, accessNote: "JR山陰本線仙崎駅から徒歩約5分（道の駅センザキッチン内）。" },
  "鳥羽水族館": { nearestStation: "鳥羽駅", walkMinutes: 10, accessNote: "JR・近鉄鳥羽駅から徒歩約10分。" },
  "鳥海山 木のおもちゃ館": { nearestStation: "鮎川駅", accessNote: "由利高原鉄道鳥海山ろく線鮎川駅からシャトルバス約5分。徒歩圏外。" },
  "鳥取県立 むきばんだ史跡公園": { nearestStation: "淀江駅", accessNote: "JR山陰本線淀江駅からタクシー約5分。丘陵地で徒歩圏外、車・タクシー利用。" },
  "鳥取砂丘": { nearestStation: "鳥取駅", accessNote: "JR鳥取駅から路線バスで約20分、鳥取砂丘下車" },
  "鳥取砂丘こどもの国": { nearestStation: "鳥取駅", accessNote: "JR鳥取駅から砂丘・岩井行バス約15分、こどもの国入口下車徒歩約10分。徒歩圏外" },
  "鳥取二十世紀梨記念館 なしっこ館": { nearestStation: "倉吉駅", accessNote: "JR倉吉駅からバス約12分、倉吉パークスクエア下車すぐ" },
  "辻堂海浜公園": { nearestStation: "辻堂駅", walkMinutes: 20, accessNote: "JR東海道本線辻堂駅南口から徒歩約20分。バス利用も可" },
  "辻堂海浜公園 ジャンボプール": { nearestStation: "辻堂駅", walkMinutes: 25, accessNote: "JR東海道線 辻堂駅から徒歩約25分、または辻堂駅南口からバス約10分「辻堂海浜公園前」下車" },
  "坪井川公園（ひごっこジャングル）": { nearestStation: "坪井川公園駅", walkMinutes: 5, accessNote: "熊本電鉄坪井川公園駅から徒歩約5分" },
  "鶴ヶ城（会津若松城）": { nearestStation: "会津若松駅", accessNote: "JR会津若松駅からまちなか周遊バスで鶴ヶ城入口下車徒歩5分（約20分）。徒歩だと30〜40分" },
  "鶴岡市立加茂水族館": { nearestStation: "鶴岡駅", accessNote: "JR鶴岡駅から庄内交通バス「湯野浜温泉行き」約40分「加茂水族館」下車すぐ。徒歩圏外。" },
  "鉄道博物館": { nearestStation: "鉄道博物館駅", walkMinutes: 1, accessNote: "ニューシャトル（埼玉新都市交通）鉄道博物館（大成）駅から徒歩約1分" },
  "鉄道歴史パーク in SAIJO": { nearestStation: "伊予西条駅", walkMinutes: 2, accessNote: "JR予讃線伊予西条駅東隣で徒歩約2分。" },
  "天王寺動物園": { nearestStation: "天王寺駅", walkMinutes: 10, accessNote: "JR・大阪メトロ天王寺駅から徒歩約5〜10分（てんしばゲート）" },
  "天童市子育て未来館 げんキッズ": { nearestStation: "天童南駅", walkMinutes: 15, accessNote: "JR奥羽本線天童南駅から徒歩約15分。" },
  "天保山大観覧車": { nearestStation: "大阪港駅", walkMinutes: 5, accessNote: "大阪メトロ中央線大阪港駅から徒歩約5分" },
  "島根県立しまね花の郷": { nearestStation: "西出雲駅", walkMinutes: 10, accessNote: "JR山陰本線西出雲駅から徒歩約10分。" },
  "島根県立しまね海洋館アクアス": { nearestStation: "波子駅", walkMinutes: 10, accessNote: "JR山陰本線 波子駅からアクアスロードを徒歩約10分" },
  "島根県立古代出雲歴史博物館": { nearestStation: "出雲大社前駅", walkMinutes: 10, accessNote: "一畑電車大社線出雲大社前駅から徒歩約10分。" },
  "島根県立三瓶自然館サヒメル": { nearestStation: "大田市駅", accessNote: "JR大田市駅から石見交通の路線バスで約60分「自然館前」。便数1日2～3便と少なく徒歩圏外。" },
  "島根県立宍道湖自然館 ゴビウス": { nearestStation: "湖遊館新駅駅", walkMinutes: 10, accessNote: "一畑電車北松江線湖遊館新駅から徒歩約10分" },
  "東海大学海洋科学博物館": { nearestStation: "清水駅", accessNote: "JR清水駅西口からバス（三保方面）約20分、バス停から徒歩約1分。徒歩は非現実的。※2024年10月末で本館の一般公開終了。" },
  "東京おもちゃ美術館": { nearestStation: "四谷三丁目駅", walkMinutes: 5, accessNote: "東京メトロ丸ノ内線四谷三丁目駅から徒歩約5分。曙橋駅からは徒歩約8分。" },
  "東京ドイツ村": { nearestStation: "袖ケ浦駅", accessNote: "鉄道駅から離れており車・バス利用が前提（袖ケ浦バスターミナル等から路線バス、本数僅少）。徒歩圏外" },
  "東京駅前 行幸通り・丸の内仲通り": { nearestStation: "東京駅", walkMinutes: 3, accessNote: "行幸通りは東京駅丸の内側に直結。丸の内仲通りも東京駅・二重橋前駅から徒歩圏" },
  "東京競馬場（パドックひろば）": { nearestStation: "府中競馬正門前駅", walkMinutes: 3, accessNote: "京王競馬場線府中競馬正門前駅から正門まで徒歩約3分。" },
  "東山動植物園": { nearestStation: "東山公園駅", walkMinutes: 3, accessNote: "名古屋市営地下鉄東山線東山公園駅3番出口から徒歩約3分。植物園側は星ヶ丘駅から徒歩約7分。" },
  "東条湖おもちゃ王国": { nearestStation: "新三田駅", accessNote: "JR福知山線新三田駅から無料送迎バス（要予約）で約30分。徒歩圏外。" },
  "東武動物公園": { nearestStation: "東武動物公園駅", walkMinutes: 10, accessNote: "東武スカイツリーライン 東武動物公園駅西口から徒歩約10分（約600m）" },
  "湯本豪一記念日本妖怪博物館 三次もののけミュージアム": { nearestStation: "三次駅", accessNote: "JR三次駅から約2.2km、徒歩約26〜30分。路線バス約10分・タクシー約5分が便利" },
  "到津の森公園": { nearestStation: "小倉駅", accessNote: "JR小倉駅から西鉄バス約20分、「到津の森公園前」下車すぐ" },
  "道の駅 四季の郷公園 FOOD HUNTER PARK": { nearestStation: "伊太祈曽駅", walkMinutes: 20, accessNote: "和歌山電鐵伊太祈曽駅から徒歩約20分。" },
  "道の駅 大栄 すいかの里": { nearestStation: "由良駅", walkMinutes: 19, accessNote: "JR由良駅（コナン駅）から徒歩約19分。" },
  "道の駅うれしの まるく": { nearestStation: "嬉野温泉駅", walkMinutes: 3, accessNote: "西九州新幹線 嬉野温泉駅に隣接、徒歩約3分" },
  "徳島県立あすたむらんど": { nearestStation: "板野駅", accessNote: "JR板野駅から車約6分。JR徳島駅から「あすたむらんど行き」バス約36分" },
  "奈良県営馬見丘陵公園": { nearestStation: "五位堂駅", accessNote: "近鉄五位堂駅から奈良交通バス「馬見丘陵公園」下車すぐ。池部駅からは約2.6kmで徒歩圏外。" },
  "奈良県立民俗博物館・大和民俗公園": { nearestStation: "郡山駅", accessNote: "近鉄橿原線郡山駅から奈良交通バスで矢田東山下車徒歩約7～10分（バス利用）" },
  "奈良公園": { nearestStation: "近鉄奈良駅", walkMinutes: 5, accessNote: "近鉄奈良駅から徒歩約5分" },
  "那須サファリパーク": { nearestStation: "那須塩原駅", accessNote: "JR那須塩原駅からバス、「那須サファリパーク入口」下車徒歩約5分" },
  "那須どうぶつ王国": { nearestStation: "那須塩原駅", accessNote: "JR那須塩原駅からシャトルバス（予約制）またはタクシー。那須ICから車約30分" },
  "那須ハイランドパーク": { nearestStation: "黒磯駅", accessNote: "JR黒磯駅から無料シャトルバスで約60分、那須塩原駅からバス約70分。徒歩圏外" },
  "那須高原りんどう湖ファミリー牧場": { nearestStation: "黒磯駅", accessNote: "JR黒磯駅から車で約20分、那須塩原駅から予約制シャトルバス等。徒歩圏外" },
  "南房総国民休暇村": { nearestStation: "館山駅", accessNote: "JR内房線 館山駅東口からJRバス約25分「休暇村館山前」下車（徒歩圏外）" },
  "日光東照宮・日光江戸村": { nearestStation: "東武日光駅", accessNote: "東武日光駅から東照宮まで世界遺産めぐりバス利用、徒歩なら約30分。江戸村はSL大樹で鬼怒川温泉方面" },
  "日南町オシドリ観察小屋": { nearestStation: "根雨駅", walkMinutes: 5, accessNote: "JR伯備線 根雨駅から徒歩約5分。なお当施設は鳥取県『日野町』根雨に所在しており、入力のloc『日南町』は誤りの可能性" },
  "日峯大神子広域公園こども広場": { nearestStation: "中田駅", accessNote: "JR牟岐線中田駅から約2.7km。JR徳島駅から市バス利用、徒歩圏外" },
  "日本民家園": { nearestStation: "向ヶ丘遊園駅", walkMinutes: 13, accessNote: "小田急線向ヶ丘遊園駅から徒歩約13分（生田緑地内）。" },
  "日立市かみね動物園": { nearestStation: "日立駅", accessNote: "JR常磐線日立駅からバス約10分、神峰公園口下車徒歩約3分。鉄道駅から徒歩圏外でバス利用。" },
  "日和佐うみがめ博物館カレッタ": { nearestStation: "日和佐駅", walkMinutes: 20, accessNote: "JR牟岐線日和佐駅から徒歩約15〜20分" },
  "能代エナジアムパーク": { nearestStation: "能代駅", accessNote: "JR能代駅から車・タクシーで約15分。徒歩は非現実的" },
  "梅小路公園": { nearestStation: "梅小路京都西駅", walkMinutes: 3, accessNote: "JR嵯峨野線梅小路京都西駅から徒歩約1〜3分。京都駅から徒歩約15分" },
  "柏の葉公園 噴水広場": { nearestStation: "柏の葉キャンパス駅", accessNote: "つくばエクスプレス柏の葉キャンパス駅から約1.7km（徒歩約21分）。通常は同駅からバスで「柏の葉公園中央」下車。" },
  "白崎海洋公園": { nearestStation: "紀伊由良駅", accessNote: "JRきのくに線「紀伊由良駅」からバス約30分・車で約15分。徒歩は非現実的" },
  "箱根彫刻の森美術館": { nearestStation: "彫刻の森駅", walkMinutes: 2, accessNote: "箱根登山鉄道「彫刻の森」駅から徒歩約2分" },
  "箱根湯本駅前 旧街道周辺": { nearestStation: "箱根湯本駅", walkMinutes: 3, accessNote: "箱根登山鉄道「箱根湯本駅」前の旧街道周辺エリア" },
  "八ヶ岳アルパカ牧場": { nearestStation: "富士見駅", accessNote: "JR中央線富士見駅からタクシー・車で約5分（路線バスなし）" },
  "八戸公園（こどもの国）": { nearestStation: "本八戸駅", accessNote: "JR八戸線「本八戸駅」から是川団地行きバスで約20分、こどもの国入口下車すぐ。徒歩圏外" },
  "八食センター": { nearestStation: "八戸駅", accessNote: "JR八戸駅東口から八食100円バスで約12分。" },
  "八木山ベニーランド": { nearestStation: "八木山動物公園駅", walkMinutes: 5, accessNote: "仙台市地下鉄東西線八木山動物公園駅東1出口から徒歩約5分。" },
  "八木山動物公園 フジサキの杜": { nearestStation: "八木山動物公園駅", walkMinutes: 2, accessNote: "仙台市地下鉄東西線八木山動物公園駅から徒歩約2分" },
  "八木山動物公園フジサキの杜": { nearestStation: "八木山動物公園駅", walkMinutes: 2, accessNote: "仙台市地下鉄東西線「八木山動物公園駅」から徒歩約2分" },
  "板橋区立こども動物園": { nearestStation: "板橋区役所前駅", walkMinutes: 8, accessNote: "都営三田線 板橋区役所前駅から徒歩約8分" },
  "板野町歴史文化公園": { nearestStation: "板野駅", walkMinutes: 22, accessNote: "JR高徳線板野駅から徒歩約22分（車約5分）" },
  "飯田市立動物園": { nearestStation: "飯田駅", walkMinutes: 9, accessNote: "JR飯田線「飯田駅」から徒歩約9分" },
  "比島交通公園": { nearestStation: "高知駅", walkMinutes: 13, accessNote: "JR高知駅北口から徒歩約13分" },
  "備北丘陵公園": { nearestStation: "七塚駅", walkMinutes: 20, accessNote: "JR芸備線七塚駅から徒歩約20分。" },
  "琵琶湖博物館": { nearestStation: "草津駅", accessNote: "JR琵琶湖線 草津駅西口から近江鉄道バス約25分、びわこ博物館下車（バス利用）" },
  "彦根城": { nearestStation: "彦根駅", walkMinutes: 15, accessNote: "JR彦根駅から徒歩約15分" },
  "姫路セントラルパーク": { nearestStation: "姫路駅", accessNote: "JR姫路駅北口から神姫バス74系統で約25分、徒歩圏外" },
  "氷見市海浜植物園": { nearestStation: "島尾駅", walkMinutes: 15, accessNote: "JR氷見線島尾駅から徒歩約15分。" },
  "浜山公園": { nearestStation: "浜山公園北口駅", walkMinutes: 10, accessNote: "一畑電車「浜山公園北口駅」から徒歩約10分" },
  "浜松市動物園": { nearestStation: "浜松駅", accessNote: "JR浜松駅から遠鉄バス舘山寺温泉行きで約40分、動物園下車徒歩2分" },
  "浜名湖体験学習施設ウォット": { nearestStation: "弁天島駅", walkMinutes: 13, accessNote: "JR東海道本線弁天島駅から徒歩約13分。" },
  "富岡製糸場": { nearestStation: "上州富岡駅", walkMinutes: 15, accessNote: "上信電鉄 上州富岡駅から徒歩約10〜15分" },
  "富山あそびマーレ": { nearestStation: "越中大門駅", walkMinutes: 16, accessNote: "あいの風とやま鉄道越中大門駅から徒歩約16分" },
  "富山県こどもみらい館": { nearestStation: "小杉駅", accessNote: "あいの風とやま鉄道小杉駅から約3.3km、コミュニティバスで太閤山ランド下車" },
  "富山県美術館 オノマトペの屋上": { nearestStation: "富山駅", walkMinutes: 15, accessNote: "あいの風とやま鉄道・北陸新幹線富山駅北口から徒歩約15分。" },
  "富山市ファミリーパーク": { nearestStation: "富山駅", accessNote: "富山駅から地鉄バス16系統で約25分「ファミリーパーク前」下車すぐ。徒歩圏外、バス利用" },
  "富山市科学博物館": { nearestStation: "西中野駅", walkMinutes: 7, accessNote: "富山地方鉄道市内電車西中野停留場から徒歩約7分。富山駅からバスも可。" },
  "富士サファリパーク": { nearestStation: "御殿場駅", accessNote: "JR御殿場線御殿場駅から路線バスで約35分。徒歩圏外、バス・車利用" },
  "富士すばるランド": { nearestStation: "河口湖駅", accessNote: "河口湖駅から無料シャトルバスで約15分。徒歩圏外、バス利用" },
  "富士急ハイランド": { nearestStation: "富士急ハイランド駅", walkMinutes: 1, accessNote: "富士急行線富士急ハイランド駅下車すぐ、目の前が入園口" },
  "府中の森公園": { nearestStation: "東府中駅", walkMinutes: 8, accessNote: "京王線東府中駅から徒歩約8分" },
  "府中市郷土の森博物館": { nearestStation: "分倍河原駅", walkMinutes: 20, accessNote: "京王線・南武線分倍河原駅から徒歩約20分（バス便あり）" },
  "浮間公園": { nearestStation: "浮間舟渡駅", walkMinutes: 1, accessNote: "JR埼京線・浮間舟渡駅から徒歩約1分" },
  "武生中央公園 だるまちゃん広場": { nearestStation: "武生駅", walkMinutes: 20, accessNote: "JR北陸本線（ハピラインふくい）「武生駅」から徒歩約20分（福鉄バス約10分）" },
  "武蔵丘陵森林公園": { nearestStation: "森林公園駅", accessNote: "東武東上線森林公園駅北口から立正大学行きバス約7分「滑川中学校」下車徒歩5分。徒歩だと南口まで約3km。" },
  "武蔵国分寺公園": { nearestStation: "西国分寺駅", walkMinutes: 7, accessNote: "JR中央線・武蔵野線「西国分寺駅」から徒歩7分（国分寺駅からは徒歩10分）" },
  "武蔵野公園": { nearestStation: "多磨駅", walkMinutes: 18, accessNote: "西武多摩川線「多磨駅」から約1.5km・徒歩約18分。新小金井駅からも徒歩約19分" },
  "武蔵野公園 じゃぶじゃぶ池": { nearestStation: "武蔵小金井駅", accessNote: "JR武蔵小金井駅南口から京王バス「武蔵野公園」下車すぐ。徒歩は遠くバス利用。" },
  "福井県児童科学館 エンゼルランドふくい": { nearestStation: "太郎丸エンゼルランド駅", walkMinutes: 15, accessNote: "えちぜん鉄道三国芦原線太郎丸エンゼルランド駅から徒歩約15分" },
  "福井県立こども歴史文化館": { nearestStation: "福井駅", walkMinutes: 15, accessNote: "JR福井駅東口から徒歩約15分。コミュニティバスも利用可。" },
  "福井県立一乗谷朝倉氏遺跡博物館": { nearestStation: "一乗谷駅", walkMinutes: 3, accessNote: "JR越美北線一乗谷駅から徒歩約3分" },
  "福井県立恐竜博物館": { nearestStation: "勝山駅", accessNote: "えちぜん鉄道勝山駅から直通バスまたはタクシー約10〜15分" },
  "福岡アンパンマンこどもミュージアムinモール": { nearestStation: "中洲川端駅", walkMinutes: 1, accessNote: "地下鉄空港線中洲川端駅直結（博多リバレインモール5・6F）。" },
  "福岡市動物園": { nearestStation: "薬院大通駅", walkMinutes: 15, accessNote: "地下鉄七隈線薬院大通駅2番出口から徒歩約15分。" },
  "福山市立動物園": { nearestStation: "福山駅", accessNote: "JR福山駅からバス乗継または車で約30分。徒歩圏外、バス・タクシー利用" },
  "平城宮跡歴史公園 朱雀門ひろば": { nearestStation: "大和西大寺駅", walkMinutes: 20, accessNote: "近鉄大和西大寺駅南口から徒歩約20分。同駅からバス「朱雀門ひろば前」下車約6分も利用可。" },
  "平川動物公園": { nearestStation: "五位野駅", walkMinutes: 20, accessNote: "JR指宿枕崎線五位野駅から徒歩約20分（路線バスもあり）" },
  "平和の森公園 じゃぶじゃぶ池": { nearestStation: "平和島駅", walkMinutes: 10, accessNote: "京急本線「平和島駅」から徒歩約10分" },
  "米子水鳥公園": { nearestStation: "米子駅", accessNote: "JR米子駅から境港行きバス約20分「乗越」下車徒歩約20分、または米子ICから車約15分。徒歩圏外" },
  "別府こどもあそびめぐり": { nearestStation: "別府駅", walkMinutes: 10, accessNote: "トキハ別府店4F。JR別府駅東口から徒歩約10分。" },
  "宝が池公園 子どもの楽園": { nearestStation: "宝ケ池駅", walkMinutes: 5, accessNote: "叡山電鉄宝ケ池駅から徒歩約5分" },
  "豊橋総合動植物公園 のんほいパーク": { nearestStation: "二川駅", walkMinutes: 6, accessNote: "JR東海道本線二川駅南口から徒歩約6分。" },
  "防府市青少年科学館ソラール": { nearestStation: "防府駅", walkMinutes: 15, accessNote: "JR防府駅から徒歩15分" },
  "北海道こどもの国": { nearestStation: "砂川駅", accessNote: "JR砂川駅から車で約15分。路線バス利用後も徒歩約1kmで、徒歩圏外。" },
  "北九州市立いのちのたび博物館": { nearestStation: "スペースワールド駅", walkMinutes: 5, accessNote: "JR鹿児島本線スペースワールド駅から徒歩約5分。" },
  "本所防災館（墨田区）": { nearestStation: "錦糸町駅", walkMinutes: 10, accessNote: "JR・東京メトロ錦糸町駅から徒歩約10分。押上駅からも徒歩約10分" },
  "万博記念公園": { nearestStation: "万博記念公園駅", walkMinutes: 1, accessNote: "大阪モノレール 万博記念公園駅から徒歩約1分" },
  "夢見が丘キッズパーク": { nearestStation: "西都城駅", accessNote: "JR日豊本線西都城駅から宮崎交通バス霧島神宮線で夢見ヶ丘下車徒歩約2分。宮崎道高原ICから車約30分。徒歩圏外" },
  "霧島市こども館 すかいぴあ": { nearestStation: "国分駅", accessNote: "JR国分駅から車約20分（上野原テクノパーク内）" },
  "名古屋アンパンマンこどもミュージアム＆パーク": { nearestStation: "桑名駅", accessNote: "JR・近鉄 桑名駅から三重交通バス約20分「長島温泉」下車すぐ（ナガシマリゾート内）" },
  "名古屋港水族館": { nearestStation: "名古屋港駅", walkMinutes: 5, accessNote: "名古屋市営地下鉄名港線名古屋港駅3番出口から徒歩約5分" },
  "名古屋市科学館": { nearestStation: "伏見駅", walkMinutes: 5, accessNote: "地下鉄東山線・鶴舞線伏見駅から徒歩約5分。" },
  "鳴門ウチノ海総合公園": { nearestStation: "鳴門駅", accessNote: "JR鳴門線鳴門駅からバスで約15分、高島バス停下車徒歩約3分。" },
  "鳴門市ドイツ館": { nearestStation: "板東駅", walkMinutes: 20, accessNote: "JR高徳線板東駅から徒歩約20分。" },
  "木曽三川公園センター": { nearestStation: "石津駅", accessNote: "養老鉄道石津駅から海津コミュニティバス「木曽三川公園」下車すぐ。徒歩は非現実的でバス利用。" },
  "野川公園": { nearestStation: "新小金井駅", walkMinutes: 15, accessNote: "西武多摩川線新小金井駅または多磨駅から徒歩約15分。調布駅からは京王バス「野川公園一之橋」下車。" },
  "友ヶ島": { nearestStation: "加太駅", accessNote: "南海加太線加太駅から加太港まで徒歩約20分、加太港から友ヶ島汽船で約20分（島へは渡船必須）。" },
  "悠久山公園": { nearestStation: "長岡駅", accessNote: "JR長岡駅から約4kmで徒歩圏外。越後交通バス悠久山行で終点下車徒歩5分。" },
  "竜北公園": { nearestStation: "小川駅", accessNote: "JR鹿児島本線小川駅からバス・車で約10分、徒歩圏外" },
  "龍泉洞": { nearestStation: "岩泉小本駅", accessNote: "三陸鉄道岩泉小本駅から岩泉町民バスで約26分（バス利用）" },
  "鈴鹿サーキット": { nearestStation: "白子駅", accessNote: "近鉄名古屋線白子駅からバスで約20分（またはタクシー約15分）。徒歩圏外。" },
  "歴史公園えさし藤原の郷": { nearestStation: "水沢江刺駅", accessNote: "JR東北新幹線 水沢江刺駅から車で約15分（鉄道駅からは徒歩圏外）" },
  "和歌山県立自然博物館": { nearestStation: "海南駅", accessNote: "JR海南駅から和歌山市方面行きバス約10分「琴の浦」下車すぐ。徒歩圏外。" },
  "和歌山市立こども科学館": { nearestStation: "和歌山市駅", walkMinutes: 5, accessNote: "南海和歌山市駅から南へ徒歩約5分" },
  "和歌山城": { nearestStation: "和歌山市駅", walkMinutes: 10, accessNote: "南海和歌山市駅から徒歩約10分。" },
  "和田堀公園 じゃぶじゃぶ池": { nearestStation: "西永福駅", walkMinutes: 15, accessNote: "京王井の頭線西永福駅から徒歩約15分。" },
  "諫早市こどもの城": { nearestStation: "諫早駅", accessNote: "JR・島鉄諫早駅から県営バス（国立諫早青少年自然の家行き）で白木峰高原下車徒歩約6分、所要約30分。徒歩圏外。" },
};
