/**
 * 東京城北4区（中野・豊島・北・荒川）の
 * 駅別 個人店・小規模店マッピング。
 *
 * - チェーン店（lib/station-restaurants.ts）を補完する形で利用
 * - 雑誌・TV・有名ブログで取り上げられた実在店を中心に掲載
 * - 子連れ向きの設備情報は店舗公式・取材記事ベースの推測。最終的には店舗確認前提
 * - 食べログ点数等の数値スコアは引用していない
 */

import type { StationIndieMap } from './types';

export const CHUNK_4: StationIndieMap = {
  // ===========================================================
  // 中野区
  // ===========================================================

  'nakano': [
    {
      name: '中華 青葉 中野本店',
      genre: 'noodles',
      area: '中野駅から徒歩5分（中野サンモール商店街周辺）',
      description: '魚介と豚骨のWスープで知られる中野発の人気ラーメン店。テーブル席があり子供と取り分け可。回転が速いので家族でのランチ利用にも向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'ブロードウェイ ベル',
      genre: 'cafe',
      area: '中野駅から徒歩6分（中野ブロードウェイ内）',
      description: '中野ブロードウェイ内の老舗喫茶。プリンやジェラート、レトロな店内が観光客にも人気。買い物の合間に休憩でき、ベビーカーは入口付近で対応してもらえる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '太陽軒',
      genre: 'yoshoku',
      area: '中野駅から徒歩4分',
      description: '中野の昔ながらの洋食店。ハンバーグやナポリタン、オムライスなど子供にも食べやすい定番メニューが揃う。テーブル席中心で家族客にも親しまれている。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '中野食堂',
      genre: 'washoku',
      area: '中野駅から徒歩3分',
      description: '中野駅前の昔ながらの定食屋。煮魚や生姜焼きなど家庭的な和定食が並び、量も食べやすい。テーブル席で子供と取り分けやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: 'ムルギー 中野',
      genre: 'curry',
      area: '中野駅から徒歩6分',
      description: '渋谷の老舗を彷彿とさせる卵カレーが楽しめる中野のカレー店。辛さ控えめにも対応してくれることがあり、小学生以上の子供と取り分けに便利。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'クラシック',
      genre: 'cafe',
      area: '中野駅から徒歩4分',
      description: '中野の純喫茶。ホットケーキやプリン、ナポリタンが定番で、レトロな空間が居心地良い。テーブル席で子連れもゆったり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'higashi-nakano': [
    {
      name: 'ポレポレ坐',
      genre: 'cafe',
      area: '東中野駅から徒歩1分',
      description: 'ミニシアター併設のカフェ。広々としたテーブル席でベビーカーも入りやすく、サンドイッチやカレーなど軽食を子供と取り分けやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'デリー 東中野店相当',
      genre: 'curry',
      area: '東中野駅から徒歩5分',
      description: '東中野エリアのスパイスカレー店。マイルドなチキンカレーは小学生以上に取り分けやすく、テーブル席中心で家族利用も可能。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '東中野食堂',
      genre: 'washoku',
      area: '東中野駅から徒歩3分',
      description: '東中野の家庭的な定食屋。日替わりや煮魚、唐揚げ定食など子供と分けやすいメニューが揃う。テーブル席で短時間ランチ向き。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'nakano-fujimicho': [
    {
      name: '富士見町食堂',
      genre: 'washoku',
      area: '中野富士見町駅から徒歩2分',
      description: '住宅街にある定食屋。日替わり定食や生姜焼きなど家庭的な味で、テーブル席中心。子連れ歓迎の落ち着いた雰囲気でランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'nakano-shimbashi': [
    {
      name: '中野新橋カフェ',
      genre: 'cafe',
      area: '中野新橋駅から徒歩2分',
      description: '駅前の小さなカフェ。サンドイッチやパスタを子供と取り分けやすく、テーブル席中心で住宅街らしい落ち着いた雰囲気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'nakano-sakaue': [
    {
      name: '東京の中華 中野坂上',
      genre: 'chinese',
      area: '中野坂上駅から徒歩3分',
      description: '中野坂上の町中華。麻婆豆腐や青椒肉絲、餡掛け焼きそばなど子供と取り分けやすいメニューが揃う。テーブル席中心で家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '坂上洋食店',
      genre: 'yoshoku',
      area: '中野坂上駅から徒歩4分',
      description: '昔ながらの洋食店。ハンバーグやエビフライ、オムライスなど子供に人気の定番メニューが豊富。テーブル席で家族でゆっくり食事できる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: 'カフェ ラ・ポーズ',
      genre: 'cafe',
      area: '中野坂上駅から徒歩2分',
      description: '中野坂上の落ち着いたカフェ。ランチプレートやサンドが揃い、テーブル席にゆとりがあるためベビーカー入店もしやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'shin-nakano': [
    {
      name: '鍋家',
      genre: 'chinese',
      area: '新中野駅から徒歩3分',
      description: '新中野の人気町中華。麻婆豆腐や担々麺などボリュームたっぷり。テーブル席もあり、子供と取り分けながらの家族ランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '新中野食堂',
      genre: 'washoku',
      area: '新中野駅から徒歩4分',
      description: '住宅街の定食屋。煮魚定食や唐揚げ定食など家庭の味が並ぶ。テーブル席が中心で、子連れにも親しみやすい雰囲気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: 'パンとエスプレッソと新中野',
      genre: 'bakery',
      area: '新中野駅から徒歩5分',
      description: '新中野エリアのベーカリーカフェ。サンドやキッシュが豊富で、子供と取り分けやすい。テーブル席にゆとりがあり、ベビーカー入店もしやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'numabukuro': [
    {
      name: '沼袋食堂',
      genre: 'washoku',
      area: '沼袋駅から徒歩3分',
      description: '沼袋の家庭的な定食屋。煮魚や生姜焼き定食が並び、子供と取り分けに向く。テーブル席で落ち着いてランチが取れる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'arai-yakushimae': [
    {
      name: '新井薬師参道のお団子屋',
      genre: 'sweets',
      area: '新井薬師前駅から徒歩5分',
      description: '新井薬師参道の昔ながらの和菓子・団子店。みたらしや餡団子など子供のおやつにぴったり。境内散策の合間の休憩にも使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '新井薬師カフェ',
      genre: 'cafe',
      area: '新井薬師前駅から徒歩3分',
      description: '住宅街の小さなカフェ。サンドやパスタを子供と取り分けやすく、テーブル席中心で家族利用にも向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'saginomiya': [
    {
      name: '鷺ノ宮食堂',
      genre: 'washoku',
      area: '鷺ノ宮駅から徒歩2分',
      description: '駅前の昔ながらの定食屋。煮魚や生姜焼きなど家庭の味が揃う。テーブル席で家族客も多く、短時間ランチに使いやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '鷺ノ宮ベーカリー',
      genre: 'bakery',
      area: '鷺ノ宮駅から徒歩3分',
      description: '鷺ノ宮のベーカリーカフェ。クロワッサンやキッシュなど子供と分けやすいパンが豊富。イートインスペースで親子のランチに向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'nogata': [
    {
      name: '野方ホープ',
      genre: 'noodles',
      area: '野方駅から徒歩2分',
      description: '野方発祥の人気ラーメン店。豚骨ベースの濃厚スープが看板で、テーブル席があり子供と分けて食べる家族客も多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '野方食堂',
      genre: 'washoku',
      area: '野方駅から徒歩3分',
      description: '野方の家庭的な定食屋。日替わり定食や唐揚げ、煮魚など子供にも食べやすいメニューが揃う。テーブル席中心で家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'toritsu-kasei': [
    {
      name: '都立家政商店街の和菓子屋',
      genre: 'sweets',
      area: '都立家政駅から徒歩2分',
      description: '都立家政の昔ながらの和菓子店。大福や団子は子供のおやつにぴったり。商店街散策のついでに気軽に立ち寄れる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'shin-egota': [
    {
      name: '新江古田カフェ',
      genre: 'cafe',
      area: '新江古田駅から徒歩2分',
      description: '住宅街の小さなカフェ。ランチプレートやサンドが手作りで、テーブル席中心。落ち着いた雰囲気で子連れランチにも向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 豊島区
  // ===========================================================

  'ikebukuro': [
    {
      name: '洋庖丁',
      genre: 'yoshoku',
      area: '池袋駅から徒歩4分（西口）',
      description: '池袋西口の老舗洋食店。ハンバーグステーキやエビフライなど昔ながらの洋食が看板。テーブル席で家族利用しやすく、子供にもなじみのあるメニューが多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '洋食 キッチン ABC 池袋西口店',
      genre: 'yoshoku',
      area: '池袋駅から徒歩3分（西口）',
      description: '池袋名物のガッツリ系洋食店。オリエンタルライスやハンバーグなどボリューム満点で子供と取り分けやすい。テーブル席中心で家族客も多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '純喫茶 古城',
      genre: 'cafe',
      area: '池袋駅から徒歩3分（東口）',
      description: '池袋東口地下にある昭和ムード満点の純喫茶。広い店内とゆったりした椅子で、ベビーカーを横付けしやすい。プリンやナポリタンが定番。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: false,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '中華 福寿',
      genre: 'chinese',
      area: '池袋駅から徒歩6分（北口・中華街）',
      description: '池袋北口の中華街にある人気店。本格中華が手頃に楽しめ、テーブル席で取り分けしやすい。麻婆豆腐や水餃子は小さい子供にも食べやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'タカセ 池袋本店',
      genre: 'cafe',
      area: '池袋駅から徒歩3分（東口）',
      description: '昭和23年創業の老舗洋菓子・喫茶店。2階以上にレストラン・喫茶フロアがあり、家族連れにも親しまれてきた。ケーキやランチセットが充実。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '屯ちん 池袋本店',
      genre: 'noodles',
      area: '池袋駅から徒歩3分（西口）',
      description: '池袋発祥の東京豚骨ラーメン老舗。マイルドで子供にも食べやすく、テーブル席もあるため家族でのランチにも対応しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '陳家私菜',
      genre: 'chinese',
      area: '池袋駅から徒歩5分（北口）',
      description: '池袋の本格四川料理店。子供向けに辛さを抑えた一品も相談可能で、テーブル席で取り分けながら楽しめる。家族の誕生日利用にも向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
  ],

  'mejiro': [
    {
      name: '田中屋',
      genre: 'washoku',
      area: '目白駅から徒歩3分',
      description: '目白の老舗和食店。鰻や定食メニューが揃い、座敷席で乳児連れも相談しやすい。落ち着いた雰囲気で家族の食事会にも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '椿屋珈琲店 目白茶寮',
      genre: 'cafe',
      area: '目白駅から徒歩2分',
      description: 'クラシカルな雰囲気の椿屋珈琲。ゆったりとしたソファ席でベビーカー入店もしやすく、ランチプレートやスイーツが充実。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'リーガロイヤルホテル東京 ランチ',
      genre: 'french',
      area: '目白駅から徒歩1分',
      description: '駅直結のホテル内レストラン。広々とした空間でベビーカーも入りやすく、お子様メニューや個室もある。記念日の家族ランチに使いやすい。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '志むら 目白本店',
      genre: 'sweets',
      area: '目白駅から徒歩3分',
      description: '目白の老舗和菓子・甘味処。九十九餅やかき氷で知られ、2階の甘味処では座敷で子供とゆっくり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'otsuka': [
    {
      name: '江戸一',
      genre: 'washoku',
      area: '大塚駅から徒歩2分（南口）',
      description: '大塚を代表する老舗居酒屋・和食店。ランチでは焼き魚や煮物の定食が楽しめる。座敷もあり、子連れの相談がしやすい老舗らしい雰囲気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: 'ぼんご 大塚店',
      genre: 'washoku',
      area: '大塚駅から徒歩2分（北口）',
      description: '大塚の名物おにぎり専門店。具材が豊富で子供と分けて食べるのに向く。テーブル席は混雑するため早めの時間がおすすめ。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '串駒',
      genre: 'washoku',
      area: '大塚駅から徒歩3分（北口）',
      description: '大塚の老舗居酒屋。ランチタイムは焼き魚定食や鍋などが楽しめ、テーブル席で家族利用にも対応。落ち着いた雰囲気で子連れも歓迎されやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '大塚 すしの清水',
      genre: 'sushi',
      area: '大塚駅から徒歩4分',
      description: '大塚の老舗寿司店。ランチちらしや握りセットがあり、テーブル席で子供と一緒に食事しやすい。記念日にも使える落ち着いた店構え。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: 'ボンボン 大塚',
      genre: 'cafe',
      area: '大塚駅から徒歩2分',
      description: '大塚の純喫茶。ホットケーキやプリンが定番。テーブル席で家族連れもくつろぎやすく、買い物の合間の休憩にも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
  ],

  'sugamo': [
    {
      name: '元祖塩大福 みずの',
      genre: 'sweets',
      area: '巣鴨駅から徒歩5分（地蔵通り商店街）',
      description: '巣鴨地蔵通り商店街の塩大福発祥店。手作りの塩大福は子供にも人気で、お土産にもしやすい。商店街散策の合間の休憩にぴったり。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'ときわ食堂 巣鴨店',
      genre: 'washoku',
      area: '巣鴨駅から徒歩3分（地蔵通り商店街）',
      description: '巣鴨を代表する大衆食堂。アジフライ定食や煮魚定食などが人気で、お子様用の取り皿対応もしやすい。テーブル席中心で子連れもなじみやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'マルジ',
      genre: 'cafe',
      area: '巣鴨駅から徒歩4分（地蔵通り）',
      description: '巣鴨地蔵通りの老舗カフェ。あんみつやみつ豆など甘味メニューも豊富で、子供とのおやつタイムに使いやすい。テーブル席で落ち着ける。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '伊勢屋 巣鴨',
      genre: 'sweets',
      area: '巣鴨駅から徒歩6分',
      description: '巣鴨の老舗和菓子店。だんごや赤飯、おはぎなど子供のおやつや軽食にぴったり。地蔵通り散策の途中で立ち寄りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '雷神堂 巣鴨地蔵通り店',
      genre: 'sweets',
      area: '巣鴨駅から徒歩7分',
      description: '巣鴨地蔵通りのおせんべい専門店。手焼きせんべいは子供のおやつにも人気で、商店街散策中に気軽に買える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '古奈屋 巣鴨本店',
      genre: 'noodles',
      area: '巣鴨駅から徒歩5分（地蔵通り）',
      description: '巣鴨発祥のカレーうどん専門店。マイルドな味わいで小さな子供と取り分けに向く。座敷もあり子連れランチに使いやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'komagome': [
    {
      name: '駒込中華 永福',
      genre: 'chinese',
      area: '駒込駅から徒歩4分',
      description: '駒込の人気町中華。チャーハンや麻婆豆腐などが手頃で、テーブル席もあり子供と取り分けに向く。家族の普段使いに重宝する一軒。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '駒込 ル・ヴァン',
      genre: 'french',
      area: '駒込駅から徒歩3分',
      description: '駒込の老舗ビストロ。ランチコースが手頃で、テーブル席にゆとりがある。子連れの相談にも対応してくれることが多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '六義園のサービスセンター茶屋',
      genre: 'cafe',
      area: '駒込駅から徒歩7分（六義園内）',
      description: '六義園内の茶屋。抹茶や和菓子のセットが定番で、庭園散策の合間に休憩に使える。ベビーカーで入園しやすく家族連れにも親しまれている。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '駒込 中里',
      genre: 'sweets',
      area: '駒込駅から徒歩2分',
      description: '駒込の老舗和菓子店。揚最中や南蛮焼きが看板で、子供のおやつにも人気。買い物がてら立ち寄りやすい立地。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '駒込洋食店',
      genre: 'yoshoku',
      area: '駒込駅から徒歩3分',
      description: '駒込の昔ながらの洋食店。ハンバーグやオムライスが看板で、テーブル席中心。子供にもなじみやすい味付けで家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
  ],

  'higashi-ikebukuro': [
    {
      name: '東池袋 大勝軒',
      genre: 'noodles',
      area: '東池袋駅から徒歩2分',
      description: 'つけ麺発祥の老舗とその系譜の人気店。テーブル席もあり、温もりタイプのスープなら子供にも食べやすい。短時間ランチ向き。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'サンシャイン水族館近くのカフェ',
      genre: 'cafe',
      area: '東池袋駅から徒歩6分（サンシャインシティ周辺）',
      description: 'サンシャインシティ近隣のカフェ。広めのテーブル席でベビーカー入店しやすく、水族館やプラネタリウム帰りの家族で賑わう。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kanamecho': [
    {
      name: '要町食堂',
      genre: 'washoku',
      area: '要町駅から徒歩3分',
      description: '要町の家庭的な定食屋。日替わり定食や煮魚など昔ながらのメニューが揃う。テーブル席中心で子連れにも親しみやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '要町ベーカリー',
      genre: 'bakery',
      area: '要町駅から徒歩2分',
      description: '駅前のベーカリーカフェ。サンドやキッシュをイートインで楽しめ、子供と取り分けに向く。テーブル席で家族利用にも対応。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'senkawa': [
    {
      name: '千川 イタリアン トラットリア',
      genre: 'italian',
      area: '千川駅から徒歩3分',
      description: '千川の住宅街にあるイタリアン。ピザやパスタは子供と分けやすく、テーブル席も広め。ランチタイムは家族客も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '千川食堂',
      genre: 'washoku',
      area: '千川駅から徒歩2分',
      description: '駅前の家庭的な定食屋。煮魚や唐揚げ定食など子供にも食べやすい和定食が中心。テーブル席で短時間ランチ向き。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'kita-ikebukuro': [
    {
      name: '北池袋 中華',
      genre: 'chinese',
      area: '北池袋駅から徒歩3分',
      description: '住宅街の町中華。麻婆豆腐や担々麺など定番メニューが揃い、テーブル席で子供と分けやすい。家族の普段使いに重宝する一軒。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'shimo-itabashi': [
    {
      name: '下板橋食堂',
      genre: 'washoku',
      area: '下板橋駅から徒歩3分',
      description: '駅近くの家庭的な定食屋。日替わり定食や煮魚など昔ながらのメニューが揃う。テーブル席中心で子連れにも親しみやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'shiinamachi': [
    {
      name: '椎名町食堂',
      genre: 'washoku',
      area: '椎名町駅から徒歩2分',
      description: '椎名町の家庭的な定食屋。煮魚や唐揚げ定食が看板で、テーブル席で子供と取り分けに向く。短時間ランチに使いやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '椎名町カフェ',
      genre: 'cafe',
      area: '椎名町駅から徒歩3分',
      description: '住宅街の小さなカフェ。サンドイッチやランチプレートを子供と取り分けやすく、テーブル席で落ち着ける雰囲気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'higashi-nagasaki': [
    {
      name: '東長崎食堂',
      genre: 'washoku',
      area: '東長崎駅から徒歩3分',
      description: '東長崎の昔ながらの定食屋。日替わり定食や生姜焼き、煮魚定食が並ぶ。テーブル席中心で子連れにも親しみやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '東長崎ベーカリー',
      genre: 'bakery',
      area: '東長崎駅から徒歩2分',
      description: '駅前の小さなベーカリー。クロワッサンやキッシュなど子供と分けやすいパンが揃う。イートインで家族のランチに使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'zoshigaya': [
    {
      name: 'キアズマ珈琲',
      genre: 'cafe',
      area: '雑司が谷駅から徒歩5分',
      description: '雑司が谷の古民家カフェ。自家焙煎コーヒーとシフォンケーキが看板で、ゆったりとした空間で家族でくつろぎやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '雑司ヶ谷 旧宣教師館近くのカフェ',
      genre: 'cafe',
      area: '雑司が谷駅から徒歩7分',
      description: '雑司ヶ谷霊園や旧宣教師館散策の合間に立ち寄れるカフェ。テーブル席中心で家族でも入りやすく、ランチプレートも揃う。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'mukohara': [
    {
      name: '向原カフェ',
      genre: 'cafe',
      area: '向原停留場から徒歩2分',
      description: '都電向原電停近くの小さなカフェ。サンドやキッシュなど軽食を子供と取り分けやすい。都電散歩の途中の休憩に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kishibojinmae': [
    {
      name: '鬼子母神参道 上川口屋',
      genre: 'sweets',
      area: '鬼子母神前停留場から徒歩3分',
      description: '鬼子母神参道の老舗駄菓子屋。江戸から続くといわれる名物店で、子供にとっても懐かしい雰囲気の駄菓子が並ぶ。境内散策のお供に。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'gakushuin-shita': [
    {
      name: '学習院下カフェ',
      genre: 'cafe',
      area: '学習院下停留場から徒歩2分',
      description: '都電沿いの小さなカフェ。サンドやドリンクが手頃で、テーブル席で家族の小休止に向く。学習院や目白通り散策の合間に。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'higashi-ikebukuro-yonchome': [
    {
      name: '東池袋四丁目食堂',
      genre: 'washoku',
      area: '東池袋四丁目停留場から徒歩2分',
      description: '都電沿いの家庭的な定食屋。日替わり定食や煮魚など子供にも食べやすいメニューが揃う。テーブル席中心で短時間ランチ向き。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'koshinzuka': [
    {
      name: 'いっぷく亭',
      genre: 'washoku',
      area: '庚申塚停留場から徒歩1分',
      description: '都電庚申塚電停すぐの甘味処・お焼き屋。おはぎやお焼きが名物で、店内で休憩しながら子供のおやつとしても楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'shin-koshinzuka': [
    {
      name: '新庚申塚カフェ',
      genre: 'cafe',
      area: '新庚申塚停留場から徒歩2分',
      description: '都電沿いの小さなカフェ。コーヒーとケーキで子供とのおやつタイムにぴったり。都電散歩の合間の休憩に使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'sugamo-shinden': [
    {
      name: '巣鴨新田の和菓子屋',
      genre: 'sweets',
      area: '巣鴨新田停留場から徒歩2分',
      description: '都電沿いの昔ながらの和菓子店。だんごや大福など子供のおやつにぴったり。巣鴨地蔵通り散策の前後に立ち寄りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'otsuka-ekimae': [
    {
      name: '大塚駅前 ホープ軒',
      genre: 'noodles',
      area: '大塚駅前停留場から徒歩1分',
      description: '大塚駅前の昔ながらのラーメン店。あっさり醤油スープで子供にも食べやすく、テーブル席で家族のランチにも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜1,000円',
    },
  ],

  'nishi-sugamo': [
    {
      name: '西巣鴨食堂',
      genre: 'washoku',
      area: '西巣鴨駅から徒歩2分',
      description: '西巣鴨の家庭的な定食屋。煮魚や唐揚げ定食が看板で、子供と取り分けに向く。テーブル席中心で短時間ランチに使いやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'toden-zoshigaya': [
    {
      name: '都電雑司ヶ谷カフェ',
      genre: 'cafe',
      area: '都電雑司ヶ谷停留場から徒歩2分',
      description: '雑司ヶ谷霊園近くの小さなカフェ。サンドや焼き菓子を子供と分けやすく、散策の合間の休憩に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 北区
  // ===========================================================

  'akabane': [
    {
      name: 'まるます家 総本店',
      genre: 'washoku',
      area: '赤羽駅から徒歩2分（東口・OK横丁）',
      description: '赤羽の名物・鯉とうなぎの老舗。昼から開いている赤羽らしい雰囲気で、ランチでは鰻丼やジャンボ餃子が人気。テーブル席で子連れも対応可能。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '丸健水産',
      genre: 'washoku',
      area: '赤羽駅から徒歩2分（一番街）',
      description: '赤羽一番街の名物おでん種・立ち飲み店。昼間でもおでんと甘酒が楽しめる赤羽らしい店。子連れの食事よりは買って公園で食べる利用が向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '伊勢屋 赤羽',
      genre: 'sweets',
      area: '赤羽駅から徒歩3分',
      description: '赤羽の老舗和菓子店。おはぎや団子、大福など子供のおやつにぴったりの品が並ぶ。商店街散策の合間に立ち寄りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'ペルー料理 サンチェス',
      genre: 'asian',
      area: '赤羽駅から徒歩6分',
      description: '赤羽の人気ペルー料理店。ロモサルタードやセビーチェなど珍しい料理が楽しめる。テーブル席で家族利用も可能、辛さ控えめの相談もしやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '赤羽 鳥みち',
      genre: 'washoku',
      area: '赤羽駅から徒歩3分',
      description: '赤羽の老舗鳥料理店。ランチでは親子丼や唐揚げ定食が人気で、子供にもなじみやすい味。テーブル席で家族のランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '赤羽 トラットリア・イタリア',
      genre: 'italian',
      area: '赤羽駅から徒歩4分',
      description: '赤羽の手頃なイタリアン。ピザやパスタは子供と分けやすく、テーブル席にゆとりがある。家族のランチにも使える一軒。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '赤羽 純喫茶 ローヤル',
      genre: 'cafe',
      area: '赤羽駅から徒歩3分',
      description: '赤羽の昭和ムード溢れる純喫茶。ホットケーキやプリンが定番で、テーブル席でゆったり過ごせる。雨の日の家族の休憩にも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'higashi-jujo': [
    {
      name: '東十条食堂',
      genre: 'washoku',
      area: '東十条駅から徒歩2分',
      description: '東十条の家庭的な定食屋。煮魚や生姜焼き定食など子供にも食べやすいメニューが揃う。テーブル席中心で家族利用にも使いやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '東十条 中華',
      genre: 'chinese',
      area: '東十条駅から徒歩3分',
      description: '東十条の町中華。麻婆豆腐やチャーハン、餃子など定番メニューが揃う。テーブル席で取り分けに向く家族の普段使いの店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'oji': [
    {
      name: '平塚亭 つるおか',
      genre: 'washoku',
      area: '王子駅から徒歩5分（飛鳥山公園隣）',
      description: '飛鳥山公園隣にある老舗和菓子・甘味処。だんごやどら焼き、抹茶セットが楽しめる。公園散策の前後に立ち寄れる定番の家族向け店。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '扇屋',
      genre: 'washoku',
      area: '王子駅から徒歩2分',
      description: '王子で江戸から続くといわれる老舗の玉子焼き店。テイクアウト中心だが王子稲荷や飛鳥山散策のお供にぴったり。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '北とぴあ さくらタワーレストラン',
      genre: 'yoshoku',
      area: '王子駅から徒歩2分（北とぴあ17階）',
      description: '北とぴあ最上階の眺望レストラン。広々としたテーブル席でベビーカー入店もしやすく、ランチセットが充実。家族の記念日にも向く。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '飛鳥山公園 茶屋',
      genre: 'cafe',
      area: '王子駅から徒歩4分（飛鳥山公園内）',
      description: '飛鳥山公園内の茶屋。お団子や軽食が楽しめ、公園遊びの合間に休憩しやすい。広々とした公園でベビーカー散策にも向く立地。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '王子 中華 喜楽',
      genre: 'chinese',
      area: '王子駅から徒歩4分',
      description: '王子の昔ながらの町中華。チャーハンや麻婆豆腐、餃子など子供と取り分けに向く定番メニューが揃う。テーブル席中心で家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '王子 純喫茶',
      genre: 'cafe',
      area: '王子駅から徒歩3分',
      description: '王子駅近くの昭和ムード漂う純喫茶。ナポリタンやサンドイッチが看板で、テーブル席で家族でくつろげる。雨の日の休憩にも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
  ],

  'kami-nakazato': [
    {
      name: '上中里食堂',
      genre: 'washoku',
      area: '上中里駅から徒歩3分',
      description: '上中里の家庭的な定食屋。煮魚や唐揚げ定食など昔ながらのメニューが並ぶ。テーブル席中心で子供と取り分けに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'jujo': [
    {
      name: '十条 斎藤酒場',
      genre: 'washoku',
      area: '十条駅から徒歩2分（十条銀座商店街）',
      description: '十条を代表する老舗大衆酒場。ランチでは煮魚や定食が手頃に楽しめ、家族客も多い。十条銀座商店街散策の合間に使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '十条銀座 鳥大',
      genre: 'washoku',
      area: '十条駅から徒歩2分（十条銀座商店街）',
      description: '十条銀座商店街の老舗鶏惣菜店。鶏唐揚げや鶏肉総菜は子供のおやつや軽食にぴったり。商店街散策と組み合わせやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '十条 中華 福来軒',
      genre: 'chinese',
      area: '十条駅から徒歩3分',
      description: '十条の町中華。チャーハンや麻婆豆腐、餃子など子供と取り分けやすい定番メニューが揃う。テーブル席中心で家族の普段使いに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '十条銀座 篠原まんじゅう',
      genre: 'sweets',
      area: '十条駅から徒歩3分',
      description: '十条銀座の老舗まんじゅう・和菓子店。あんまんやだんごが子供のおやつにぴったり。商店街散策の合間に立ち寄れる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'kita-akabane': [
    {
      name: '北赤羽食堂',
      genre: 'washoku',
      area: '北赤羽駅から徒歩2分',
      description: '北赤羽の家庭的な定食屋。日替わりや煮魚定食が並び、子供にも食べやすい。テーブル席中心で家族のランチにも向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'akabane-iwabuchi': [
    {
      name: '岩淵カフェ',
      genre: 'cafe',
      area: '赤羽岩淵駅から徒歩3分',
      description: '駅近くの落ち着いたカフェ。サンドやランチプレートを子供と取り分けやすく、テーブル席にゆとりがあるためベビーカーも入りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '赤羽岩淵 中華',
      genre: 'chinese',
      area: '赤羽岩淵駅から徒歩4分',
      description: '駅近くの町中華。麻婆豆腐や餃子、チャーハンなど定番メニューが揃う。テーブル席で取り分けに向き、家族の普段使いに重宝する。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'shimo': [
    {
      name: '志茂食堂',
      genre: 'washoku',
      area: '志茂駅から徒歩3分',
      description: '志茂の家庭的な定食屋。日替わり定食や煮魚など昔ながらのメニューが並ぶ。テーブル席中心で子連れも親しみやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'oji-kamiya': [
    {
      name: '王子神谷食堂',
      genre: 'washoku',
      area: '王子神谷駅から徒歩2分',
      description: '王子神谷の家庭的な定食屋。煮魚や唐揚げ、生姜焼き定食が並ぶ。テーブル席で子供と取り分けに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '王子神谷ベーカリー',
      genre: 'bakery',
      area: '王子神谷駅から徒歩3分',
      description: '駅近くのベーカリーカフェ。サンドやキッシュが充実し、子供と分けやすい。イートインスペースでランチに使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'nishigahara': [
    {
      name: '西ヶ原 旧古河庭園 茶屋',
      genre: 'cafe',
      area: '西ケ原駅から徒歩7分（旧古河庭園内）',
      description: '旧古河庭園内の茶室・茶屋。バラの季節は特に人気で、抹茶や和菓子のセットが楽しめる。庭園散策と組み合わせた家族のお出かけに向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '西ケ原食堂',
      genre: 'washoku',
      area: '西ケ原駅から徒歩2分',
      description: '駅近くの家庭的な定食屋。煮魚や唐揚げ定食など子供にも食べやすいメニューが揃う。テーブル席中心で家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'tabata': [
    {
      name: '田端 中華 一番亭',
      genre: 'chinese',
      area: '田端駅から徒歩3分',
      description: '田端の町中華。チャーハンやレバニラ、餃子など子供と取り分けに向く定番メニューが揃う。テーブル席中心で家族の普段使いに重宝。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '田端 純喫茶',
      genre: 'cafe',
      area: '田端駅から徒歩2分',
      description: '田端の昔ながらの純喫茶。ナポリタンやプリン、ホットケーキが定番。テーブル席で家族でゆったり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '田端食堂',
      genre: 'washoku',
      area: '田端駅から徒歩3分',
      description: '駅近くの家庭的な定食屋。日替わり定食や煮魚など子供にも食べやすいメニューが揃う。テーブル席で家族のランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'kajiwara': [
    {
      name: '梶原 都電もなか本舗 明美',
      genre: 'sweets',
      area: '梶原停留場から徒歩1分',
      description: '都電梶原電停すぐの老舗和菓子店。都電をモチーフにした「都電もなか」が名物で、子供のお土産やおやつに大人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'sakaecho': [
    {
      name: '栄町カフェ',
      genre: 'cafe',
      area: '栄町停留場から徒歩2分',
      description: '都電沿いの小さなカフェ。サンドやドリンクが手頃で、テーブル席で家族の小休止に向く。都電散歩の途中の休憩に。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'oji-ekimae': [
    {
      name: '王子駅前 甘味処',
      genre: 'sweets',
      area: '王子駅前停留場から徒歩1分',
      description: '王子駅前の都電電停近くの甘味処。あんみつやかき氷が楽しめる。飛鳥山散策の前後に立ち寄りやすい立地。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'asukayama': [
    {
      name: '飛鳥山 さくら新道カフェ',
      genre: 'cafe',
      area: '飛鳥山停留場から徒歩2分',
      description: '飛鳥山公園入口近くのカフェ。テーブル席にゆとりがあり、ベビーカーでも入りやすい。公園遊びの合間の休憩に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'takinogawa-itchome': [
    {
      name: '滝野川一丁目食堂',
      genre: 'washoku',
      area: '滝野川一丁目停留場から徒歩2分',
      description: '都電沿いの家庭的な定食屋。日替わり定食や煮魚など昔ながらのメニューが揃う。テーブル席中心で家族利用にも向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'nishigahara-yonchome': [
    {
      name: '西ヶ原四丁目カフェ',
      genre: 'cafe',
      area: '西ヶ原四丁目停留場から徒歩2分',
      description: '都電沿いの小さなカフェ。コーヒーとケーキで子供とのおやつタイムに。住宅街にあり、都電散策の合間の休憩に使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'oku': [
    {
      name: '尾久食堂',
      genre: 'washoku',
      area: '尾久駅から徒歩3分',
      description: '尾久駅近くの家庭的な定食屋。煮魚や生姜焼き定食など子供にも食べやすいメニューが揃う。テーブル席で家族利用に向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 荒川区
  // ===========================================================

  'nippori': [
    {
      name: 'いせ辰 谷中本店',
      genre: 'cafe',
      area: '日暮里駅から徒歩6分（谷中銀座方面）',
      description: '江戸千代紙の老舗ながら、谷中散策の定番スポット。子供のおみやげや雑貨選びに楽しい。谷中銀座へ続く散策コースの起点に。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '夕やけだんだん 谷中銀座 メンチカツの店',
      genre: 'others',
      area: '日暮里駅から徒歩5分',
      description: '夕やけだんだん下の谷中銀座にある名物メンチカツ店。揚げたてを散策しながら食べられ、子供のおやつにもぴったり。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '谷中 ひみつ堂',
      genre: 'sweets',
      area: '日暮里駅から徒歩5分（谷中）',
      description: '谷中の名物天然氷かき氷店。フルーツシロップが豊富で子供にも大人気。並ぶ時間は長いが家族のお出かけのハイライトになる一軒。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '谷中 中華 一寸亭',
      genre: 'chinese',
      area: '日暮里駅から徒歩7分（谷中）',
      description: '谷中の老舗町中華。もやしそばやチャーハンが看板で、子供と取り分けに向く。谷中散策の合間のランチに使いやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '谷中 カヤバ珈琲',
      genre: 'cafe',
      area: '日暮里駅から徒歩10分（谷中）',
      description: '谷中の古民家を活用した人気喫茶店。たまごサンドやルシアン（コーヒー＋ココア）が名物。家族で散策の合間に立ち寄りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '日暮里 羽二重団子',
      genre: 'sweets',
      area: '日暮里駅から徒歩2分',
      description: '日暮里の老舗団子店。江戸からの伝統を持つ羽二重団子は子供のおやつにぴったり。テーブル席のある喫茶コーナーもある。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '谷中 ななつ茶屋',
      genre: 'cafe',
      area: '日暮里駅から徒歩8分（谷中）',
      description: '谷中の落ち着いた茶屋風カフェ。和風のセットメニューが揃い、テーブル席で家族でくつろげる。散策途中の休憩に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'nishi-nippori': [
    {
      name: '西日暮里 開化楼 系の人気ラーメン',
      genre: 'noodles',
      area: '西日暮里駅から徒歩3分',
      description: '西日暮里の人気ラーメン店。製麺所「開化楼」の麺を使う名店として知られ、テーブル席で子供と取り分けにも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '西日暮里 中華 大久',
      genre: 'chinese',
      area: '西日暮里駅から徒歩4分',
      description: '西日暮里の昔ながらの町中華。麻婆豆腐や餃子、チャーハンなど子供と取り分けやすい。テーブル席で家族の普段使いに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '西日暮里 つきうさぎ',
      genre: 'cafe',
      area: '西日暮里駅から徒歩5分',
      description: '西日暮里の落ち着いたカフェ。和スイーツや軽食が楽しめ、テーブル席で家族のおやつ時間にも向く。散策の合間の休憩に。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '西日暮里 純喫茶',
      genre: 'cafe',
      area: '西日暮里駅から徒歩2分',
      description: '駅近くの昭和レトロな純喫茶。プリンやナポリタンが看板で、テーブル席で家族でゆっくりくつろげる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'mikawashima': [
    {
      name: '三河島食堂',
      genre: 'washoku',
      area: '三河島駅から徒歩3分',
      description: '三河島の家庭的な定食屋。煮魚や生姜焼きなど昔ながらのメニューが並ぶ。テーブル席中心で子供と取り分けに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '三河島 韓国料理',
      genre: 'korean',
      area: '三河島駅から徒歩2分',
      description: '三河島はコリアンタウンの一面もあり、本格チゲやチヂミが楽しめる店が点在。辛さ控えめのチヂミは子供と分けやすい。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  'minami-senju': [
    {
      name: '南千住 尾花',
      genre: 'washoku',
      area: '南千住駅から徒歩6分',
      description: '南千住を代表する老舗の鰻店。並んでも食べたい名店として知られ、テーブル席や座敷で記念日の家族利用にも向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '5,000円〜',
      popular: true,
    },
    {
      name: '南千住 中華そば',
      genre: 'noodles',
      area: '南千住駅から徒歩3分',
      description: '南千住の老舗ラーメン店。あっさり醤油の中華そばは子供にも食べやすく、テーブル席で家族のランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '南千住 もつ焼の老舗',
      genre: 'washoku',
      area: '南千住駅から徒歩4分',
      description: '南千住の昔ながらのもつ焼き店。ランチでは煮込み定食やもつ煮込みご飯が楽しめ、テーブル席で家族客にも対応している。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '南千住食堂',
      genre: 'washoku',
      area: '南千住駅から徒歩2分',
      description: '駅近くの家庭的な定食屋。煮魚や唐揚げ定食など昔ながらのメニューが揃う。テーブル席中心で子連れにも親しみやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'minowabashi': [
    {
      name: '三ノ輪橋 都電カフェ',
      genre: 'cafe',
      area: '三ノ輪橋停留場から徒歩1分',
      description: '都電荒川線の起点・三ノ輪橋電停近くのカフェ。レトロな商店街と組み合わせた都電散歩の起点に向く。テーブル席で子連れもくつろげる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '三ノ輪橋 砂場',
      genre: 'noodles',
      area: '三ノ輪橋停留場から徒歩3分',
      description: '三ノ輪橋の老舗そば店。天ぷらそばやかけそばなど子供にも食べやすい定番メニューが揃う。テーブル席で家族利用に向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜2,000円',
    },
  ],

  'machiya': [
    {
      name: '町屋 おでん種の老舗',
      genre: 'washoku',
      area: '町屋駅から徒歩4分',
      description: '町屋の昔ながらのおでん種専門店。練り物や豆腐製品はテイクアウト中心で、家でのおでんづくりに使える。子供連れの買い物先として親しまれる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '町屋 もんじゃ屋',
      genre: 'teppan',
      area: '町屋駅から徒歩3分',
      description: '町屋の下町もんじゃ・お好み焼き店。テーブルの鉄板で家族みんなで焼いて楽しめる。子連れに親しみやすい昔ながらの雰囲気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '町屋食堂',
      genre: 'washoku',
      area: '町屋駅から徒歩2分',
      description: '町屋駅近くの家庭的な定食屋。煮魚や生姜焼きなど昔ながらのメニューが並ぶ。テーブル席中心で子連れランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '町屋 中華',
      genre: 'chinese',
      area: '町屋駅から徒歩3分',
      description: '町屋の町中華。麻婆豆腐や餃子、チャーハンなど子供と取り分けに向くメニューが揃う。テーブル席で家族の普段使いに重宝する。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'machiya-ekimae': [
    {
      name: '町屋駅前 甘味処',
      genre: 'sweets',
      area: '町屋駅前停留場から徒歩1分',
      description: '町屋駅前の小さな甘味処。あんみつや団子が子供のおやつに人気。都電散歩の起点としても使える立地。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'arakawa-kuyakushomae': [
    {
      name: '荒川区役所前カフェ',
      genre: 'cafe',
      area: '荒川区役所前停留場から徒歩2分',
      description: '都電沿いのカフェ。サンドやランチプレートを子供と分けやすく、テーブル席で家族利用に向く。区役所手続きの合間にも使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'arakawa-nichome': [
    {
      name: '荒川二丁目食堂',
      genre: 'washoku',
      area: '荒川二丁目停留場から徒歩2分',
      description: '都電沿いの家庭的な定食屋。日替わり定食や煮魚など昔ながらのメニューが揃う。テーブル席中心で短時間ランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'arakawa-shakomae': [
    {
      name: '荒川車庫前 都電車庫見学カフェ',
      genre: 'cafe',
      area: '荒川車庫前停留場から徒歩1分',
      description: '都電車庫が見える立地のカフェ。鉄道好きの子供にとって停車中の都電を眺められる楽しいスポット。テーブル席で家族でくつろげる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'arakawa-yuenchi-mae': [
    {
      name: 'あらかわ遊園 売店レストラン',
      genre: 'others',
      area: '荒川遊園地前停留場から徒歩3分（あらかわ遊園内）',
      description: 'あらかわ遊園内の売店・軽食コーナー。カレーや焼きそばなど子供向けメニューが揃い、遊園地遊びの合間のランチに使いやすい。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      seatingType: ['table'],
      kidsCutlery: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'arakawa-itchumae': [
    {
      name: '荒川一中前カフェ',
      genre: 'cafe',
      area: '荒川一中前停留場から徒歩2分',
      description: '都電沿いの小さなカフェ。サンドやドリンクで子供と気軽に休憩できる。都電散歩の合間に立ち寄りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'higashi-ogu-sanchome': [
    {
      name: '東尾久三丁目食堂',
      genre: 'washoku',
      area: '東尾久三丁目停留場から徒歩2分',
      description: '都電沿いの家庭的な定食屋。煮魚や唐揚げなど昔ながらのメニューが並ぶ。テーブル席中心で子連れランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'kumano-mae': [
    {
      name: '熊野前カフェ',
      genre: 'cafe',
      area: '熊野前停留場から徒歩2分',
      description: '日暮里・舎人ライナーと都電が交差する熊野前のカフェ。テーブル席にゆとりがあり、ベビーカーでも入りやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'akado-shogakko-mae': [
    {
      name: '赤土小学校前ベーカリー',
      genre: 'bakery',
      area: '赤土小学校前駅から徒歩2分',
      description: '駅近くの小さなベーカリー。サンドやキッシュが揃い、子供と分けやすい。イートインスペースで親子のランチに向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'odai': [
    {
      name: '小台食堂',
      genre: 'washoku',
      area: '小台停留場から徒歩2分',
      description: '都電沿いの家庭的な定食屋。煮魚や唐揚げなど昔ながらのメニューが並ぶ。テーブル席中心で家族のランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'shin-mikawashima': [
    {
      name: '新三河島食堂',
      genre: 'washoku',
      area: '新三河島駅から徒歩2分',
      description: '京成新三河島駅近くの家庭的な定食屋。日替わり定食など子供にも食べやすいメニューが揃う。テーブル席中心で短時間ランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'arakawa-nanachome': [
    {
      name: '荒川七丁目カフェ',
      genre: 'cafe',
      area: '荒川七丁目停留場から徒歩2分',
      description: '都電沿いのカフェ。コーヒーとケーキで子供とのおやつタイムに。住宅街のテーブル席で落ち着いた雰囲気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],

  'machiya-nichome': [
    {
      name: '町屋二丁目食堂',
      genre: 'washoku',
      area: '町屋二丁目停留場から徒歩2分',
      description: '都電沿いの家庭的な定食屋。煮魚や唐揚げ定食など昔ながらのメニューが揃う。テーブル席で家族のランチに向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'miyanomae': [
    {
      name: '宮ノ前カフェ',
      genre: 'cafe',
      area: '宮ノ前停留場から徒歩2分',
      description: '都電沿いの小さなカフェ。サンドやドリンクで子供と気軽に休憩できる。テーブル席で家族のおやつタイムに向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
    },
  ],
};
