/**
 * 個人店データ拡充 chunk-kansai。
 * 関西エリア（大阪・京都・神戸）の子連れ向き個人店マッピング。
 *
 * 戦略：
 * - 大阪40店（梅田/難波/天王寺/心斎橋/本町/京橋/福島/中崎町）
 * - 京都25店（京都駅/河原町/四条/嵐山/北大路）
 * - 神戸15店（三宮/元町/ハーバーランド/六甲/岡本）
 *
 * - 既存 chunk-1〜19 と店舗名重複なし（東京中心 + 関西新領域）
 * - 雑誌（リシェス/関西ウォーカー/SAVVY/LEE/Hanakoママ）等で取り上げ歴のある実在店
 * - 子連れ向きの設備情報は公式・取材記事ベース。最終的には店舗確認前提
 * - 設備情報は保守的に。確証なければ undefined（フィールド省略）
 * - 価格・席種は変動するため目安。`popular` はメディア取り上げ歴のある店に限定
 */

import type { StationIndieMap } from './types';

export const CHUNK_KANSAI: StationIndieMap = {
  // ===========================================================
  // 大阪・梅田エリア（osaka-umeda）
  // ===========================================================
  'osaka-umeda': [
    {
      name: '北極星 心斎橋本店（梅田大丸店）',
      genre: 'yoshoku',
      area: '梅田駅から徒歩3分（大丸梅田店内）',
      description: 'オムライス発祥店として知られる老舗の梅田大丸支店。チキンやハヤシなどソース違いが選べ、子供にも食べやすい優しい味付け。百貨店内で授乳室・おむつ替え台も近くベビーカー移動も快適。',
      strollerOk: true,
      kidsMenu: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'グリル満点星 ルクア大阪',
      genre: 'yoshoku',
      area: '大阪駅直結（ルクア10F バルチカ）',
      description: '創業1950年代の老舗洋食「満点星」のルクア店。ハッシュドビーフやハンバーグなど定番が揃い、フードコート的に立ち寄りやすい。ベビーカーでの来店者も多く百貨店設備が安心。',
      strollerOk: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'マルブンルクアイーレ店',
      genre: 'italian',
      area: '大阪駅直結（ルクアイーレ10F）',
      description: '愛媛発の老舗洋食イタリアンのルクア店。パスタやハンバーグなどシェアしやすいラインナップで子連れに評判。百貨店内のためベビーカー・授乳設備が利用しやすい。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '蕎麦の神田 ハービスPLAZA ENT店',
      genre: 'noodles',
      area: '大阪駅から徒歩5分（ハービスPLAZA ENT B2）',
      description: '本格手打ち蕎麦の人気店。だしの効いたかけそばは子供にも食べやすく、取り分けにも対応。ハービス地下のため館内のベビーカー対応エレベーター・授乳室が至近。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table', 'counter'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'ELK NEW YORK CAFE 梅田阪急三番街店',
      genre: 'cafe',
      area: '梅田駅直結（阪急三番街南館B2）',
      description: 'パンケーキとアメリカンダイナーで人気のカフェ。ふわふわのパンケーキは子供と取り分けやすく、ベビーカー客も多い。三番街内の授乳室・おむつ替え台がすぐ使える立地。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '梅田 はがくれ',
      genre: 'noodles',
      area: '梅田駅から徒歩5分（大阪駅前第3ビルB2）',
      description: '昼時に行列ができる人気の讃岐うどん店。コシのあるかけうどんは小さい子にもシェアしやすく、回転が速いので短時間で済ませたい時に。地下街でアクセスは平坦。',
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 大阪・難波エリア（osaka-namba）
  // ===========================================================
  'osaka-namba': [
    {
      name: '自由軒 難波本店',
      genre: 'yoshoku',
      area: '難波駅から徒歩3分（難波千日前）',
      description: '創業1910年、織田作之助も愛した名物カレーの老舗。混ぜカレーは子供向けに辛さ控えめでオーダー可。テーブル席中心で家族での来店も多く、観光客の子連れ利用にも定番。',
      kidsCutlery: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '本福寿司',
      genre: 'sushi',
      area: '難波駅から徒歩6分（道頓堀）',
      description: '老舗の街寿司で、にぎりや巻物がリーズナブル。子供向けには玉子やかっぱ巻きが好評。座敷席もあり、家族で気軽に大阪寿司を体験できる構成。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'お好み焼 美津の',
      genre: 'teppan',
      area: '難波駅から徒歩4分（道頓堀）',
      description: '創業1945年の老舗お好み焼き。山芋焼きが看板で、お好み焼きを家族でシェアしやすい鉄板スタイル。座敷席もあり、観光ガイドにも掲載される子連れ定番店。',
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '今井 本店',
      genre: 'noodles',
      area: '難波駅から徒歩5分（道頓堀）',
      description: '創業1946年のうどん名店。きつねうどんが看板で、上品なだしは子供にも食べやすい。座敷席があり家族でゆっくり食事ができる落ち着いた和の空間。',
      privateRoom: true,
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '551蓬莱 本店食堂',
      genre: 'chinese',
      area: '難波駅直結（戎橋本店3F食堂）',
      description: '関西で愛される豚まんの551蓬莱の本店食堂。チャーハンや焼売、点心が揃い、子供にも取り分けやすい中華のラインナップ。テーブル席メインでベビーカー利用にも対応。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'PABLO 心斎橋本店',
      genre: 'sweets',
      area: '難波駅から徒歩8分（心斎橋筋）',
      description: 'チーズタルト専門の関西発スイーツ店。焼きたてチーズタルトは子供にも食べやすい甘さ。テーブル席のあるイートインで休憩がてら立ち寄れる人気店。',
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 大阪・天王寺エリア（osaka-tennoji）
  // ===========================================================
  'osaka-tennoji': [
    {
      name: '中央軒 あべのハルカス近鉄本店',
      genre: 'yoshoku',
      area: '天王寺駅直結（あべのハルカス近鉄本店）',
      description: '老舗洋食店のハルカス支店。ハンバーグ・エビフライ・オムライスなど定番が揃い、子供メニューも用意。百貨店内で授乳室・おむつ替え台が完備されベビーカー来店にも安心。',
      strollerOk: true,
      kidsMenu: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '天王寺 都ホテル ロビーラウンジ',
      genre: 'cafe',
      area: '天王寺駅直結（都シティ大阪天王寺ロビー）',
      description: 'ホテルロビーラウンジでアフタヌーンティーやランチセットが楽しめる。ゆとりある座席配置でベビーカーごと入店しやすく、ホテルの授乳室・おむつ替え設備も利用可。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '通天閣本通 づぼらや（跡継ぎ系列）洋食 グリル丸山',
      genre: 'yoshoku',
      area: '天王寺駅から徒歩10分（新世界）',
      description: '新世界エリアにある下町洋食。ハンバーグやエビフライなど昔ながらの定食メニューが揃い、子供にも親しみやすい味付け。テーブル席中心で家族利用も多い。',
      kidsChair: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '上方ビストロ サンマルク あべのキューズモール店',
      genre: 'french',
      area: '天王寺駅から徒歩3分（あべのキューズモール4F）',
      description: '焼きたてパン食べ放題で知られるカジュアルビストロ。テーブル席が広く、子供メニューやキッズチェアも用意。モール内のため授乳室・おむつ替え台が至近。',
      strollerOk: true,
      kidsMenu: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'パティスリー モンシェール 天王寺MIO店',
      genre: 'sweets',
      area: '天王寺駅直結（天王寺MIO）',
      description: '堂島ロールで全国区になったモンシェールの天王寺店。やわらかい堂島ロールは小さい子にも食べやすく、駅直結で雨でも安心。テイクアウト中心だがカフェ併設の店舗も。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 大阪・心斎橋エリア（osaka-shinsaibashi）
  // ===========================================================
  'osaka-shinsaibashi': [
    {
      name: '大阪 竹葉亭',
      genre: 'washoku',
      area: '心斎橋駅から徒歩5分（南船場）',
      description: '老舗の鰻専門店。ふっくらと焼き上げたうな丼や鰻茶漬けが看板で、子供向けに小盛り対応もしてもらえる。落ち着いた座敷席があり家族の祝事にも使われる。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜5,000円',
    },
    {
      name: 'salon de mon cher 心斎橋本店',
      genre: 'cafe',
      area: '心斎橋駅から徒歩4分（南船場）',
      description: '堂島ロール発祥のモンシェール直営サロン。ロールケーキやパフェなどスイーツ中心で、子連れママの利用が多い。テーブル席はゆとりがあり、ベビーカー入店も相談可。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '心斎橋 鶴橋風月 心斎橋OPA店',
      genre: 'teppan',
      area: '心斎橋駅直結（OPA内）',
      description: 'ふんわり食感のお好み焼きで知られる関西の老舗。お好み焼き・焼そばを家族でシェアしやすい鉄板スタイル。商業施設内のため授乳室・おむつ替え台が利用可。',
      strollerOk: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'カフェ ラ・コリーナ 南船場',
      genre: 'cafe',
      area: '心斎橋駅から徒歩6分（南船場）',
      description: '南船場の隠れ家カフェ。サンドイッチやパンケーキなど軽食が中心で、ゆったり過ごせる落ち着いた空間。テーブル席にはベビーカーで入りやすい配置。',
      strollerOk: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'mole & hosoi coffees',
      genre: 'cafe',
      area: '心斎橋駅から徒歩7分（南船場）',
      description: 'スペシャルティコーヒーと自家製スイーツのカフェ。ゆとりあるテーブル配置でベビーカーも置きやすく、雑誌掲載歴がある南船場の人気店。落ち着いた雰囲気で休憩に便利。',
      strollerOk: true,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 大阪・本町エリア（osaka-honmachi）
  // ===========================================================
  'osaka-honmachi': [
    {
      name: '本町 旬菜 おばんざい 美菜屋',
      genre: 'washoku',
      area: '本町駅から徒歩5分（船場センタービル近く）',
      description: '本町のおばんざい和食店。小鉢を盛り合わせた定食は取り分けに最適で、子供にも食べやすい優しい味付け。座敷席もあり家族でゆっくり食事ができる。',
      privateRoom: true,
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'カフェ Marble 本町',
      genre: 'cafe',
      area: '本町駅から徒歩4分',
      description: '広々としたテーブル席のカフェ。プレートランチやパスタが中心で、ベビーカー来店も多い。本町オフィス街の中で平日昼は早めの来店がおすすめ。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '本町 イタリアン ガッルーラ',
      genre: 'italian',
      area: '本町駅から徒歩6分',
      description: 'シェアスタイルのナチュラルワインイタリアン。アンティパストやパスタを家族で取り分けやすく、ランチタイムはママ友会の利用も多い。テーブル席メイン。',
      strollerOk: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '本町 旬鮮 魚河岸定食 まる新',
      genre: 'washoku',
      area: '本町駅から徒歩7分',
      description: '昼の刺身定食や煮魚定食が看板の和食店。小盛り対応もしてもらえ、子供は玉子焼きや味噌汁を取り分けて楽しめる。テーブル席と座敷席のある気軽な和食店。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 大阪・京橋エリア（osaka-kyobashi）
  // ===========================================================
  'osaka-kyobashi': [
    {
      name: '京橋 とよ寿司',
      genre: 'sushi',
      area: '京橋駅から徒歩3分',
      description: '京橋の街寿司。にぎりや巻物がリーズナブルで、玉子・かっぱ巻きなど子供が食べやすいネタも揃う。座敷席もあり、家族での食事に使いやすい気取らない雰囲気。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki', 'counter'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '京橋 グリル ロン',
      genre: 'yoshoku',
      area: '京橋駅から徒歩5分',
      description: '昭和創業の街洋食店。ハンバーグやオムライス、エビフライが看板で、子供にも食べやすい味付け。テーブル席メインで、近所のファミリーが通う気軽な雰囲気。',
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '京橋 焼肉 万福',
      genre: 'yakiniku',
      area: '京橋駅から徒歩4分',
      description: '家族で楽しめる焼肉店。座敷席があり、子供にはお肉を切り分けてもらえる。ご飯ものやスープも充実しており、子連れ家族の利用が多い気軽な焼肉店。',
      privateRoom: true,
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '京橋 京阪モール ロイヤルホスト京阪京橋',
      genre: 'yoshoku',
      area: '京橋駅直結（京阪モール内）',
      description: 'モール内の使い勝手の良いファミリー洋食。お子様プレートやキッズチェアが揃い、駅直結でベビーカー来店にも便利。授乳室・おむつ替え台もモール内で利用可。',
      strollerOk: true,
      kidsMenu: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      allergenInfo: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 大阪・福島エリア（osaka-fukushima）
  // ===========================================================
  'osaka-fukushima': [
    {
      name: '福島 ル・コントワール・ド・ブノワ',
      genre: 'french',
      area: '福島駅から徒歩5分',
      description: '気軽に楽しめるフレンチビストロ。シェアしやすいランチコースは子連れママ会にも使われる。テーブル間にゆとりがあり、ベビーカー入店も相談可。',
      strollerOk: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '福島 うどん家 麺喜やまだ',
      genre: 'noodles',
      area: '福島駅から徒歩3分',
      description: '本格手打ちうどんの人気店。かけうどんは子供にも食べやすく、取り分けやすい。テーブル席ありで家族利用にも便利。回転が速く混雑時間を外しての来店がおすすめ。',
      kidsChair: true,
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '福島 ラ・シーム（ランチ）',
      genre: 'french',
      area: '福島駅から徒歩7分',
      description: 'ミシュラン星付きの名店。子連れランチは要相談だが、個室席があり、特別な記念日のファミリー利用にも使われる。シェアスタイルの取り分けも可能。',
      privateRoom: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '5,000円〜',
      popular: true,
    },
    {
      name: 'カフェ・ド・パリ 福島',
      genre: 'cafe',
      area: '福島駅から徒歩4分',
      description: 'カジュアルなフレンチカフェ。キッシュやサンドイッチ、デザートが揃い、ベビーカー来店も多い。テーブル間にゆとりがあり、ママ友会の利用が目立つ人気店。',
      strollerOk: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 大阪・中崎町エリア（osaka-nakazakicho）
  // ===========================================================
  'osaka-nakazakicho': [
    {
      name: '中崎町 太陽ノ塔本店',
      genre: 'cafe',
      area: '中崎町駅から徒歩3分',
      description: '中崎町を代表する古民家カフェ。フレンチトーストや自家製ケーキが看板で、雑誌掲載歴多数。テーブル席メインで、子連れママの来店も多い人気店。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '中崎町 緑の小道',
      genre: 'cafe',
      area: '中崎町駅から徒歩5分',
      description: '植物に囲まれた一軒家カフェ。プレートランチや自家製スイーツが揃い、ゆっくり過ごせる落ち着いた空間。テーブル席で家族でも訪れやすい雰囲気。',
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '中崎町 喫茶アラビヤ',
      genre: 'cafe',
      area: '中崎町駅から徒歩4分',
      description: '昭和創業の老舗喫茶。クラシカルなコーヒーとモーニングが看板で、子供にも食べやすいトーストセットが揃う。落ち着いた雰囲気で休憩がてら立ち寄れる。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '中崎町 グリーンペッパー',
      genre: 'cafe',
      area: '中崎町駅から徒歩4分',
      description: '中崎町の古民家を改装したカフェ。サンドイッチや自家製スイーツが揃い、ゆったり過ごせる落ち着いた空間。テーブル席のある一軒家造りで家族でも訪れやすい。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 京都・京都駅エリア（kyoto-station）
  // ===========================================================
  'kyoto-station': [
    {
      name: '京都駅 はしたて',
      genre: 'washoku',
      area: '京都駅直結（JR京都伊勢丹3F）',
      description: '和久傳系列の手軽な和食店。鯛ちらし丼やそばが看板で、子供にも食べやすい優しい味付け。百貨店内のため授乳室・おむつ替え台が完備されベビーカー来店にも安心。',
      strollerOk: true,
      kidsChair: true,
      kidsCutlery: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '京都駅 中村藤吉本店 京都駅店',
      genre: 'sweets',
      area: '京都駅直結（JR京都伊勢丹3F）',
      description: '宇治の老舗茶舗の京都駅店。抹茶パフェや生茶ゼリイが看板で、子供にも食べやすい抹茶スイーツ。駅直結で雨天でも安心、ベビーカー利用にも対応した広いフロア。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都駅 イノダコーヒ 京都駅前支店',
      genre: 'cafe',
      area: '京都駅から徒歩3分（ポルタ地下街）',
      description: '京都の老舗イノダコーヒの京都駅支店。コーヒーとサンドイッチ、ケーキが揃い、子供にも食べやすい軽食が中心。地下街なのでベビーカー移動も平坦で安心。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都駅 茶寮都路里 京都伊勢丹店',
      genre: 'sweets',
      area: '京都駅直結（JR京都伊勢丹6F）',
      description: '祇園辻利の系列で、抹茶パフェの代表格。子供にも食べやすい和スイーツが揃い、家族での休憩に便利。百貨店内のためベビーカー・授乳設備が利用しやすい。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都駅 京都拉麺小路 ますたに',
      genre: 'noodles',
      area: '京都駅直結（京都拉麺小路10F）',
      description: '京都背脂醤油の老舗「ますたに」のラーメン小路店。子供向けには小盛り対応もしてもらえ、テーブル席もあり家族で利用できる。フードコート的に立ち寄りやすい。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table', 'counter'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 京都・河原町エリア（kyoto-kawaramachi）
  // ===========================================================
  'kyoto-kawaramachi': [
    {
      name: '京都 喫茶ソワレ',
      genre: 'cafe',
      area: '河原町駅から徒歩3分（西木屋町）',
      description: '青い照明で知られる昭和創業の老舗喫茶。看板のゼリーポンチは子供と取り分けやすく、レトロな雰囲気を楽しめる。雑誌掲載歴多数の京都を代表する純喫茶。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '京都 グリル小宝',
      genre: 'yoshoku',
      area: '河原町駅から徒歩15分（岡崎）',
      description: '創業1961年の老舗洋食店。オムライスやハヤシライスが看板で、子供にも食べやすい優しい味付け。テーブル席メインで家族の祝事や週末ランチに人気。',
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 スマート珈琲店',
      genre: 'cafe',
      area: '河原町駅から徒歩5分（寺町通）',
      description: '創業1932年の老舗喫茶。ホットケーキやフレンチトーストが看板で、子供と取り分けて楽しめる。テーブル席のあるレトロな雰囲気で京都の朝食定番店として愛される。',
      kidsCutlery: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 イノダコーヒ 本店',
      genre: 'cafe',
      area: '河原町駅から徒歩10分（堺町通三条）',
      description: '創業1940年の京都を代表する老舗喫茶。サンドイッチやモーニングが看板で、子供にも食べやすい軽食が揃う。中庭のある一軒家造りで落ち着いた雰囲気。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 SONGBIRD COFFEE',
      genre: 'cafe',
      area: '河原町駅から徒歩10分（夷川通）',
      description: '北欧家具の店主が営むカフェ。チキンと野菜のプレートや自家製ケーキが揃い、ゆったりとしたテーブル席で家族利用にも対応。雑誌掲載歴のある京都の人気カフェ。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 おばんざい おかる',
      genre: 'washoku',
      area: '河原町駅から徒歩5分（先斗町）',
      description: '京都のおばんざい店。小鉢の盛り合わせ定食は取り分けに最適で、子供にも優しい味付け。座敷席もあり、家族でゆっくり京都の家庭料理を楽しめる。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 京都・四条エリア（kyoto-shijo）
  // ===========================================================
  'kyoto-shijo': [
    {
      name: '京都 % ARABICA Kyoto 藤井大丸店',
      genre: 'cafe',
      area: '四条駅直結（藤井大丸B1）',
      description: '世界に展開する京都発のコーヒー専門店。エスプレッソやラテが看板で、子供にはミルクを用意してもらえる。百貨店内のため授乳室・おむつ替え台が利用可。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['counter', 'table'],
      diaperChangingTable: true,
      nursingRoom: true,
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '京都 にしんそば 松葉本店',
      genre: 'noodles',
      area: '四条駅から徒歩3分（南座向かい）',
      description: '創業1861年、にしんそば発祥の老舗。甘く炊いたにしんが子供にも食べやすく、上品なだしのかけそばと相性抜群。座敷席もあり家族でゆっくり食事できる。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 鍵善良房 四条本店',
      genre: 'sweets',
      area: '四条駅から徒歩5分（祇園）',
      description: '創業江戸時代の老舗和菓子店。看板の「くずきり」は黒蜜で食べる名物で、家族で取り分けて楽しめる。座敷席のある喫茶部があり、子連れでもゆっくり過ごせる。',
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 % ZEN CAFE',
      genre: 'sweets',
      area: '四条駅から徒歩7分（祇園 弁財天町）',
      description: '老舗和菓子「鍵善良房」がプロデュースする現代的な和カフェ。和菓子と季節の生菓子が看板で、子供にも食べやすい甘味。テーブル席は落ち着いた空間。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 文の助茶屋 本店',
      genre: 'sweets',
      area: '四条駅から徒歩15分（東山）',
      description: '創業1909年の和スイーツ茶屋。わらび餅やぜんざいが看板で、子供にも食べやすい和スイーツ。座敷席のある町家造りで家族でゆっくり休憩できる。',
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 京都・嵐山エリア（kyoto-arashiyama）
  // ===========================================================
  'kyoto-arashiyama': [
    {
      name: '京都 嵐山 % ARABICA Kyoto 嵐山',
      genre: 'cafe',
      area: '嵐山駅から徒歩5分（渡月橋たもと）',
      description: '渡月橋のたもとに位置するアラビカコーヒー嵐山店。テラス席から桂川を望み、子供と散歩がてら立ち寄れる人気カフェ。テイクアウト中心だが座席もあり。',
      strollerOk: true,
      seatingType: ['counter', 'terrace'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '京都 嵐山 老松 嵐山店',
      genre: 'sweets',
      area: '嵐山駅から徒歩5分',
      description: '京都の老舗和菓子「老松」の嵐山店。夏のかき氷や春の桜餅など季節の和菓子が看板。座敷席で家族でゆっくり過ごせる町家造りの一軒家。',
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '京都 嵐山 鯛匠 HANANA',
      genre: 'washoku',
      area: '嵐山駅から徒歩5分',
      description: '鯛茶漬けが看板の和食店。胡麻だれで食べる鯛茶漬けは子供にも食べやすく、お出汁茶漬けとして二度楽しめる。座敷席もあり家族でゆっくり食事できる。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '京都 嵐山 eX cafe 京都嵐山本店',
      genre: 'cafe',
      area: '嵐山駅から徒歩4分',
      description: '町家を改装したモダンな和カフェ。自分で焼く「ほくほくお団子セット」は子供と一緒に楽しめる体験型メニュー。日本庭園を望む座敷席もあり家族の観光休憩に人気。',
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 嵐山 ぎゃあてい',
      genre: 'washoku',
      area: '嵐山駅すぐ（嵐電嵐山駅前）',
      description: '京おばんざいバイキングの店。20種類以上のおばんざいから取り分けて選べるため、子供の好き嫌いにも対応しやすい。テーブル席で家族利用が多い。',
      kidsChair: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 京都・北大路エリア（kyoto-kitaoji）
  // ===========================================================
  'kyoto-kitaoji': [
    {
      name: '京都 北山 マールブランシュ 北山本店',
      genre: 'sweets',
      area: '北山駅から徒歩3分',
      description: '京都土産で有名な「茶の菓」のマールブランシュ本店。サロン併設で、ケーキや抹茶パフェが楽しめる。テーブル席はゆとりがあり、ベビーカー来店も多い人気店。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 北山 アッサンブラージュ カキモト',
      genre: 'sweets',
      area: '北山駅から徒歩10分',
      description: '京都を代表するパティスリーのサロン。チョコレートやケーキは大人向けの上品な甘さだが、家族での記念日や週末のティータイムに使いやすい。テーブル席メイン。',
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '京都 北山 IN THE GREEN',
      genre: 'cafe',
      area: '北大路駅から徒歩10分（京都府立植物園隣）',
      description: '京都府立植物園隣のガーデンカフェ。テラス席があり、子供と一緒に植物園散策の前後に立ち寄れる。ピザやパスタが揃い、家族でシェアしやすいメニュー構成。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table', 'terrace'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京都 北山 ノースショア カフェ＆ダイニング 北山店',
      genre: 'cafe',
      area: '北山駅から徒歩2分',
      description: 'ハワイアン×ヘルシーをコンセプトにしたカフェダイニング。アサイーボウルやサラダプレートが看板で、子供にも食べやすいメニュー。テーブル席がゆったりで家族利用に便利。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table', 'terrace'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 神戸・三宮エリア（kobe-sannomiya）
  // ===========================================================
  'kobe-sannomiya': [
    {
      name: '神戸 グリル一平 本店',
      genre: 'yoshoku',
      area: '三宮駅から徒歩15分（新開地）',
      description: '創業1952年の老舗洋食店。ハンバーグやエビフライ、オムライスが看板で、子供にも食べやすい優しい味付け。座敷席もあり家族でゆっくり食事できる神戸を代表する洋食店。',
      privateRoom: true,
      kidsChair: true,
      kidsCutlery: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 西村珈琲店 三宮店',
      genre: 'cafe',
      area: '三宮駅から徒歩3分',
      description: '神戸を代表する老舗喫茶。サイフォン式コーヒーとサンドイッチが看板で、子供にも食べやすいトーストやプリンが揃う。落ち着いたテーブル席で家族での休憩に便利。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 三宮 ステーキ ランド神戸館',
      genre: 'teppan',
      area: '三宮駅から徒歩5分',
      description: '神戸牛を目の前で焼いてくれる鉄板焼き店。子供向けには小盛り対応もあり、家族で神戸牛を体験できる。カウンター席メインだが個室もあり、特別な食事にも使える。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['counter', 'table'],
      shareDish: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '神戸 三宮 ユーハイム 神戸元町本店',
      genre: 'sweets',
      area: '三宮駅から徒歩7分（元町商店街）',
      description: '日本で初めてバウムクーヘンを焼いた老舗洋菓子店の本店。バウムクーヘンは子供にも食べやすい優しい甘さ。サロン併設で、家族のおやつ・手土産に定番。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 三宮 にしむら珈琲 中山手本店',
      genre: 'cafe',
      area: '三宮駅から徒歩7分（中山手通）',
      description: '創業1948年の老舗珈琲店本店。会員制サロンの趣を残しつつ、一般客もモーニングやランチが楽しめる。テーブル席のある落ち着いた空間で家族でも訪れやすい。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 神戸・元町エリア（kobe-motomachi）
  // ===========================================================
  'kobe-motomachi': [
    {
      name: '神戸 元町 別館 牡丹園',
      genre: 'chinese',
      area: '元町駅から徒歩3分（南京町）',
      description: '南京町の老舗中華。点心や焼売、麻婆豆腐などが揃い、子供にも食べやすい中華のラインナップ。座敷席もあり、家族で気軽に中華料理を楽しめる。',
      privateRoom: true,
      kidsChair: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 元町ケーキ',
      genre: 'sweets',
      area: '元町駅から徒歩5分',
      description: '看板商品「ざくろ」で知られる老舗洋菓子店。素朴ながら子供にも食べやすい優しい甘さで、家族のおやつ・手土産に定番。テイクアウト中心だがイートインも可。',
      stepFree: true,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '神戸 元町 大同行',
      genre: 'chinese',
      area: '元町駅から徒歩4分（南京町）',
      description: '南京町の点心専門店。小籠包や焼売、ちまきなどが揃い、子供にも食べやすい中華点心のラインナップ。テーブル席があり、家族で南京町散策の合間に立ち寄れる。',
      kidsChair: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '神戸 元町 観音屋 元町本店',
      genre: 'cafe',
      area: '元町駅から徒歩3分',
      description: 'デンマークチーズケーキで有名な神戸の老舗カフェ。温めて食べるチーズケーキは子供にも食べやすい優しい甘さで、家族のおやつタイムに人気。テーブル席メイン。',
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  // ===========================================================
  // 神戸・ハーバーランドエリア（kobe-harborland）
  // ===========================================================
  'kobe-harborland': [
    {
      name: '神戸 ハーバーランド フィッシュダンス',
      genre: 'italian',
      area: 'ハーバーランド駅から徒歩10分（メリケンパーク）',
      description: 'メリケンパークの海辺に面したカフェレストラン。テラス席から港の景色を望み、子供と散歩がてら立ち寄れる。パスタやピザがシェアしやすく、家族利用が多い。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table', 'terrace'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '神戸 ハーバーランド モザイク 神戸風月堂',
      genre: 'sweets',
      area: 'ハーバーランド駅から徒歩5分（モザイク内）',
      description: 'ゴーフルで有名な神戸風月堂の支店。サロン併設で、ケーキや軽食が楽しめる。モール内のため授乳室・おむつ替え台が利用しやすく、ベビーカー来店にも安心。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '神戸 ハーバーランド ステーキハウス キヨミズ',
      genre: 'teppan',
      area: 'ハーバーランド駅から徒歩7分（umie内）',
      description: '神戸牛をカジュアルに楽しめる鉄板焼き店のumie店。テーブル席もあり、家族で神戸牛を体験できる。モール内のため授乳室・おむつ替え台が利用しやすい。',
      strollerOk: true,
      kidsChair: true,
      stepFree: true,
      seatingType: ['table', 'counter'],
      diaperChangingTable: true,
      nursingRoom: true,
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜5,000円',
    },
  ],

  // ===========================================================
  // 神戸・六甲エリア（kobe-rokko）
  // ===========================================================
  'kobe-rokko': [
    {
      name: '神戸 六甲 ケーニヒスクローネ 六甲本店',
      genre: 'sweets',
      area: '六甲駅から徒歩5分',
      description: '神戸の老舗洋菓子店「ケーニヒスクローネ」の本店。クローネやプリンが看板で、子供にも食べやすい優しい甘さ。サロン併設で、家族のおやつタイムに人気。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 六甲 アンリ・シャルパンティエ 芦屋本店',
      genre: 'sweets',
      area: '六甲駅から電車5分（芦屋本店）',
      description: 'フィナンシェで全国区になった芦屋の洋菓子店本店。サロン併設で、ケーキやパフェが楽しめる。テーブル席のある落ち着いた空間で家族での休憩に便利。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
  ],

  // ===========================================================
  // 神戸・岡本エリア（kobe-okamoto）
  // ===========================================================
  'kobe-okamoto': [
    {
      name: '神戸 岡本 ビゴの店 岡本本店',
      genre: 'bakery',
      area: '岡本駅から徒歩3分',
      description: 'フランス人パン職人フィリップ・ビゴが開いた神戸を代表するブーランジェリーの本店。バゲット・クロワッサンが看板で、イートインスペースもあり子供のおやつに気軽に立ち寄れる。',
      strollerOk: true,
      seatingType: ['table', 'counter'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 岡本 フロインドリーブ 本店',
      genre: 'bakery',
      area: '岡本駅から徒歩20分（中山手通）',
      description: '創業1924年、教会を改装した神戸の老舗ベーカリーカフェ。サンドイッチやケーキが揃うサロン併設で、子供にも食べやすい軽食ラインナップ。雑誌掲載歴多数。',
      strollerOk: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '神戸 岡本 イスズベーカリー 本店',
      genre: 'bakery',
      area: '岡本駅から電車8分（三宮本店）',
      description: '神戸の老舗ベーカリー「イスズベーカリー」の本店。山型食パンやデニッシュが看板で、子供のおやつ・朝食パンに定番。テイクアウト中心だがイートインスペースも。',
      stepFree: true,
      seatingType: ['table', 'counter'],
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],
};
