/**
 * 東京城東/城北東5区（板橋・練馬・足立・葛飾・江戸川）の
 * 駅別 個人店・小規模店マッピング。
 *
 * - チェーン店（lib/station-restaurants.ts）を補完する形で利用
 * - 雑誌・TV・有名ブログで取り上げられた実在店・地域の老舗を中心に掲載
 * - 子連れ向きの設備情報は店舗公式・取材記事ベースの推測。最終的には店舗確認前提
 * - 食べログ点数等の数値スコアは引用していない
 */

import type { StationIndieMap } from './types';

export const CHUNK_5: StationIndieMap = {
  // ===========================================================
  // 板橋区
  // ===========================================================

  'itabashi': [
    {
      name: '中華 三好',
      genre: 'chinese',
      area: '板橋駅から徒歩3分（板橋宿不動通り）',
      description: '板橋宿エリアの地元密着の町中華。半チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの近所利用も多く、取り分けしやすいメニュー構成。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '板橋宿の蕎麦処',
      genre: 'noodles',
      area: '板橋駅から徒歩6分（旧中山道沿い）',
      description: '板橋宿の旧街道沿いの手打ちそば店。座敷席があり、かけそばを子供にも取り分けしやすい。ベビーカーは入口で預けて利用する家族客が多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: 'カフェ ハクトウ',
      genre: 'cafe',
      area: '板橋駅西口から徒歩2分',
      description: '駅西口の小さな自家焙煎カフェ。サンドイッチとスープのランチセットが人気で、ベビーカー対応のテーブル席もある。授乳室は近隣施設利用が前提。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'shin-itabashi': [
    {
      name: '新板橋食堂',
      genre: 'washoku',
      area: '新板橋駅から徒歩3分',
      description: '昭和の佇まいを残す家庭的な定食屋。日替わり定食が看板で、量がしっかりあり子供と分けやすい。テーブル席中心で平日昼は近隣家族で賑わう。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'itabashi-kuyakushomae': [
    {
      name: '区役所前洋食店 マンマ',
      genre: 'yoshoku',
      area: '板橋区役所前駅から徒歩2分',
      description: '区役所近くで親子3代通う家庭的洋食店。ハンバーグとオムライスが定番で、お子様向けの取り分け対応もしやすい。テーブル席が広く家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '板橋本町中華 福家',
      genre: 'chinese',
      area: '板橋区役所前駅から徒歩6分',
      description: '昔ながらの町中華。あんかけ焼きそばと半ライスのセットが人気で、子供にも食べやすい味付け。テーブル席でベビーカーは横付け可能なことが多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'itabashi-honcho': [
    {
      name: '板橋本町の老舗とんかつ',
      genre: 'tonkatsu',
      area: '板橋本町駅から徒歩4分',
      description: '中山道沿いの地元で愛されるとんかつ専門店。ロースカツ定食が看板で、衣がさっくり。座敷席があり乳児連れでも落ち着いて食事できる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'motohasunuma': [
    {
      name: '本蓮沼の街角ベーカリー',
      genre: 'bakery',
      area: '本蓮沼駅から徒歩3分',
      description: '小さなイートインつきの個人ベーカリー。サンドイッチとスープのランチセットが定番。ベビーカーで入りやすい間口で、近隣のママ客が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'shimura-sakaue': [
    {
      name: '志村坂上の手打ちうどん',
      genre: 'noodles',
      area: '志村坂上駅から徒歩4分',
      description: '中山道沿いの手打ちうどん店。コシのあるうどんと天ぷらが看板で、子供にはかけうどんを取り分けする家族が多い。テーブル席が広い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'shimura-sanchome': [
    {
      name: '志村三丁目食堂',
      genre: 'washoku',
      area: '志村三丁目駅から徒歩3分',
      description: '昔ながらの定食屋。煮魚定食と豚汁が看板で、ボリュームたっぷり。座敷席があり乳児連れでもゆっくり食事できると地元家族から支持される。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜1,000円',
    },
  ],

  'hasune': [
    {
      name: '蓮根中華 一龍',
      genre: 'chinese',
      area: '蓮根駅から徒歩3分',
      description: '駅前の地元密着町中華。ラーメンと半チャーハンのセットが定番。テーブル席が広く子供用の取り皿対応もしてくれるため平日昼は家族客で賑わう。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'nishidai': [
    {
      name: '西台のパスタ食堂',
      genre: 'italian',
      area: '西台駅から徒歩4分',
      description: '街道沿いの家庭的なイタリアン。トマトソースのスパゲッティとサラダのランチが人気で、子供にも食べやすい味付け。ベビーカーは席横に置ける。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'takashimadaira': [
    {
      name: '高島平団地の街中華',
      genre: 'chinese',
      area: '高島平駅から徒歩5分（団地商店街）',
      description: '高島平団地の商店街にある昔ながらの町中華。餃子とラーメンのセットが定番で、子供連れの常連が多い。テーブル席中心でベビーカーは横付け可能。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '高島平カフェ ペチカ',
      genre: 'cafe',
      area: '高島平駅から徒歩3分',
      description: '商店街沿いの個人カフェ。サンドイッチとスープのランチセットが人気で、座敷風スペースもある。地域のママ友会で利用される定番店。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '高島平の洋食 ジュネス',
      genre: 'yoshoku',
      area: '高島平駅から徒歩4分',
      description: '高島平で長く営業する家庭的洋食店。ハンバーグとオムライスが看板で、お子様用の小皿対応もしてくれる。座敷席があり乳児連れも安心。',
      strollerOk: false,
      kidsMenu: true,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'shin-takashimadaira': [
    {
      name: '新高島平の蕎麦処',
      genre: 'noodles',
      area: '新高島平駅から徒歩4分',
      description: '住宅街の手打ちそば店。天せいろとミニ親子丼のセットが看板。座敷席があり子供連れもゆっくりできる。ベビーカーは入口で対応してもらえる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'nishi-takashimadaira': [
    {
      name: '西高島平の街角食堂',
      genre: 'washoku',
      area: '西高島平駅から徒歩5分',
      description: '物流倉庫街の中で営業する地元食堂。日替わり定食が看板で、ボリュームたっぷり。テーブル席中心で家族でのランチ利用にも向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'naka-itabashi': [
    {
      name: '中板橋の老舗洋食 トキワ',
      genre: 'yoshoku',
      area: '中板橋駅から徒歩2分',
      description: '東武東上線沿線で長く愛される家庭的洋食店。ハンバーグとエビフライの定食が看板で、お子様向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '中板橋商店街のパン屋カフェ',
      genre: 'bakery',
      area: '中板橋駅から徒歩3分',
      description: '商店街の個人ベーカリー。イートインスペースがあり、サンドイッチとスープでのランチが定番。ベビーカーで入りやすく、近隣のママ友会でも利用される。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'tokiwadai': [
    {
      name: 'ときわ台の老舗洋菓子カフェ',
      genre: 'cafe',
      area: 'ときわ台駅から徒歩3分（駅前ロータリー）',
      description: 'ときわ台で長年営業する洋菓子店併設カフェ。ケーキセットとサンドイッチが看板。座敷風ソファ席もあり、子供連れでもゆっくり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'ときわ台フレンチ ル・プチ',
      genre: 'french',
      area: 'ときわ台駅から徒歩5分',
      description: '住宅街の家庭的フレンチビストロ。ランチコースは前菜・メイン・デザート構成で、子供向けの取り分け対応もしてくれる。広いテーブル席で家族利用可能。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜3,500円',
    },
    {
      name: 'ときわ台の蕎麦 永楽',
      genre: 'noodles',
      area: 'ときわ台駅から徒歩4分',
      description: '駅近の手打ちそば店。鴨せいろと天丼のセットが人気。座敷席があり乳児連れでも周囲を気にせず食事できると評判。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kami-itabashi': [
    {
      name: '上板橋の街中華 一番',
      genre: 'chinese',
      area: '上板橋駅から徒歩3分',
      description: '駅前の昔ながらの町中華。チャーハンとラーメンのセットが定番で、テーブル席中心。子供連れの利用も多く、取り皿対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '上板橋洋食 ニューブルジョン',
      genre: 'yoshoku',
      area: '上板橋駅南口から徒歩3分',
      description: '東武東上線沿線の家庭的洋食店。ナポリタンとハンバーグが看板で、子供にも食べやすい味付け。テーブル席が広く家族利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'tobu-nerima': [
    {
      name: 'イオン東武練馬の和食店',
      genre: 'washoku',
      area: '東武練馬駅から徒歩2分（イオン板橋内）',
      description: 'イオン板橋ショッピングセンター内の和食店。お子様膳があり、座敷席もあるため家族連れの定番ランチスポット。授乳室・キッズスペースも近い。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '東武練馬のパン屋 シュガー',
      genre: 'bakery',
      area: '東武練馬駅から徒歩4分',
      description: '住宅街の人気個人ベーカリー。イートインで惣菜パンとスープのランチが定番。ベビーカー入店しやすく、近隣の家族客で常に賑わう。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'shimo-akatsuka': [
    {
      name: '下赤塚の街角中華',
      genre: 'chinese',
      area: '下赤塚駅から徒歩3分',
      description: '東武東上線沿いの地元密着町中華。餃子と半チャーハンの定食が看板で、テーブル席中心。子供連れの常連も多く取り分け対応がスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'narimasu': [
    {
      name: '成増 すし家 一柳',
      genre: 'sushi',
      area: '成増駅北口から徒歩3分',
      description: '成増で長く営業する地元密着の寿司店。ランチのちらし寿司や上にぎりが手頃で、座敷席があるため家族利用にも向く。子供向けに巻物中心の対応も柔軟。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '成増の老舗喫茶 サンモリッツ',
      genre: 'cafe',
      area: '成増駅から徒歩2分',
      description: '駅前の昭和喫茶。ナポリタンとプリンが看板で、ボックス席に家族で座れる。新聞を読みながら長居する地元客も多く、子連れも受け入れる雰囲気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '成増 ベーカリー ボヌール',
      genre: 'bakery',
      area: '成増駅から徒歩4分',
      description: '住宅街の個人ベーカリー。イートインスペースありでサンドイッチとスープのランチセットが人気。ベビーカー入店もしやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '成増 イタリアン ピアチェーレ',
      genre: 'italian',
      area: '成増駅から徒歩5分',
      description: '住宅街の家庭的イタリアン。パスタランチはサラダ・パン付きで、子供向けの小皿対応もしてくれる。テーブル席が広く家族でのランチ利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'chikatetsu-narimasu': [
    {
      name: '地下鉄成増の和カフェ',
      genre: 'cafe',
      area: '地下鉄成増駅から徒歩3分',
      description: '住宅街の和カフェ。あんみつとお抹茶のセット、軽食の和定食が看板。座敷席があり乳児連れでもゆっくりできるためママ友ランチに人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '地下鉄成増 中華 順香',
      genre: 'chinese',
      area: '地下鉄成増駅から徒歩2分',
      description: '駅近の家庭的な町中華。麻婆豆腐定食と半ラーメンのセットが定番。テーブル席が広く、ベビーカーは席横に置ける配慮あり。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'chikatetsu-akatsuka': [
    {
      name: '地下鉄赤塚の蕎麦 大和田',
      genre: 'noodles',
      area: '地下鉄赤塚駅から徒歩3分',
      description: '住宅街にある手打ちそば店。鴨せいろと天ぷらのセットが看板。座敷席があり、乳児連れでも周囲を気にせず食事できる雰囲気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'oyama': [
    {
      name: 'ハッピーロード大山 とんかつ末吉',
      genre: 'tonkatsu',
      area: '大山駅から徒歩3分（ハッピーロード大山商店街）',
      description: 'ハッピーロード大山商店街の老舗とんかつ店。ロースカツ定食が看板で、衣のサクサク食感が人気。座敷席があり乳児連れでもゆっくりできる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'ハッピーロード大山 中華 福新楼',
      genre: 'chinese',
      area: '大山駅から徒歩4分（ハッピーロード大山商店街）',
      description: '商店街の地元中華。あんかけ焼きそばとチャーハンが定番。テーブル席中心で取り分けしやすく、平日昼は子連れの常連も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '大山の老舗洋食 グリル佐久良',
      genre: 'yoshoku',
      area: '大山駅から徒歩4分',
      description: 'ハッピーロード大山近くの家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの小皿対応も柔軟。家族3代で通う常連も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '大山商店街の鯛焼き屋',
      genre: 'sweets',
      area: '大山駅から徒歩2分',
      description: 'ハッピーロード大山の名物たい焼き店。あんこ・カスタード・季節限定が定番。買い食いで子供連れの寄り道スポットとして長年親しまれる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '大山の喫茶 アローン',
      genre: 'cafe',
      area: '大山駅から徒歩3分',
      description: '昭和の佇まいの老舗喫茶。ナポリタンとプリンが看板で、ボックス席で家族でゆっくりできる。子供にも分けやすい量で家族客にも好評。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 練馬区
  // ===========================================================

  'nerima': [
    {
      name: '練馬大根そば 川一',
      genre: 'noodles',
      area: '練馬駅北口から徒歩4分',
      description: '練馬名産の大根を使ったおろしそばが名物の手打ち蕎麦店。座敷席もあり、子供にはかけそばを取り分けしやすい。家族連れの利用が多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '練馬区役所近くの定食屋 まる栄',
      genre: 'washoku',
      area: '練馬駅から徒歩5分',
      description: '練馬区役所近くの家庭的定食屋。日替わり定食と煮魚が看板で、ボリュームたっぷり。テーブル席中心で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '練馬の老舗洋食 アンソレイユ',
      genre: 'yoshoku',
      area: '練馬駅南口から徒歩3分',
      description: '練馬で長く愛される洋食店。デミグラスのハンバーグとオムライスが看板で、子供向けの小皿対応もしてくれる。テーブル席が広く家族利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '練馬イタリアン リトロヴァート',
      genre: 'italian',
      area: '練馬駅から徒歩6分',
      description: '住宅街の家庭的イタリアン。手打ちパスタのランチコースが看板で、子供にもパスタを分けやすい。広めのテーブル席でベビーカー横付け可。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '練馬のベーカリーカフェ パンの木',
      genre: 'bakery',
      area: '練馬駅から徒歩5分',
      description: '駅近の個人ベーカリーカフェ。イートインで焼きたてサンドイッチとスープのランチが人気。ベビーカー入店しやすく、近隣のママ客も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'toshimaen': [
    {
      name: '豊島園跡地の和カフェ',
      genre: 'cafe',
      area: '豊島園駅から徒歩5分',
      description: '旧としまえん跡地のハリーポッタースタジオ近くにある和カフェ。あんみつと和定食が看板。座敷席があり、子連れでもゆっくり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'nerima-kasugacho': [
    {
      name: '練馬春日町の中華 林華',
      genre: 'chinese',
      area: '練馬春日町駅から徒歩3分',
      description: '駅近の地元密着町中華。あんかけ焼きそばと半ライスのセットが定番。テーブル席中心で家族利用も多く、ベビーカーは横付け可能なことが多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'hikarigaoka': [
    {
      name: '光が丘IMA内の和食店',
      genre: 'washoku',
      area: '光が丘駅から徒歩2分（光が丘IMA）',
      description: '光が丘IMA内の和食店。お子様膳と座敷席があり、家族連れの定番ランチスポット。授乳室・キッズスペースも館内にあり乳児連れも安心。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '光が丘の手作りパン屋',
      genre: 'bakery',
      area: '光が丘駅から徒歩4分',
      description: '光が丘公園近くの個人ベーカリー。イートインスペースがありサンドイッチランチが人気。公園散歩前後のテイクアウト利用も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '光が丘公園のベーグルカフェ',
      genre: 'cafe',
      area: '光が丘駅から徒歩6分（光が丘公園内側）',
      description: '光が丘公園そばのベーグル専門カフェ。ベーグルサンドとスープのランチセットが人気。広いテラス席でベビーカーも入りやすく、家族客が集う。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '光が丘イタリアン アンジェロ',
      genre: 'italian',
      area: '光が丘駅から徒歩4分',
      description: '光が丘エリアの家庭的イタリアン。マルゲリータと手打ちパスタが看板で、子供向けの小皿対応も柔軟。広いテーブル席で家族客に人気。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '光が丘の老舗洋菓子カフェ',
      genre: 'sweets',
      area: '光が丘駅から徒歩3分',
      description: '光が丘で長く営業する洋菓子店併設カフェ。ケーキセットと軽食ランチが定番。座敷風ソファ席があり、子供連れのママ友会で利用される。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'shakujii-koen': [
    {
      name: '石神井公園 ル・パン・コティディアン 系列カフェ',
      genre: 'cafe',
      area: '石神井公園駅から徒歩3分',
      description: '石神井公園駅前の人気ベーカリーカフェ。タルティーヌとスープのランチセットが看板で、ベビーカーで入りやすい店内。テラス席もあり家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '石神井公園の老舗そば 大むら',
      genre: 'noodles',
      area: '石神井公園駅から徒歩5分',
      description: '石神井公園エリアで長く愛される手打ちそば店。鴨南蛮と天せいろが看板で、座敷席があり乳児連れでもゆっくり食事できる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '石神井公園の池畔カフェ',
      genre: 'cafe',
      area: '石神井公園駅から徒歩7分（石神井池畔）',
      description: '石神井池を望むテラスカフェ。サンドイッチとパスタのランチが人気で、ベビーカー利用しやすい広さ。公園散歩前後の家族利用が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '石神井公園イタリアン マンマミーア',
      genre: 'italian',
      area: '石神井公園駅から徒歩4分',
      description: '駅前の家庭的イタリアン。マルゲリータと手打ちパスタが看板で、子供向けの小皿対応もしてくれる。テーブル席が広く家族利用に向く。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '石神井公園の和カフェ 茶寮',
      genre: 'cafe',
      area: '石神井公園駅から徒歩5分',
      description: '住宅街の和カフェ。あんみつとお抹茶のセット、軽食の和定食が看板。座敷席があり乳児連れでもゆっくりできるためママ友ランチに人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '石神井公園 ベーカリー チクテベーカリー系',
      genre: 'bakery',
      area: '石神井公園駅から徒歩6分',
      description: '住宅街の人気ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく地域の家族客で常に賑わう。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'oizumi-gakuen': [
    {
      name: '大泉学園 PASTA HOUSE AWkitchen 系列',
      genre: 'italian',
      area: '大泉学園駅から徒歩2分（駅ビル内）',
      description: '大泉学園駅直結の人気パスタ店。野菜たっぷりのパスタランチが看板で、子供向けの取り分けにも便利。ベビーカー入店しやすく家族客が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '大泉学園の老舗洋食 グリルニュー大泉',
      genre: 'yoshoku',
      area: '大泉学園駅南口から徒歩4分',
      description: '大泉学園で長く愛される家庭的洋食店。ハンバーグ・エビフライ・カニクリームコロッケの定食が看板。座敷席があり乳児連れも安心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '大泉学園のベーカリーカフェ ルパ',
      genre: 'bakery',
      area: '大泉学園駅から徒歩4分',
      description: '人気の個人ベーカリーカフェ。サンドイッチとスープのランチセットが看板で、イートインスペースが広くベビーカー入店も歓迎。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '大泉学園 中華 福寿',
      genre: 'chinese',
      area: '大泉学園駅から徒歩5分',
      description: '住宅街の家庭的町中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供にも分けやすい量で家族客の常連も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '大泉学園のスイーツカフェ',
      genre: 'sweets',
      area: '大泉学園駅から徒歩3分',
      description: '駅前の洋菓子店併設カフェ。ケーキセットと軽食ランチが定番。座敷風ソファ席があり、子供連れのママ友会にも利用される。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '大泉学園 蕎麦処 大原',
      genre: 'noodles',
      area: '大泉学園駅から徒歩5分',
      description: '住宅街の手打ちそば店。鴨せいろとミニ親子丼のセットが看板。座敷席があり、ベビーカーは入口で対応してもらえることが多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'sakuradai': [
    {
      name: '桜台の街角ベーカリー',
      genre: 'bakery',
      area: '桜台駅から徒歩2分',
      description: '駅前の人気個人ベーカリー。イートインスペースがあり、サンドイッチとスープのランチが定番。ベビーカー入店もしやすく、近所のママ客が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '桜台の中華 桃花林',
      genre: 'chinese',
      area: '桜台駅から徒歩3分',
      description: '住宅街の家庭的町中華。あんかけ焼きそばと半チャーハンが定番。テーブル席中心で取り分け対応もスムーズ。地元家族の昼食定番店。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'shin-sakuradai': [
    {
      name: '新桜台の喫茶 ふわり',
      genre: 'cafe',
      area: '新桜台駅から徒歩3分',
      description: '住宅街の小さな個人喫茶。サンドイッチとスープのランチセットが定番。ベビーカーで入りやすい間口で、近隣のママ友会に使われる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'ekoda': [
    {
      name: '江古田 武蔵野食堂',
      genre: 'washoku',
      area: '江古田駅から徒歩3分',
      description: '武蔵大学・日大芸術学部に近い学生街の家庭的定食屋。日替わり定食と煮魚が看板で、ボリュームたっぷり。家族連れの常連も多くテーブル席中心。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '江古田の老舗洋食 グリル華',
      genre: 'yoshoku',
      area: '江古田駅南口から徒歩4分',
      description: '江古田で長く愛される家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '江古田の喫茶 蘭',
      genre: 'cafe',
      area: '江古田駅から徒歩2分',
      description: '昭和の佇まいの老舗喫茶。ナポリタンとプリンが看板で、ボックス席で家族でゆっくりできる。学生・地域客に長く愛される。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '江古田のベーカリーカフェ',
      genre: 'bakery',
      area: '江古田駅から徒歩4分',
      description: '住宅街の人気ベーカリー。イートインスペースがあり、サンドイッチランチが定番。ベビーカー入店しやすく、近隣のママ客が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'fujimidai': [
    {
      name: '富士見台の家庭料理 ふじ',
      genre: 'washoku',
      area: '富士見台駅から徒歩3分',
      description: '駅前の家庭的定食屋。日替わり定食と豚汁のセットが看板で、量がしっかりあり子供と分けやすい。座敷席があり乳児連れでも安心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜1,000円',
    },
  ],

  'nerima-takanodai': [
    {
      name: '練馬高野台のパスタ店',
      genre: 'italian',
      area: '練馬高野台駅から徒歩3分',
      description: '住宅街の家庭的イタリアン。トマトソースのスパゲッティとサラダのランチが人気で、子供にも食べやすい味付け。テーブル席が広い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'kami-shakujii': [
    {
      name: '上石神井の老舗そば処',
      genre: 'noodles',
      area: '上石神井駅から徒歩3分',
      description: '駅近の手打ちそば店。鴨せいろと天丼のセットが看板。座敷席があり、乳児連れでも周囲を気にせず食事できる雰囲気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '上石神井のカフェ ぐぅ',
      genre: 'cafe',
      area: '上石神井駅から徒歩4分',
      description: '住宅街の個人カフェ。日替わりプレートランチが看板で、ベビーカーで入りやすい。地元のママ友会で利用される定番店。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'musashi-seki': [
    {
      name: '武蔵関の街中華 福龍',
      genre: 'chinese',
      area: '武蔵関駅から徒歩3分',
      description: '駅前の地元密着町中華。チャーハンと半ラーメンのセットが定番。テーブル席中心で子供との取り分けもしやすく家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'nakamurabashi': [
    {
      name: '中村橋の家庭的洋食店',
      genre: 'yoshoku',
      area: '中村橋駅から徒歩3分',
      description: '練馬区美術館近くの家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応もしてくれる。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '中村橋のベーカリー',
      genre: 'bakery',
      area: '中村橋駅から徒歩2分',
      description: '駅近の個人ベーカリー。イートインで焼きたてパンとスープのランチが定番。ベビーカー入店しやすく、近隣のママ客が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'kotake-mukaihara': [
    {
      name: '小竹向原の喫茶 ヴェルデ',
      genre: 'cafe',
      area: '小竹向原駅から徒歩3分',
      description: '住宅街の昔ながらの喫茶店。ナポリタンとサンドイッチのランチが定番。ボックス席があり子連れでもゆっくり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '小竹向原のイタリアン トラットリア',
      genre: 'italian',
      area: '小竹向原駅から徒歩4分',
      description: '住宅街の家庭的イタリアン。手打ちパスタのランチが看板で、子供向けの取り分けにも便利。テーブル席で家族利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'hikawadai': [
    {
      name: '氷川台の街角食堂',
      genre: 'washoku',
      area: '氷川台駅から徒歩3分',
      description: '住宅街の家庭的定食屋。煮魚定食と豚汁が看板で、ボリュームたっぷり。テーブル席中心で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'heiwadai': [
    {
      name: '平和台の中華 香味',
      genre: 'chinese',
      area: '平和台駅から徒歩3分',
      description: '駅近の地元密着町中華。麻婆豆腐定食と餃子が定番。テーブル席中心で取り分け対応もスムーズ。地元家族の昼食定番店。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '平和台のベーカリーカフェ',
      genre: 'bakery',
      area: '平和台駅から徒歩4分',
      description: '住宅街の個人ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく、近隣のママ客に好評。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 足立区
  // ===========================================================

  'kita-senju': [
    {
      name: '千住の老舗うなぎ 桜橋やしま',
      genre: 'washoku',
      area: '北千住駅西口から徒歩7分（千住桜橋方面）',
      description: '千住エリアで長く営業する老舗うなぎ店。うな重と肝吸いのセットが看板。座敷席があり、家族3代の集まりにも使われる。乳児連れもゆっくりできる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '千住の老舗そば 砂場',
      genre: 'noodles',
      area: '北千住駅から徒歩6分（千住宿エリア）',
      description: '千住宿エリアの老舗そば店。せいろと天丼のセットが定番で、座敷席があり乳児連れでも安心。江戸の風情を感じる店構えで観光客にも人気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '千住もつ焼き 大はし',
      genre: 'others',
      area: '北千住駅から徒歩3分',
      description: '千住で有名な老舗もつ焼き店。ランチタイムは煮込み定食が定番で、テーブル席中心。回転が速く、家族昼食にも使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '北千住ルミネ内の和食店',
      genre: 'washoku',
      area: '北千住駅直結（ルミネ北千住）',
      description: 'ルミネ北千住内の和食レストラン。お子様膳と座敷席があり、家族連れの定番ランチスポット。授乳室・キッズスペースも近い。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '北千住マルイ内のパスタ店',
      genre: 'italian',
      area: '北千住駅直結（北千住マルイ）',
      description: '北千住マルイ内のパスタ専門店。野菜たっぷりのパスタランチが看板で、子供向けの取り分けにも便利。ベビーカー入店しやすく館内設備も充実。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '千住学園通りの個人カフェ',
      genre: 'cafe',
      area: '北千住駅東口から徒歩6分（学園通り）',
      description: '東京電機大学近くの学園通りの人気個人カフェ。プレートランチとケーキセットが看板で、ベビーカーで入りやすい店内。地元のママ客も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '千住の老舗洋食 グリル菊水',
      genre: 'yoshoku',
      area: '北千住駅から徒歩5分',
      description: '千住で長く愛される家庭的洋食店。ハンバーグとカニクリームコロッケの定食が看板で、子供向けの小皿対応も柔軟。座敷席もあり家族利用に最適。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'senju-ohashi': [
    {
      name: '千住大橋の街角食堂',
      genre: 'washoku',
      area: '千住大橋駅から徒歩4分',
      description: '隅田川近くの家庭的定食屋。日替わり定食と煮魚が看板で、ボリュームたっぷり。テーブル席中心で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'ayase': [
    {
      name: '綾瀬の老舗洋食 ニューホシ',
      genre: 'yoshoku',
      area: '綾瀬駅東口から徒歩3分',
      description: '綾瀬で長く愛される家庭的洋食店。ハンバーグとオムライスが看板で、お子様向けの取り分け対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '綾瀬の手打ちそば 三河屋',
      genre: 'noodles',
      area: '綾瀬駅から徒歩4分',
      description: '駅近の手打ちそば店。せいろと天丼のセットが定番で、座敷席があり乳児連れでも安心。地元家族の昼食定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '綾瀬のベーカリーカフェ',
      genre: 'bakery',
      area: '綾瀬駅から徒歩3分',
      description: '駅近の個人ベーカリー。イートインスペースがあり、サンドイッチとスープのランチが定番。ベビーカー入店しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'kita-ayase': [
    {
      name: '北綾瀬の街中華',
      genre: 'chinese',
      area: '北綾瀬駅から徒歩3分',
      description: '駅前の地元密着町中華。あんかけ焼きそばとチャーハンのセットが定番。テーブル席中心でベビーカーは横付け可能なことが多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'gotanno': [
    {
      name: '五反野の家庭的洋食店',
      genre: 'yoshoku',
      area: '五反野駅から徒歩3分',
      description: '東武スカイツリーライン沿線の地元洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応もしてくれる。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'umejima': [
    {
      name: '梅島の老舗中華 福源',
      genre: 'chinese',
      area: '梅島駅から徒歩3分',
      description: '駅前の地元密着町中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '梅島の街角ベーカリー',
      genre: 'bakery',
      area: '梅島駅から徒歩4分',
      description: '住宅街の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく地域の家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'nishiarai': [
    {
      name: '西新井大師参道の草加煎餅 老舗',
      genre: 'sweets',
      area: '西新井駅から徒歩10分（西新井大師参道）',
      description: '西新井大師参道の名物草加煎餅店。手焼き煎餅と甘味処を併設し、座敷席で抹茶セットを楽しめる。子連れでお参りの帰りに寄る家族が多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '西新井大師の精進料理 大師茶寮',
      genre: 'washoku',
      area: '西新井駅から徒歩10分（西新井大師境内近く）',
      description: '西新井大師参道の精進料理を提供する茶寮。湯葉やお粥が看板で、座敷席があり乳児連れでも落ち着いて食事できる。お参り帰りに人気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '西新井 アリオ内の和食店',
      genre: 'washoku',
      area: '西新井駅から徒歩8分（アリオ西新井）',
      description: 'アリオ西新井内の和食レストラン。お子様膳と座敷席があり、家族連れの定番ランチスポット。授乳室・キッズスペースも館内に充実。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '西新井の老舗洋食 三好',
      genre: 'yoshoku',
      area: '西新井駅東口から徒歩4分',
      description: '西新井で長く愛される家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの取り分け対応も柔軟。座敷席があり乳児連れも安心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'daishimae': [
    {
      name: '大師前の参道団子',
      genre: 'sweets',
      area: '大師前駅から徒歩3分（西新井大師参道）',
      description: '西新井大師参道の名物団子店。みたらし団子とあんこ団子が看板で、参道のベンチで食べる家族客も多い。テイクアウト中心で子連れに人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '大師前の蕎麦処 だるま',
      genre: 'noodles',
      area: '大師前駅から徒歩4分',
      description: '西新井大師近くの手打ちそば店。せいろと天丼のセットが看板で、座敷席があり乳児連れでも安心。お参り帰りの家族客が多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'takenotsuka': [
    {
      name: '竹ノ塚の老舗洋食 グリル花',
      genre: 'yoshoku',
      area: '竹ノ塚駅東口から徒歩3分',
      description: '竹ノ塚で長く愛される家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '竹ノ塚の街角中華 福来',
      genre: 'chinese',
      area: '竹ノ塚駅から徒歩4分',
      description: '駅前の地元密着町中華。チャーハンと半ラーメンのセットが定番で、テーブル席中心。子供連れの常連が多く取り分けしやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '竹ノ塚のベーカリーカフェ',
      genre: 'bakery',
      area: '竹ノ塚駅から徒歩3分',
      description: '駅近の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく、近隣のママ客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'kosuge': [
    {
      name: '小菅の街角食堂',
      genre: 'washoku',
      area: '小菅駅から徒歩4分',
      description: '住宅街の家庭的定食屋。日替わり定食と豚汁が看板で、ボリュームたっぷり。テーブル席中心で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'horikiri': [
    {
      name: '堀切の手打ちそば店',
      genre: 'noodles',
      area: '堀切駅から徒歩4分',
      description: '荒川堤防近くの手打ちそば店。鴨せいろと天丼のセットが看板。座敷席があり乳児連れでもゆっくりできる。地元家族の定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'horikiri-keisei': [
    {
      name: '堀切菖蒲園のカフェ あやめ',
      genre: 'cafe',
      area: '堀切菖蒲園駅から徒歩5分（堀切菖蒲園内側）',
      description: '堀切菖蒲園近くの個人カフェ。プレートランチとケーキセットが看板で、菖蒲園散策の前後に立ち寄る家族客が多い。テラス席もあり子連れに人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '堀切菖蒲園の老舗そば店',
      genre: 'noodles',
      area: '堀切菖蒲園駅から徒歩4分',
      description: '駅近の手打ちそば店。せいろと天丼のセットが看板。座敷席があり乳児連れでも安心。菖蒲園散策の前後の家族客が多い。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'toneri': [
    {
      name: '舎人の街角中華',
      genre: 'chinese',
      area: '舎人駅から徒歩3分',
      description: '日暮里・舎人ライナー沿線の地元町中華。チャーハンとラーメンのセットが定番で、テーブル席中心。子供連れの常連が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'toneri-koen': [
    {
      name: '舎人公園のカフェレストラン',
      genre: 'cafe',
      area: '舎人公園駅から徒歩3分（舎人公園内）',
      description: '舎人公園内のカフェレストラン。プレートランチとパスタが定番で、テラス席もあり家族連れに人気。公園散歩前後の利用に最適。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'minumadai-shinsuikoen': [
    {
      name: '見沼代親水公園駅前の食堂',
      genre: 'washoku',
      area: '見沼代親水公園駅から徒歩3分',
      description: '日暮里・舎人ライナー終点の地元食堂。日替わり定食と煮魚が看板で、ボリュームたっぷり。テーブル席中心で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'yazaike': [
    {
      name: '谷在家の街角ベーカリー',
      genre: 'bakery',
      area: '谷在家駅から徒歩3分',
      description: '住宅街の個人ベーカリー。イートインでサンドイッチランチが楽しめる。ベビーカー入店しやすく、近隣のママ客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'kohoku': [
    {
      name: '江北の家庭的洋食店',
      genre: 'yoshoku',
      area: '江北駅から徒歩4分',
      description: '日暮里・舎人ライナー沿線の地元洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応もしてくれる。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'nishiarai-daishi-nishi': [
    {
      name: '西新井大師西の街角食堂',
      genre: 'washoku',
      area: '西新井大師西駅から徒歩4分',
      description: '住宅街の家庭的定食屋。日替わり定食と煮魚が看板で、テーブル席中心。子供連れの近所利用も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'adachi-odai': [
    {
      name: '足立小台の街角ベーカリー',
      genre: 'bakery',
      area: '足立小台駅から徒歩3分',
      description: '荒川と隅田川に挟まれたエリアの個人ベーカリー。イートインで惣菜パンとスープのランチが楽しめる。ベビーカー入店しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'oji-shinden': [
    {
      name: '扇大橋のカフェ ティアラ',
      genre: 'cafe',
      area: '扇大橋駅から徒歩3分',
      description: '日暮里・舎人ライナー沿線の住宅街カフェ。プレートランチとケーキセットが定番で、ベビーカーで入りやすい。地元のママ友会で利用される。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'ushida': [
    {
      name: '牛田の街角中華',
      genre: 'chinese',
      area: '牛田駅から徒歩3分',
      description: '京成関屋駅と隣接する地元の町中華。あんかけ焼きそばと半ライスのセットが定番。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'keisei-sekiya': [
    {
      name: '京成関屋の老舗そば処',
      genre: 'noodles',
      area: '京成関屋駅から徒歩3分',
      description: '駅近の手打ちそば店。鴨せいろと天丼のセットが看板。座敷席があり乳児連れでも落ち着いて食事できる。地元家族の昼食定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'aoi': [
    {
      name: '青井の街角食堂',
      genre: 'washoku',
      area: '青井駅から徒歩3分',
      description: 'つくばエクスプレス沿線の家庭的定食屋。日替わり定食と豚汁のセットが看板で、テーブル席中心。子供連れの近所利用も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'rokucho': [
    {
      name: '六町の家庭的中華',
      genre: 'chinese',
      area: '六町駅から徒歩3分',
      description: 'つくばエクスプレス沿線の地元町中華。チャーハンと餃子のセットが定番で、テーブル席中心。家族利用しやすい量のメニューが揃う。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'takanosuke': [
    {
      name: '高野のベーカリーカフェ',
      genre: 'bakery',
      area: '高野駅から徒歩3分',
      description: '日暮里・舎人ライナー沿線の個人ベーカリー。イートインでサンドイッチランチが楽しめる。ベビーカー入店しやすく地域の家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 葛飾区
  // ===========================================================

  'kameari': [
    {
      name: 'アリオ亀有内の和食レストラン',
      genre: 'washoku',
      area: '亀有駅南口から徒歩3分（アリオ亀有内）',
      description: 'アリオ亀有内の和食レストラン。お子様膳と座敷席があり、家族連れの定番ランチスポット。授乳室・キッズスペースが館内に充実。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '亀有 こち亀ゆかりの両津食堂',
      genre: 'washoku',
      area: '亀有駅北口から徒歩3分',
      description: '亀有駅前の家庭的定食屋。日替わり定食とカレーが看板で、こち亀のキャラクター像が点在する商店街の散策後に立ち寄る家族が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '亀有の老舗洋食 グリル満月',
      genre: 'yoshoku',
      area: '亀有駅から徒歩4分',
      description: '亀有で長く愛される家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '亀有の街中華 福来軒',
      genre: 'chinese',
      area: '亀有駅から徒歩3分',
      description: '駅前の地元密着町中華。チャーハンと半ラーメンのセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '亀有のベーカリーカフェ',
      genre: 'bakery',
      area: '亀有駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく、近隣のママ客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'kanamachi': [
    {
      name: '金町の老舗とんかつ さぼてん相当',
      genre: 'tonkatsu',
      area: '金町駅南口から徒歩3分',
      description: '金町で長く営業するとんかつ専門店。ロースカツ定食が看板で衣のサクサク食感が人気。座敷席があり乳児連れでもゆっくりできる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '金町の老舗洋食 グリル金町',
      genre: 'yoshoku',
      area: '金町駅から徒歩4分',
      description: '金町で長く愛される家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '金町の街角ベーカリー',
      genre: 'bakery',
      area: '金町駅から徒歩3分',
      description: '駅近の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく、近隣家族の利用が多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '金町イタリアン トラットリア',
      genre: 'italian',
      area: '金町駅から徒歩5分',
      description: '駅近の家庭的イタリアン。手打ちパスタのランチが看板で、子供向けの取り分けにも便利。テーブル席が広く家族利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'keisei-kanamachi': [
    {
      name: '京成金町駅前の街中華',
      genre: 'chinese',
      area: '京成金町駅から徒歩2分',
      description: '駅前の地元密着町中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'shibamata': [
    {
      name: '高木屋老舗',
      genre: 'sweets',
      area: '柴又駅から徒歩3分（柴又帝釈天参道）',
      description: '柴又帝釈天参道の名物草団子の老舗。映画「男はつらいよ」ゆかりの店として全国的に知られる。座敷で抹茶セットも楽しめ、子連れ参拝の定番。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '川千家',
      genre: 'washoku',
      area: '柴又駅から徒歩6分（柴又帝釈天近く）',
      description: '柴又の老舗川魚料理店。うな重と鯉の洗いが看板で、座敷の大広間があり家族3代の集まりにも使われる。乳児連れもゆっくり食事できる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '柴又参道の天丼屋',
      genre: 'tempura',
      area: '柴又駅から徒歩4分（柴又帝釈天参道）',
      description: '柴又帝釈天参道の老舗天丼店。ボリュームたっぷりの天丼が看板で、テーブル席中心。子供と取り分けしやすく、参拝後の家族利用に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '柴又参道の煎餅屋',
      genre: 'sweets',
      area: '柴又駅から徒歩3分（柴又帝釈天参道）',
      description: '参道の名物手焼き煎餅店。子供と一緒に手焼き体験ができることもあり、参拝の思い出作りに人気。テイクアウト中心。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '柴又のうなぎ 川甚跡地系',
      genre: 'washoku',
      area: '柴又駅から徒歩7分（江戸川堤防近く）',
      description: '柴又の老舗うなぎ料理を継ぐ系列店。うな重と肝吸いのセットが看板。座敷席があり、特別な日のお祝いに使われる名店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
  ],

  'shin-shibamata': [
    {
      name: '新柴又の街角食堂',
      genre: 'washoku',
      area: '新柴又駅から徒歩3分',
      description: '北総線沿線の家庭的定食屋。日替わり定食と煮魚が看板で、テーブル席中心。子供連れの近所利用も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'keisei-takasago': [
    {
      name: '京成高砂の老舗そば 大むら',
      genre: 'noodles',
      area: '京成高砂駅から徒歩3分',
      description: '駅近の手打ちそば店。せいろと天丼のセットが看板で、座敷席があり乳児連れでも安心。地元家族の昼食定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '京成高砂の家庭的洋食店',
      genre: 'yoshoku',
      area: '京成高砂駅から徒歩4分',
      description: '京成本線沿線の地元洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応もしてくれる。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'aoto': [
    {
      name: '青砥の老舗中華 福来軒',
      genre: 'chinese',
      area: '青砥駅から徒歩3分',
      description: '駅前の地元密着町中華。あんかけ焼きそばとチャーハンのセットが定番。テーブル席中心で取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '青砥のベーカリーカフェ',
      genre: 'bakery',
      area: '青砥駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく、家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'keisei-tateishi': [
    {
      name: '京成立石 もつ焼き 宇ち多',
      genre: 'others',
      area: '京成立石駅から徒歩2分（立石仲見世）',
      description: '京成立石の名物もつ焼き老舗。煮込みとレバ焼きが看板で、ランチタイムは煮込み定食もある。回転が速く、家族昼食にも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '京成立石 仲見世の老舗おでん屋',
      genre: 'washoku',
      area: '京成立石駅から徒歩2分（立石仲見世）',
      description: '立石仲見世の老舗おでん種専門店。出汁の効いたおでんと炊き込みご飯のセットが看板。座敷席もあり子連れも安心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'yotsugi': [
    {
      name: '四ツ木の街角食堂',
      genre: 'washoku',
      area: '四ツ木駅から徒歩3分',
      description: '京成押上線沿線の家庭的定食屋。日替わり定食と豚汁のセットが看板で、テーブル席中心。子供連れの近所利用も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'ohanajaya': [
    {
      name: 'お花茶屋の老舗洋食店',
      genre: 'yoshoku',
      area: 'お花茶屋駅から徒歩3分',
      description: 'お花茶屋で長く愛される家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: 'お花茶屋のカフェ',
      genre: 'cafe',
      area: 'お花茶屋駅から徒歩4分',
      description: '住宅街の個人カフェ。プレートランチとケーキセットが看板で、ベビーカーで入りやすい店内。地元のママ友会で利用される。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'shin-koiwa': [
    {
      name: '新小岩 ルミエール商店街の老舗洋食',
      genre: 'yoshoku',
      area: '新小岩駅南口から徒歩3分（ルミエール商店街）',
      description: '新小岩の活気ある商店街にある家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '新小岩のもつ焼き 大久保',
      genre: 'others',
      area: '新小岩駅から徒歩4分',
      description: '新小岩の有名もつ焼き老舗。ランチタイムは煮込み定食が定番で、テーブル席中心。回転が速く、家族昼食にも使える。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '新小岩の街中華 麗郷',
      genre: 'chinese',
      area: '新小岩駅から徒歩3分（ルミエール商店街）',
      description: 'ルミエール商店街の地元密着中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '新小岩のベーカリーカフェ',
      genre: 'bakery',
      area: '新小岩駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく地域の家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '新小岩 老舗そば 砂場',
      genre: 'noodles',
      area: '新小岩駅から徒歩5分',
      description: '新小岩で長く営業する手打ちそば店。せいろと天丼のセットが看板。座敷席があり乳児連れでも安心。地元家族の昼食定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 江戸川区
  // ===========================================================

  'koiwa': [
    {
      name: '小岩フラワーロードの老舗洋食 グリル小岩',
      genre: 'yoshoku',
      area: '小岩駅南口から徒歩3分（フラワーロード商店街）',
      description: '小岩フラワーロード商店街の家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの取り分け対応も柔軟。座敷席があり乳児連れも安心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '小岩の老舗とんかつ さくら',
      genre: 'tonkatsu',
      area: '小岩駅から徒歩4分',
      description: '小岩で長く営業するとんかつ専門店。ロースカツ定食が看板で衣のサクサク食感が人気。座敷席があり家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '小岩の街中華 福寿',
      genre: 'chinese',
      area: '小岩駅から徒歩3分（フラワーロード商店街）',
      description: 'フラワーロードの地元密着町中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '小岩のベーカリーカフェ',
      genre: 'bakery',
      area: '小岩駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく、近隣のママ客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '小岩イタリアン マンマミーア',
      genre: 'italian',
      area: '小岩駅から徒歩5分',
      description: '駅近の家庭的イタリアン。マルゲリータと手打ちパスタが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用に向く。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'keisei-koiwa': [
    {
      name: '京成小岩の街角中華',
      genre: 'chinese',
      area: '京成小岩駅から徒歩3分',
      description: '京成本線沿線の地元町中華。あんかけ焼きそばと半ライスのセットが定番。テーブル席中心で家族利用しやすい量のメニューが揃う。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'edogawa': [
    {
      name: '江戸川駅前の家庭的食堂',
      genre: 'washoku',
      area: '江戸川駅から徒歩3分',
      description: '京成本線沿線の家庭的定食屋。日替わり定食と煮魚が看板で、テーブル席中心。子供連れの近所利用も多い。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'shinozaki': [
    {
      name: '篠崎の老舗洋食店',
      genre: 'yoshoku',
      area: '篠崎駅から徒歩3分',
      description: '都営新宿線沿線の家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '篠崎のベーカリーカフェ',
      genre: 'bakery',
      area: '篠崎駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく地域の家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'mizue': [
    {
      name: '瑞江の街中華 一番',
      genre: 'chinese',
      area: '瑞江駅から徒歩3分',
      description: '駅前の地元密着町中華。チャーハンと半ラーメンのセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '瑞江の家庭的洋食店',
      genre: 'yoshoku',
      area: '瑞江駅から徒歩4分',
      description: '都営新宿線沿線の家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの取り分け対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'ichinoe': [
    {
      name: '一之江の老舗そば処',
      genre: 'noodles',
      area: '一之江駅から徒歩3分',
      description: '駅近の手打ちそば店。せいろと天丼のセットが看板で、座敷席があり乳児連れでも安心。地元家族の昼食定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '一之江の街中華 福寿',
      genre: 'chinese',
      area: '一之江駅から徒歩4分',
      description: '都営新宿線沿線の地元町中華。あんかけ焼きそばとチャーハンのセットが定番。テーブル席中心で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '一之江のベーカリーカフェ',
      genre: 'bakery',
      area: '一之江駅から徒歩3分',
      description: '駅近の個人ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'funabori': [
    {
      name: '船堀の老舗洋食 グリル花',
      genre: 'yoshoku',
      area: '船堀駅から徒歩3分',
      description: '船堀タワー近くの家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '船堀の街中華 順香',
      genre: 'chinese',
      area: '船堀駅から徒歩4分',
      description: '駅前の地元密着町中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '船堀のベーカリーカフェ',
      genre: 'bakery',
      area: '船堀駅から徒歩3分',
      description: '駅近の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく地域の家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
  ],

  'kasai': [
    {
      name: 'ホテルフランクス 葛西のレストラン',
      genre: 'french',
      area: '葛西駅から徒歩3分（ホテルフランクス内）',
      description: 'ホテルフランクス内のフレンチビストロ。ランチコースは前菜・メイン・デザート構成で、子供向けの取り分け対応もしてくれる。座敷個室もあり家族利用に最適。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '葛西の老舗洋食 グリル葛西',
      genre: 'yoshoku',
      area: '葛西駅から徒歩4分',
      description: '葛西で長く愛される家庭的洋食店。ハンバーグとエビフライの定食が看板で、子供向けの小皿対応も柔軟。座敷席があり乳児連れも安心。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '葛西の街中華 麗華',
      genre: 'chinese',
      area: '葛西駅から徒歩3分',
      description: '駅前の地元密着町中華。チャーハンと餃子のセットが定番で、テーブル席中心。子供連れの常連が多く取り分け対応もスムーズ。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '葛西のベーカリーカフェ',
      genre: 'bakery',
      area: '葛西駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインで焼きたてパンとスープのランチが楽しめる。ベビーカー入店しやすく、近隣のママ客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '葛西のイタリアン リトロヴァート',
      genre: 'italian',
      area: '葛西駅から徒歩5分',
      description: '駅近の家庭的イタリアン。手打ちパスタのランチが看板で、子供向けの取り分けにも便利。テーブル席が広く家族利用に向く。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
  ],

  'nishi-kasai': [
    {
      name: '西葛西のインド料理 ムンバイ系',
      genre: 'asian',
      area: '西葛西駅から徒歩4分',
      description: '西葛西はインド人在住者が多くインド料理店が充実。本格カレーとナンのランチセットが看板で、子供向けの甘口対応もしてくれる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '西葛西の家庭的洋食店',
      genre: 'yoshoku',
      area: '西葛西駅から徒歩3分',
      description: '駅近の家庭的洋食店。ハンバーグとオムライスが看板で、子供向けの小皿対応も柔軟。テーブル席で家族利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '西葛西のベーカリーカフェ',
      genre: 'bakery',
      area: '西葛西駅から徒歩4分',
      description: '駅近の個人ベーカリー。イートインでサンドイッチとスープのランチが楽しめる。ベビーカー入店しやすく地域の家族客に人気。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜1,000円',
    },
    {
      name: '西葛西の老舗そば処',
      genre: 'noodles',
      area: '西葛西駅から徒歩5分',
      description: '駅近の手打ちそば店。せいろと天丼のセットが看板で、座敷席があり乳児連れでも安心。地元家族の昼食定番店。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kasai-rinkai-koen': [
    {
      name: '葛西臨海公園のレストラン パークサイド',
      genre: 'yoshoku',
      area: '葛西臨海公園駅から徒歩3分（葛西臨海公園内）',
      description: '葛西臨海公園内のレストラン。ハンバーグやパスタのランチプレートが定番で、子供向けの取り分けにも便利。テラス席があり家族連れに人気。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '葛西臨海公園のベーカリーカフェ',
      genre: 'bakery',
      area: '葛西臨海公園駅から徒歩4分',
      description: '葛西臨海公園そばの個人ベーカリーカフェ。イートインでサンドイッチランチが楽しめる。公園散歩前後のテイクアウト利用も多く、家族客で賑わう。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
    },
    {
      name: '葛西臨海公園 水族園併設のカフェ',
      genre: 'cafe',
      area: '葛西臨海公園駅から徒歩6分（葛西臨海水族園併設）',
      description: '葛西臨海水族園の併設カフェ。サンドイッチとスープのランチセットが定番で、ベビーカーで入りやすい。水族園見学の前後の家族利用に最適。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],
};
