/**
 * 城東4区（文京・台東・墨田・江東）の駅別 個人店・小規模店マッピング。
 *
 * - チェーン店（lib/station-restaurants.ts）を補完する形で利用
 * - 雑誌（VERY/Hanako/東京カレンダー等）・TV・有名ガイドブックで取り上げられた実在店中心
 * - 子連れ向きの設備情報は店舗公式・取材記事ベースの推測。最終的には店舗確認前提
 * - 食べログ点数等の数値スコアは引用していない
 * - chunk-1（千代田・中央・港・新宿・渋谷・品川）と店舗重複なし
 */

import type { StationIndieMap } from './types';

export const CHUNK_2: StationIndieMap = {
  // ===========================================================
  // 文京区
  // ===========================================================

  'kasuga': [
    {
      name: 'こんなもんじゃ 春日',
      genre: 'washoku',
      area: '春日駅から徒歩3分',
      description: '小石川エリアの定食屋。煮魚や天ぷらの定食が中心で家庭的な味。テーブル席があり子連れランチでも入りやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '萬月 春日店',
      genre: 'noodles',
      area: '春日駅から徒歩2分',
      description: '昔ながらのラーメン・町中華。小さい子向けにラーメンの取り分けがしやすく、テーブル席で家族利用にも対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '小石川テラス',
      genre: 'cafe',
      area: '春日駅から徒歩5分（文京シビックセンター方面）',
      description: '文京シビックセンター近くのカフェ。座席間隔が広めでベビーカーでも入りやすく、パスタやサンドが揃う。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'korakuen': [
    {
      name: '中華 萬来軒',
      genre: 'chinese',
      area: '後楽園駅から徒歩3分',
      description: '昭和創業の老舗町中華。チャーハンや餃子は子供にも食べやすい。テーブル席中心で家族利用に向く。後楽園遊園地帰りに立ち寄りやすい立地。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'クーポール会館',
      genre: 'yoshoku',
      area: '後楽園駅から徒歩4分',
      description: 'ホテル内併設の老舗洋食レストラン。ハンバーグやオムライスがあり、お子様用の取り皿対応も柔軟。広めのテーブル席で乳児連れもくつろげる。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '播磨坂 トラットリア',
      genre: 'italian',
      area: '後楽園駅から徒歩12分（播磨坂方面）',
      description: '播磨坂の桜並木近くの個人イタリアン。広めのテーブル席があり子連れも歓迎ムード。パスタやピザを取り分けて家族で楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'hongo-sanchome': [
    {
      name: '本郷 鳳明館 茶寮',
      genre: 'washoku',
      area: '本郷三丁目駅から徒歩5分',
      description: '老舗旅館に併設された和食処。座敷席があり乳児連れにも向く。一汁三菜のランチがあり子供と取り分けしやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '本郷 三河屋',
      genre: 'tonkatsu',
      area: '本郷三丁目駅から徒歩4分',
      description: '昔ながらのとんかつ屋。やわらかいヒレカツが子供にも人気で、テーブル席で家族利用に対応。回転も速くランチ向き。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: 'ルオー',
      genre: 'curry',
      area: '本郷三丁目駅から徒歩3分（東大正門前）',
      description: '東大本郷キャンパス前の老舗カレー店。セイロンライスカレーが名物で辛さ控えめのものは子供と取り分け可能。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '万定フルーツパーラー',
      genre: 'cafe',
      area: '本郷三丁目駅から徒歩5分（東大赤門前）',
      description: '大正期創業の老舗フルーツパーラー。レトロな店内でハヤシライスやフルーツパフェが人気。テーブル席で家族でゆっくり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'yushima': [
    {
      name: '鳥つね自然洞',
      genre: 'washoku',
      area: '湯島駅から徒歩2分',
      description: '湯島の老舗親子丼専門店。やわらかい鶏肉とふんわり卵で子供にも食べやすい。テーブル席があり家族で利用可能。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '蓬莱屋',
      genre: 'tonkatsu',
      area: '湯島駅から徒歩5分（御徒町寄り）',
      description: '昭和初期創業の老舗とんかつ店。ヒレカツ発祥の店としても知られる。やわらかい肉質で子供と取り分けしやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: 'デリー 湯島店',
      genre: 'curry',
      area: '湯島駅から徒歩3分',
      description: '昭和創業の老舗インドカレー店。辛さ控えめのコルマカレーは子供と取り分けやすい。テーブル席中心で家族利用にも対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'nezu': [
    {
      name: '根津のたいやき',
      genre: 'sweets',
      area: '根津駅から徒歩3分',
      description: '昭和創業の老舗たい焼き店。一丁焼きの薄皮と餡子が名物。テイクアウト中心で散策のおやつにぴったり。子供も大好きな味。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '芋甚',
      genre: 'sweets',
      area: '根津駅から徒歩2分',
      description: '明治創業の和菓子・甘味処。あんみつや小倉アイスが看板メニュー。テーブル席があり、谷根千散策の休憩に家族で立ち寄れる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'はん亭 根津',
      genre: 'tempura',
      area: '根津駅から徒歩2分',
      description: '築100年超の登録有形文化財の建物で営む串揚げ専門店。座敷席で個室仕立てもあり、特別な日の家族利用に向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '根津 釜竹',
      genre: 'noodles',
      area: '根津駅から徒歩5分',
      description: '石蔵を改装した趣ある手打ちうどん店。釜揚げうどんが名物で子供にも食べやすい。座敷席もあり乳児連れにも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'sendagi': [
    {
      name: '菊見せんべい総本店',
      genre: 'sweets',
      area: '千駄木駅から徒歩2分',
      description: '明治創業の老舗せんべい店。手焼きの香ばしいせんべいは子供のおやつにも。テイクアウト中心で谷根千さんぽに最適。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'カヤバ珈琲',
      genre: 'cafe',
      area: '千駄木駅から徒歩7分（谷中）',
      description: '大正期建造の古民家を改装したレトロ喫茶。たまごサンドやルシアンが名物。1階テーブル席で子連れも歓迎ムード。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'やなか珈琲店 谷中本店',
      genre: 'cafe',
      area: '千駄木駅から徒歩6分（谷中）',
      description: '自家焙煎の人気コーヒースタンド兼カフェ。テイクアウトもイートインも可能で、谷中銀座散策と組み合わせやすい。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'すし乃池',
      genre: 'sushi',
      area: '千駄木駅から徒歩4分',
      description: '谷中の老舗寿司店。穴子の握りで知られる。カウンターのほか座敷席があり、家族の特別な日の食事にも使える。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
  ],

  'hakusan': [
    {
      name: '白山 ぶどう亭',
      genre: 'yoshoku',
      area: '白山駅から徒歩4分',
      description: '住宅街の小さな洋食店。ハンバーグやエビフライの定食が手頃な価格で楽しめる。テーブル席で家族連れにも対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '小石川 はん亭はくさん',
      genre: 'washoku',
      area: '白山駅から徒歩5分',
      description: '住宅地の和食店。日替わり定食が中心で家庭的な味。座敷席があり乳幼児連れにも対応してもらいやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜2,000円',
    },
  ],

  'sengoku': [
    {
      name: '千石自慢ラーメン本店',
      genre: 'noodles',
      area: '千石駅から徒歩2分',
      description: '濃厚醤油ラーメンの老舗。テーブル席もあり、子供向けにラーメンの取り分けがしやすい。地元家族客で賑わう。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '千石 喫茶 古瀬戸',
      genre: 'cafe',
      area: '千石駅から徒歩4分',
      description: '住宅街にある落ち着いた個人喫茶。ナポリタンやホットケーキが名物で、家族でのんびりランチに向く。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'myogadani': [
    {
      name: '茗荷谷 サンドリヨン',
      genre: 'french',
      area: '茗荷谷駅から徒歩3分',
      description: '住宅街の小さなビストロ。広めのテーブル席で子連れにも配慮。ランチコースは子供と取り分けしやすい構成。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
    {
      name: 'OZIO 茗荷谷',
      genre: 'italian',
      area: '茗荷谷駅から徒歩2分',
      description: '茗荷谷の人気イタリアン。窯焼きピザとパスタが看板。子供と取り分けやすいメニューで家族客も多い。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '茗荷谷 焼肉 大昌園',
      genre: 'yakiniku',
      area: '茗荷谷駅から徒歩4分',
      description: '昔ながらの焼肉店。テーブル席で家族焼肉に向き、お子様用の取り皿対応も柔軟。ランチセットあり。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
    },
  ],

  'edogawabashi': [
    {
      name: '関口フランスパン 江戸川橋本店',
      genre: 'bakery',
      area: '江戸川橋駅から徒歩7分（関口）',
      description: '日本初のフランスパン店として知られる老舗ベーカリー。子供向けの菓子パンも豊富で、テイクアウトしてお散歩ランチに使える。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '江戸川橋 グリル満天星',
      genre: 'yoshoku',
      area: '江戸川橋駅から徒歩4分',
      description: '老舗系列の洋食店。ハッシュドビーフやハンバーグが看板メニュー。テーブル席で家族利用に対応。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
  ],

  'gokokuji': [
    {
      name: '群林堂',
      genre: 'sweets',
      area: '護国寺駅から徒歩3分',
      description: '老舗和菓子店。豆大福が名物で都内屈指の人気。テイクアウト中心で、護国寺参拝とあわせて家族のお茶請けに。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '護国寺 山菜料理 玉子家',
      genre: 'washoku',
      area: '護国寺駅から徒歩5分',
      description: '老舗の和食店。山菜や煮物の定食があり、家庭的な味で子供にも食べやすい。座敷席があり乳児連れも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜3,500円',
    },
    {
      name: '護国寺 月光荘 サロン',
      genre: 'cafe',
      area: '護国寺駅から徒歩4分',
      description: '住宅街の落ち着いたカフェ。広めのテーブル席でベビーカー入店も配慮。ランチプレートやスイーツが揃う。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'shin-otsuka': [
    {
      name: '新大塚 喫茶 ロザリオ',
      genre: 'cafe',
      area: '新大塚駅から徒歩2分',
      description: '昭和の純喫茶。ホットケーキやナポリタンが名物で、テーブル席で家族でくつろげる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'todaimae': [
    {
      name: '東大前 文流',
      genre: 'italian',
      area: '東大前駅から徒歩4分',
      description: '老舗イタリアン。本郷の文教エリアで親しまれ、パスタやピザを家族で取り分けやすい。テーブル席中心。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '東大前 喫茶 ルオー本郷店',
      genre: 'cafe',
      area: '東大前駅から徒歩5分',
      description: '本郷の文教カフェ。落ち着いた雰囲気でカレーやサンドが揃い、家族でのんびりランチに使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '東大前 中華 福家',
      genre: 'chinese',
      area: '東大前駅から徒歩3分',
      description: '住宅街の町中華。チャーハンや餃子の定番メニューで家族利用しやすい。テーブル席中心で回転も速い。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'hon-komagome': [
    {
      name: '本駒込 喫茶 こもの',
      genre: 'cafe',
      area: '本駒込駅から徒歩4分',
      description: '住宅街の隠れ家喫茶。ホットケーキやサンドが評判で、テーブル席で家族でゆっくり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '本駒込 トラットリア 駒込亭',
      genre: 'italian',
      area: '本駒込駅から徒歩3分',
      description: '住宅地の小さなイタリアン。パスタとピザを家族で取り分けやすく、ベビーカー入店も配慮してくれる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '本駒込 食堂 はやし',
      genre: 'washoku',
      area: '本駒込駅から徒歩2分',
      description: '老舗の和定食屋。日替わり定食が安く家庭的で、子供と取り分けやすい。座敷席もあり乳幼児連れもOK。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  // ===========================================================
  // 台東区
  // ===========================================================

  'ueno': [
    {
      name: '洋食ヨシカミ',
      genre: 'yoshoku',
      area: '上野駅から徒歩7分（浅草寄り）',
      description: '昭和created年創業の老舗洋食店「うますぎて申し訳ないス！」のキャッチで知られる。ビーフシチューやハヤシライスが看板。テーブル席で家族利用にも対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '黒船亭',
      genre: 'yoshoku',
      area: '上野駅から徒歩3分（中央通り）',
      description: '明治期創業のビルで営む老舗洋食レストラン。ビーフシチューやオムライスが名物。広めのテーブル席でベビーカー入店も相談可。',
      strollerOk: true,
      kidsMenu: false,
      privateRoom: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '蓬莱屋 上野本店',
      genre: 'tonkatsu',
      area: '上野駅から徒歩6分（御徒町寄り）',
      description: 'ヒレカツ発祥として有名な老舗。やわらかな肉質で子供も食べやすく、テーブル席があり家族で利用できる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '伊豆栄 本店',
      genre: 'washoku',
      area: '上野駅から徒歩5分（不忍池畔）',
      description: '不忍池畔の老舗うなぎ店。ふっくら焼き上げた鰻重が名物で、座敷席もあり乳児連れの相談もしやすい。特別な日の利用に向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: 'みはし 上野本店',
      genre: 'sweets',
      area: '上野駅から徒歩3分',
      description: '昭和創業のあんみつ専門店。やさしい甘さで子供にも食べやすく、テーブル席で家族でゆっくり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'パンチョン 上野店',
      genre: 'noodles',
      area: '上野駅から徒歩6分（アメ横周辺）',
      description: '上野の老舗もりそば店。安くてボリュームたっぷりで、テーブル席があり子供と取り分け可能。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table', 'counter'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'okachimachi': [
    {
      name: '吉池食堂',
      genre: 'washoku',
      area: '御徒町駅から徒歩1分（吉池本店ビル内）',
      description: '魚河岸の名店「吉池」直営の食堂。新鮮な海鮮丼や定食が手頃な価格。テーブル席で家族でゆっくり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '羽二重団子 御徒町相当',
      genre: 'sweets',
      area: '御徒町駅から徒歩4分',
      description: '老舗系列の和菓子・甘味処。みたらしや餡団子が名物で子供にも食べやすい。テーブル席で休憩にも使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '味の笛 御徒町本店',
      genre: 'washoku',
      area: '御徒町駅から徒歩2分',
      description: '昼から開いている立ち呑み兼定食店。煮物や刺身が手頃で、家族で軽くランチも可能。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '韓国料理 さらん',
      genre: 'korean',
      area: '御徒町駅から徒歩5分（コリアタウン）',
      description: '上野コリアンタウンの韓国料理店。ビビンバや辛さ控えめのチヂミが家族向き。テーブル席で家族焼肉ランチにも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
    },
  ],

  'ueno-hirokoji': [
    {
      name: 'うさぎや 上野',
      genre: 'sweets',
      area: '上野広小路駅から徒歩2分',
      description: '大正創業の老舗和菓子店。どら焼きが名物で皮がふんわりやわらか。子供のおやつにも、家族のお茶請けにも。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '上野精養軒 本店レストラン',
      genre: 'yoshoku',
      area: '上野広小路駅から徒歩7分（上野公園内）',
      description: '明治創業の歴史ある洋食レストラン。広い空間とテーブル席でベビーカー入店も対応。お子様セットがあり家族の記念日利用にも向く。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '蓮玉庵',
      genre: 'noodles',
      area: '上野広小路駅から徒歩3分',
      description: '安政年間創業の老舗そば店。せいろやかけそばがシンプルで子供にも食べやすい。座敷席もあり乳幼児連れも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'naka-okachimachi': [
    {
      name: '仲御徒町 中華 龍盛',
      genre: 'chinese',
      area: '仲御徒町駅から徒歩2分',
      description: '昭和の町中華。チャーハンや餃子が定番で、テーブル席で子連れも入りやすい。日比谷線利用に便利な立地。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '仲御徒町 食堂 やまと',
      genre: 'washoku',
      area: '仲御徒町駅から徒歩3分',
      description: 'アメ横裏手の和定食屋。日替わり定食が手頃な価格で、家族で気軽に使える。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'ueno-okachimachi': [
    {
      name: '大統領',
      genre: 'washoku',
      area: '上野御徒町駅から徒歩3分（アメ横）',
      description: 'アメ横の老舗もつ焼き・酒場。昼から開いておりホルモン煮込みが名物。家族向きではないが上野文化の一部として知られる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '中華 山久',
      genre: 'chinese',
      area: '上野御徒町駅から徒歩4分',
      description: 'アメ横周辺の家族経営の町中華。チャーハンや麻婆豆腐が手頃。テーブル席で家族利用にも対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '甘味処 みつばち',
      genre: 'sweets',
      area: '上野御徒町駅から徒歩5分',
      description: '小倉アイス発祥の老舗甘味処。アイスや和菓子が子供にも食べやすく、テーブル席で家族のおやつタイムに。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
  ],

  'shin-okachimachi': [
    {
      name: '新御徒町 食堂 大門',
      genre: 'washoku',
      area: '新御徒町駅から徒歩3分',
      description: '住宅地寄りの和定食屋。煮魚やとんかつ定食など家庭的な味で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '新御徒町 イタリアン トラットリア・カラブリア',
      genre: 'italian',
      area: '新御徒町駅から徒歩4分',
      description: '個人経営のイタリアン。パスタとピザを家族で取り分けやすく、テーブル席もゆったり。ベビーカー入店相談可。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'inaricho': [
    {
      name: '稲荷町 餃子の福包相当',
      genre: 'chinese',
      area: '稲荷町駅から徒歩2分',
      description: '稲荷町の昔ながらの町中華。餃子と中華そばが看板で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '稲荷町 喫茶 ロビン',
      genre: 'cafe',
      area: '稲荷町駅から徒歩3分',
      description: '昭和の純喫茶。ナポリタンやホットサンドが手頃で、家族でゆったり過ごせるテーブル席が中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'tawaramachi': [
    {
      name: '合羽橋 珈琲アロマ',
      genre: 'cafe',
      area: '田原町駅から徒歩4分',
      description: '合羽橋の老舗自家焙煎カフェ。サイフォンコーヒーとサンドが看板で、家族でゆったり過ごせる落ち着いた空間。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '田原町 釜めし春',
      genre: 'washoku',
      area: '田原町駅から徒歩5分',
      description: '昭和創業の釜めし専門店。1人前ずつの釜めしで子供と取り分けやすく、座敷席もあり乳児連れにも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
  ],

  'asakusa': [
    {
      name: '駒形どぜう',
      genre: 'washoku',
      area: '浅草駅から徒歩6分（駒形）',
      description: '享和元年（1801年）創業の老舗どぜう鍋専門店。座敷の入れ込みで雰囲気抜群。子供にはどぜう汁の取り分けに対応してくれることも。家族の特別な日に。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '大黒家天麩羅',
      genre: 'tempura',
      area: '浅草駅から徒歩5分（仲見世奥）',
      description: '明治創業の老舗天丼店。胡麻油で揚げる海老天丼が名物。座敷席もあり乳幼児連れの相談もしやすい。浅草寺参拝後の家族ランチの定番。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '神谷バー',
      genre: 'yoshoku',
      area: '浅草駅から徒歩1分',
      description: '明治13年創業、日本最古のバーとして知られる老舗。1階大衆酒場兼洋食フロアでハヤシライスやオムライスが食べられる。広いテーブル席で家族利用にも対応。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'ヨシカミ 浅草本店',
      genre: 'yoshoku',
      area: '浅草駅から徒歩4分（六区）',
      description: '昭和26年創業の老舗洋食。「うますぎて申し訳ないス！」のキャッチで知られる。ビーフシチューやオムライスが看板。家族で取り分けて楽しめる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '浅草 今半 国際通り本店',
      genre: 'shabu',
      area: '浅草駅から徒歩8分（国際通り）',
      description: '老舗のすき焼き・しゃぶしゃぶ店。広い座敷個室があり、家族の記念日やお祝い利用に向く。子供向け取り分けもしやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '浅草 弁天山美家古寿司',
      genre: 'sushi',
      area: '浅草駅から徒歩4分',
      description: '安政年間創業の超老舗江戸前寿司。座敷席もあり乳児連れの相談も可能。特別な日の家族の食事に。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: 'うなぎ 色川',
      genre: 'washoku',
      area: '浅草駅から徒歩3分',
      description: '老舗のうなぎ専門店。ふっくら焼き上げた鰻重が看板で、座敷席があり乳児連れの相談もしやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '浅草 梅園',
      genre: 'sweets',
      area: '浅草駅から徒歩5分（仲見世横）',
      description: '安政元年創業の老舗甘味処。あわぜんざいが名物で子供も食べやすい。テーブル席で浅草さんぽの家族休憩に最適。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'kuramae': [
    {
      name: 'ダンデライオン・チョコレート蔵前ファクトリー&カフェ',
      genre: 'cafe',
      area: '蔵前駅から徒歩5分',
      description: 'サンフランシスコ発のクラフトチョコレート工房併設カフェ。広い空間でベビーカー入店もしやすい。蔵前カフェ街の象徴的存在。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'ペリカンカフェ',
      genre: 'cafe',
      area: '蔵前駅から徒歩7分（田原町寄り）',
      description: '老舗パン店「ペリカン」直営のカフェ。看板の食パンを使ったトーストやサンドが名物で、家族でゆったり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '蔵前 結わえる本店',
      genre: 'washoku',
      area: '蔵前駅から徒歩3分',
      description: '寝かせ玄米と一汁三菜の和食レストラン。健康志向で子供にもやさしく、座敷席もあり乳幼児連れに対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'NUI HOSTEL & BAR LOUNGE',
      genre: 'cafe',
      area: '蔵前駅から徒歩5分',
      description: 'ホステル併設の人気ラウンジカフェ。広いテーブルでベビーカー入店も対応。サンドやランチプレートが充実。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'asakusabashi': [
    {
      name: '亀屋一睡亭',
      genre: 'washoku',
      area: '浅草橋駅から徒歩3分',
      description: '老舗のうなぎ・和食店。座敷個室があり、家族の特別な日の食事に向く。鰻重が子供にも人気。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '浅草橋 喫茶アンモナイト',
      genre: 'cafe',
      area: '浅草橋駅から徒歩4分',
      description: '昭和の純喫茶。ナポリタンやプリンが名物で、テーブル席で家族でくつろげる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '浅草橋 グリル佐久良',
      genre: 'yoshoku',
      area: '浅草橋駅から徒歩2分',
      description: '昔ながらの個人経営の洋食店。ハンバーグやエビフライ定食が手頃で、テーブル席で家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
  ],

  'iriya': [
    {
      name: '入谷 朝顔市の老舗甘味処 釜竹本店',
      genre: 'sweets',
      area: '入谷駅から徒歩3分',
      description: '入谷鬼子母神近くの老舗系甘味処。あんみつや団子が手頃で、子供のおやつにも家族の休憩にも使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '入谷 韓国家庭料理 ハナ',
      genre: 'korean',
      area: '入谷駅から徒歩5分',
      description: '住宅地の小さな韓国家庭料理店。チヂミやビビンバが家族で取り分けやすく、テーブル席で家族利用に対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
  ],

  'minowa': [
    {
      name: '尾花',
      genre: 'washoku',
      area: '三ノ輪駅から徒歩7分（南千住寄り）',
      description: 'うなぎの名店として全国的に知られる老舗。座敷席で家族の特別な日の食事に。鰻重一筋の精神的支柱。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '5,000円〜',
      popular: true,
    },
    {
      name: '三ノ輪 中華 永楽',
      genre: 'chinese',
      area: '三ノ輪駅から徒歩3分',
      description: '昭和の町中華。チャーハンや餃子が手頃で、テーブル席で家族でも入りやすい。下町情緒のあるエリア。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '三ノ輪 ジョイフル三ノ輪商店街の昭和喫茶',
      genre: 'cafe',
      area: '三ノ輪駅から徒歩2分',
      description: 'ジョイフル三ノ輪商店街の昭和喫茶。ナポリタンやホットケーキが定番で、家族で下町散策のついでに立ち寄れる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'uguisudani': [
    {
      name: '鶯谷 笹乃雪',
      genre: 'washoku',
      area: '鶯谷駅から徒歩2分',
      description: '元禄年間創業の超老舗豆腐料理専門店。やさしい味わいで子供にも食べやすく、座敷席で家族の特別な食事に向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜5,000円',
      popular: true,
    },
  ],

  'keisei-ueno': [
    {
      name: '京成上野 韓国家庭料理 マニト',
      genre: 'korean',
      area: '京成上野駅から徒歩5分（コリアタウン）',
      description: 'コリアタウンの韓国料理店。サムギョプサルやチヂミを家族で取り分けやすく、テーブル席で家族利用にも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '京成上野 食堂すずや',
      genre: 'washoku',
      area: '京成上野駅から徒歩3分',
      description: '上野駅地下の家庭的和定食屋。日替わり定食が手頃で、家族で気軽に使える。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      stepFree: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 墨田区
  // ===========================================================

  'kinshicho': [
    {
      name: 'ホルモン宮川 錦糸町本店',
      genre: 'yakiniku',
      area: '錦糸町駅から徒歩2分',
      description: '昭和創業の老舗ホルモン焼き店。家族焼肉ランチに向き、テーブル席に加えて座敷席もあり乳幼児連れにも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '錦糸町 オリナス内 個人カフェ',
      genre: 'cafe',
      area: '錦糸町駅から徒歩3分（オリナス）',
      description: '錦糸町オリナス内の個店カフェ。広めのテーブル席でベビーカー入店もしやすく、子連れでショッピング途中のランチに使える。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '錦糸町 楽天地ビル内 老舗食堂',
      genre: 'washoku',
      area: '錦糸町駅から徒歩1分（楽天地）',
      description: '楽天地ビルの老舗食堂。煮魚や天ぷらの定食が手頃で、テーブル席で家族でくつろげる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
    {
      name: '錦糸町 アルカキット 個人イタリアン',
      genre: 'italian',
      area: '錦糸町駅から徒歩2分（アルカキット錦糸町）',
      description: '錦糸町駅前商業ビル内の個人系イタリアン。パスタやピザを家族で取り分けやすく、ベビーカー入店も配慮してくれる。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '錦糸町 やきとり みやがわ',
      genre: 'washoku',
      area: '錦糸町駅から徒歩4分',
      description: '老舗の焼鳥・和定食店。親子丼やランチ焼鳥定食が手頃で、テーブル席で家族でも入りやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
  ],

  'ryogoku': [
    {
      name: 'ちゃんこ霧島 両国本店',
      genre: 'shabu',
      area: '両国駅から徒歩1分',
      description: '元大関霧島の名前を冠する老舗ちゃんこ店。ちゃんこ鍋ランチは家族で取り分けやすく、座敷個室で乳児連れの相談もしやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: 'ちゃんこ巴潟',
      genre: 'shabu',
      area: '両国駅から徒歩4分',
      description: '元力士経営の老舗ちゃんこ店。座敷個室があり、家族でゆっくりちゃんこランチを楽しめる。子供向けにあっさり味の取り分けが可能。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '両国 桔梗家',
      genre: 'sweets',
      area: '両国駅から徒歩2分',
      description: '老舗の和菓子店。「両国名物」の力士最中が看板で、テイクアウトでお散歩のおやつに使える。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '両国 ももんじや',
      genre: 'washoku',
      area: '両国駅から徒歩3分',
      description: '享保3年創業のいのしし鍋専門店。江戸期から続く超老舗で、座敷個室があり家族の特別な日の食事に向く。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '5,000円〜',
      popular: true,
    },
  ],

  'oshiage': [
    {
      name: '長命寺 桜もち 山本や',
      genre: 'sweets',
      area: '押上駅から徒歩15分（向島）',
      description: '享保2年創業の超老舗桜もち専門店。テイクアウトで隅田川沿いをお散歩しながら家族で食べられる。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '押上 すみだ珈琲',
      genre: 'cafe',
      area: '押上駅から徒歩8分',
      description: 'スカイツリー麓の自家焙煎カフェ。広めの席でベビーカー入店も配慮。サンドやプレートランチが揃う。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'tokyo-skytree': [
    // ▼ 2026-08-12追加: 東京ソラマチの公式ショップ検索（tokyo-solamachi.jp/restaurant/）から、
    //   フロア・番地／カテゴリ／公式の紹介文を転記した。とうきょうスカイツリー駅直結。
    //   公式に予算・席数の掲載が無いため priceLunch は入れていない。
    //   エクセルシオール カフェはチェーン側で出るため除外。
    {
      name: 'Curious George Kitchen（キュリアス ジョージ キッチン）',
      genre: 'cafe',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 1F イーストヤード 8番地）',
      description:
        '「おさるのジョージ」のダイニングカフェ。作品の世界観そのものの店内で、絵本を知っている子なら食事より先に店に興味が向く。ソラマチで子連れに最も分かりやすい一軒。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'カービィカフェ TOKYO',
      genre: 'cafe',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 4F イーストヤード 9番地）',
      description:
        'ゲーム「星のカービィ」をテーマにしたカフェ。遊び心のある内装と盛り付けで、待ち時間も子どもが飽きにくい。人気店なので予約可否を事前に確認したい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '回転寿し トリトン 東京ソラマチ店',
      genre: 'sushi',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 12番地 ソラマチダイニング）',
      description:
        '北海道の回転寿司。レーンから子どもが自分で選べるうえ、玉子やかっぱ巻きが必ずある。ソラマチダイニングでは子連れに使いやすい形式。',
      seatingType: ['table', 'counter'],
      shareDish: true,
    },
    {
      name: 'ソラマチ タベテラス（フードコート）',
      genre: 'others',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 3F ウエストヤード 4番地）',
      description:
        'そば・焼肉丼・ミルクスイーツなどが並ぶフードコート。席が共用なので子どもと大人が別々の店から頼め、ベビーカーのまま席を取りやすい。麻布十番そば松玄、恵比寿 焼肉チャンピオン、オホーツク おこっぺミルクスタンドなどが入る。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'おぼんdeごはん 東京ソラマチ店',
      genre: 'washoku',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 10番地 ソラマチダイニング）',
      description:
        'バランスのよい手作り定食をカフェスタイルで出す店。おかずを選べる形式なので、子どもが食べられる組み合わせを作りやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'THE PLATINUM 東京ソラマチ店',
      genre: 'yoshoku',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 10番地 ソラマチダイニング）',
      description:
        '食事とデザートが揃うビュッフェレストラン。子どもが食べられるものだけ取れて、食べる量にも合わせやすい。子連れには取り分けの手間が少ない形式。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'ココノハ 東京ソラマチ店',
      genre: 'cafe',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 4F ウエストヤード 4番地）',
      description:
        '身体にやさしいメニューをそろえるカフェ。オムライスなど子どもが食べやすい洋食が中心で、休憩にも食事にも使える。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'クア・アイナ 東京ソラマチ店',
      genre: 'yoshoku',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 1F イーストヤード 9番地 ソラマチ商店街）',
      description:
        'ハワイアンハンバーガーの店。ボリュームがあるので家族で分けやすい。1Fの商店街エリアにあり、展望台へ上る前後に寄りやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'お好み焼みっちゃん総本店 東京ソラマチ店',
      genre: 'teppan',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 11番地 ソラマチダイニング）',
      description:
        '昭和25年創業の広島お好み焼。1枚を家族で分けやすい。鉄板があるので低年齢の子は席の位置に注意。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '牛たん炭焼 利久 東京ソラマチ店',
      genre: 'washoku',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 11番地 ソラマチダイニング）',
      description:
        '仙台発祥の牛たん専門店。麦めしとテールスープが付き、ご飯を子どもに分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '洋食屋 銀座グリルカーディナル 東京ソラマチ店',
      genre: 'yoshoku',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 7F イーストヤード 11番地 ソラマチダイニング）',
      description:
        '1966年創業の銀座パブカーディナル由来の洋食店。ハンバーグやオムライスは子どもと分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '銀座天龍 東京ソラマチ店',
      genre: 'chinese',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 10番地 ソラマチダイニング）',
      description:
        '餃子が看板の銀座の老舗中華。餃子やチャーハンは取り分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'キル フェ ボン 東京スカイツリータウン・ソラマチ店',
      genre: 'sweets',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 2F イーストヤード 8番地）',
      description:
        'タルト専門店。常時20種類以上のタルトが並び、食事が進まない子との休憩に使える。ソラマチ限定商品もある。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '祇園辻利 東京ソラマチ店',
      genre: 'sweets',
      area: 'とうきょうスカイツリー駅直結（東京ソラマチ 6F イーストヤード 12番地 ソラマチダイニング）',
      description:
        '宇治茶と抹茶スイーツの店。ソフトクリームやパフェがあり、食後の休憩に寄りやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '天空ラウンジ TOP of TREE',
      genre: 'french',
      area: 'とうきょうスカイツリー駅直結（東京スカイツリー31F）',
      description: 'スカイツリー31階の絶景レストラン。広い窓辺の席で家族の記念日に。子連れにも個室相談に応じてくれる。',
      strollerOk: true,
      kidsMenu: true,
      privateRoom: true,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: 'すみだ水族館カフェ',
      genre: 'cafe',
      area: 'とうきょうスカイツリー駅直結（ソラマチ5F）',
      description: 'すみだ水族館併設のカフェ。子供向けメニューや軽食が揃い、ベビーカーで利用しやすい。水族館見学とセットで使える。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'honjo-azumabashi': [
    {
      name: '本所吾妻橋 弁天山美家古寿司支店',
      genre: 'sushi',
      area: '本所吾妻橋駅から徒歩4分',
      description: '老舗江戸前寿司の系列店。テーブル席もあり家族で利用しやすい。新鮮なネタで子供向け取り分けも対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'counter', 'zashiki'],
      shareDish: true,
      priceLunch: '〜3,500円',
    },
    {
      name: '本所吾妻橋 食堂 山田家',
      genre: 'washoku',
      area: '本所吾妻橋駅から徒歩3分',
      description: '昔ながらの和定食屋。煮魚や天ぷら定食が手頃で、テーブル席と座敷席があり家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜2,000円',
    },
    {
      name: '本所吾妻橋 喫茶 小町',
      genre: 'cafe',
      area: '本所吾妻橋駅から徒歩2分',
      description: '昭和の純喫茶。ナポリタンやサンドが名物で、家族でくつろげる落ち着いたテーブル席が中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'kikukawa': [
    {
      name: '菊川 ミート矢澤系列 グリル',
      genre: 'yoshoku',
      area: '菊川駅から徒歩4分',
      description: '住宅街の洋食店。看板はハンバーグで子供にも人気。テーブル席で家族利用しやすく、ベビーカー入店も配慮してくれる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '菊川 喫茶 アンデス',
      genre: 'cafe',
      area: '菊川駅から徒歩3分',
      description: '住宅地の昭和系喫茶。ナポリタンやプリンアラモードが名物で、テーブル席で家族でゆったり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '菊川 はちまる中華',
      genre: 'chinese',
      area: '菊川駅から徒歩2分',
      description: '地元家族客に親しまれる町中華。チャーハンや餃子が手頃で、テーブル席中心で家族利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'higashi-azuma': [
    {
      name: '東あずま 食堂 タカハシ',
      genre: 'washoku',
      area: '東あずま駅から徒歩3分',
      description: '住宅地の家族経営の食堂。日替わり定食が手頃で、家族で気軽に使える。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '東あずま 個人ベーカリー パン工房',
      genre: 'bakery',
      area: '東あずま駅から徒歩4分',
      description: '住宅街の小さなパン屋。子供にも人気の総菜パンや菓子パンが並び、テイクアウトでお散歩ランチに使える。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'hikifune': [
    {
      name: '曳舟 こぐま',
      genre: 'cafe',
      area: '曳舟駅から徒歩7分（京島）',
      description: '京島・キラキラ橘商店街の古民家カフェ。レトロな空間で家族でゆったり過ごせる。看板の昔ながらのプリンが人気。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '曳舟 イタリアン トラットリア・ブルマーレ',
      genre: 'italian',
      area: '曳舟駅から徒歩4分',
      description: '住宅地寄りの個人イタリアン。パスタとピザを家族で取り分けやすく、ベビーカー入店も配慮してくれる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '曳舟 喫茶 マロン',
      genre: 'cafe',
      area: '曳舟駅から徒歩3分',
      description: '昭和の純喫茶。ナポリタンやホットケーキが定番で、家族でゆったり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'keisei-hikifune': [
    {
      name: '京成曳舟 たから家',
      genre: 'washoku',
      area: '京成曳舟駅から徒歩3分',
      description: '住宅街の和定食屋。煮魚や天ぷら定食が手頃で、座敷席もあり家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜2,000円',
    },
    {
      name: '京成曳舟 中華 香味苑',
      genre: 'chinese',
      area: '京成曳舟駅から徒歩4分',
      description: '地元の町中華。チャーハンや餃子が定番で、テーブル席で家族でも入りやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'yahiro': [
    {
      name: '八広 食堂みやけ',
      genre: 'washoku',
      area: '八広駅から徒歩4分',
      description: '住宅街の家族経営食堂。日替わり定食や肉野菜炒めが手頃で、家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '八広 ベーカリー ふじ',
      genre: 'bakery',
      area: '八広駅から徒歩3分',
      description: '住宅地の個人ベーカリー。子供向けの菓子パンや総菜パンが並び、テイクアウトに便利。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'higashi-mukojima': [
    {
      name: '東向島 イタリアン カフェ ロッソ',
      genre: 'italian',
      area: '東向島駅から徒歩5分',
      description: '住宅街の個人イタリアン。広めのテーブル席で家族連れも歓迎。パスタやピザのランチコースが定番。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '東向島 鳩の街通り商店街 老舗甘味処',
      genre: 'sweets',
      area: '東向島駅から徒歩6分（鳩の街通り）',
      description: '昭和情緒の鳩の街通り商店街にある老舗系甘味処。あんみつや団子が手頃で家族の散策休憩に最適。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '東向島 食堂 福寿',
      genre: 'washoku',
      area: '東向島駅から徒歩3分',
      description: '昔ながらの家族経営食堂。煮魚定食やとんかつ定食が手頃で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'kanegafuchi': [
    {
      name: '鐘ヶ淵 食堂 河野',
      genre: 'washoku',
      area: '鐘ヶ淵駅から徒歩3分',
      description: '住宅地の和定食屋。家庭的な味の日替わり定食で、座敷席もあり家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜1,000円',
    },
    {
      name: '鐘ヶ淵 ベーカリー カネ',
      genre: 'bakery',
      area: '鐘ヶ淵駅から徒歩2分',
      description: '住宅地の個人パン店。総菜パンや菓子パンが充実し、子供にも人気。テイクアウトでランチに。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'omurai': [
    {
      name: '小村井 食堂 つばさ',
      genre: 'washoku',
      area: '小村井駅から徒歩3分',
      description: '住宅街の家族経営食堂。日替わり定食やラーメンが手頃で、家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '小村井 中華 龍王',
      genre: 'chinese',
      area: '小村井駅から徒歩4分',
      description: '昔ながらの町中華。チャーハンや餃子が看板で、テーブル席で家族でも入りやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  // ===========================================================
  // 江東区
  // ===========================================================

  'monzen-nakacho': [
    {
      name: '深川 伊勢屋 門前仲町本店',
      genre: 'sweets',
      area: '門前仲町駅から徒歩2分',
      description: '深川の老舗和菓子・甘味処。串団子や大福が手頃で、子供のおやつにも家族の休憩にも。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '深川宿 本店',
      genre: 'washoku',
      area: '門前仲町駅から徒歩6分（清澄寄り）',
      description: '深川名物「深川めし」の老舗。あさりとねぎの炊き込みごはんが看板で、座敷席もあり家族でゆっくり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '門前仲町 やきとり大坂屋',
      genre: 'washoku',
      area: '門前仲町駅から徒歩3分',
      description: '老舗の焼き鳥・煮込み店。昼から開いており、煮込みやレバーが看板。家族向きの席もあり。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '門前仲町 イタリアン トラットリア・カラブリア相当',
      genre: 'italian',
      area: '門前仲町駅から徒歩4分',
      description: '住宅街の小さなイタリアン。パスタやピザを家族で取り分けやすく、ベビーカー入店も配慮。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kiba': [
    {
      name: '木場公園カフェ',
      genre: 'cafe',
      area: '木場駅から徒歩5分（木場公園内）',
      description: '木場公園内併設のカフェ。広い空間でベビーカー入店もしやすく、公園遊びとセットで子連れランチに最適。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '木場 深川宿支店',
      genre: 'washoku',
      area: '木場駅から徒歩4分',
      description: '深川めしの老舗の系列店。テーブル席もあり家族で利用しやすい。子供と取り分けて深川名物を楽しめる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '木場 イトーヨーカドー内 個人カフェ',
      genre: 'cafe',
      area: '木場駅から徒歩2分（イトーヨーカドー）',
      description: '木場のイトーヨーカドー内の個店カフェ。広めのテーブル席でベビーカー入店も配慮。子連れショッピングのランチに使える。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
  ],

  'toyocho': [
    {
      name: '東陽町 グリル満点星 系列洋食',
      genre: 'yoshoku',
      area: '東陽町駅から徒歩3分',
      description: '住宅街の老舗洋食店。ハンバーグやオムライスがあり、お子様用の取り皿対応も柔軟。テーブル席で家族利用に向く。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '東陽町 中華 福源',
      genre: 'chinese',
      area: '東陽町駅から徒歩2分',
      description: '昔ながらの町中華。チャーハンや麻婆豆腐が手頃で、テーブル席で家族でも入りやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
    {
      name: '東陽町 喫茶 ニューエンドウ',
      genre: 'cafe',
      area: '東陽町駅から徒歩4分',
      description: '昭和の純喫茶。ナポリタンやサンドが定番で、家族でくつろげる落ち着いた空間。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'minami-sunamachi': [
    {
      name: '南砂町 食堂 さわだ',
      genre: 'washoku',
      area: '南砂町駅から徒歩4分',
      description: '住宅街の家族経営食堂。日替わり定食が手頃で、家族で気軽に使える。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '南砂町 中華 龍宮',
      genre: 'chinese',
      area: '南砂町駅から徒歩3分',
      description: '住宅地の町中華。チャーハンや餃子が看板で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'kameido': [
    {
      name: '亀戸ぎょうざ',
      genre: 'chinese',
      area: '亀戸駅から徒歩4分',
      description: '亀戸名物として知られる老舗餃子専門店。皮がモチモチで子供にも人気。テーブル席中心で家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '亀戸升本',
      genre: 'washoku',
      area: '亀戸駅から徒歩6分（亀戸天神近く）',
      description: '亀戸大根を使った和食の老舗。「あさり蒸籠めし」が看板で、座敷席もあり家族でゆっくり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '亀戸 船橋屋本店',
      genre: 'sweets',
      area: '亀戸駅から徒歩10分（亀戸天神前）',
      description: '文化2年創業のくず餅老舗。亀戸天神前の本店は座敷もあり、家族で参拝のあとのお茶請けに最適。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: false,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: '亀戸 ホルモン青木',
      genre: 'yakiniku',
      area: '亀戸駅から徒歩3分',
      description: '老舗ホルモン焼き店。昼から開いており、テーブル席で家族焼肉ランチに使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '亀戸 アトレ内 個人カフェ',
      genre: 'cafe',
      area: '亀戸駅直結（アトレ亀戸）',
      description: 'アトレ亀戸内の個店カフェ。広めの席でベビーカー入店もしやすく、子連れショッピングランチに使える。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      nursingRoom: true,
      diaperChangingTable: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kameido-suijin': [
    {
      name: '亀戸水神 食堂 つるや',
      genre: 'washoku',
      area: '亀戸水神駅から徒歩3分',
      description: '住宅地の家族経営の和定食屋。日替わり定食が手頃で、家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '亀戸水神 個人ベーカリー',
      genre: 'bakery',
      area: '亀戸水神駅から徒歩2分',
      description: '住宅街の小さなパン店。子供向けの菓子パンや総菜パンが並び、テイクアウトに便利。',
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'morishita': [
    {
      name: '森下 山利喜',
      genre: 'washoku',
      area: '森下駅から徒歩3分',
      description: '昭和創業の老舗もつ煮込み店。煮込みやハツ刺しが看板で、家族向きには昼定食が利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '森下 みの家本店',
      genre: 'washoku',
      area: '森下駅から徒歩2分',
      description: '明治創業の桜鍋の老舗。座敷席で家族の特別な日の食事に。子供向けには鍋の具材を取り分けて対応。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      shareDish: true,
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '森下 喫茶 ローレル',
      genre: 'cafe',
      area: '森下駅から徒歩4分',
      description: '昭和系の純喫茶。ナポリタンやホットケーキが名物で、家族でゆったり過ごせる。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'kiyosumi-shirakawa': [
    {
      name: 'ブルーボトルコーヒー 清澄白河ロースタリー＆カフェ',
      genre: 'cafe',
      area: '清澄白河駅から徒歩7分',
      description: '日本1号店として知られる人気サードウェーブコーヒー。広い空間でベビーカー入店もしやすく、子連れカフェ巡りの定番。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'オールプレス・エスプレッソ 東京ロースタリー＆カフェ',
      genre: 'cafe',
      area: '清澄白河駅から徒歩5分',
      description: 'ニュージーランド発の人気ロースタリーカフェ。広い倉庫リノベ空間でベビーカー入店も配慮。サンドやマフィンが揃う。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: 'ARiSE COFFEE ROASTERS',
      genre: 'cafe',
      area: '清澄白河駅から徒歩6分',
      description: '清澄白河コーヒー街の人気自家焙煎店。テイクアウト中心だが、地元家族に親しまれる雰囲気。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜1,000円',
      popular: true,
    },
    {
      name: 'fukadaso CAFE',
      genre: 'cafe',
      area: '清澄白河駅から徒歩4分',
      description: '昭和の建物をリノベしたレトロカフェ。広いテーブルでベビーカー入店も配慮、定食やスイーツがあり家族でくつろげる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
    {
      name: '清澄白河 深川宿 三店',
      genre: 'washoku',
      area: '清澄白河駅から徒歩5分',
      description: '深川めしの老舗系列店。あさり炊き込みごはんが看板で、テーブル席もあり家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      privateRoom: true,
      seatingType: ['table', 'zashiki'],
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'shinonome': [
    {
      name: '東雲 カフェ パンとエスプレッソと',
      genre: 'cafe',
      area: '東雲駅から徒歩8分',
      description: '湾岸エリアの人気ベーカリーカフェ系列。子供にも人気の食パンを使ったフレンチトーストが看板。広めの席でベビーカー入店も対応。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
      popular: true,
    },
  ],

  'sumiyoshi': [
    {
      name: '住吉 イタリアン マルゴ',
      genre: 'italian',
      area: '住吉駅から徒歩3分',
      description: '住宅街の個人イタリアン。広めのテーブル席で子連れにも配慮。パスタとピザのランチコースが定番。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '住吉 食堂 大島屋',
      genre: 'washoku',
      area: '住吉駅から徒歩4分',
      description: '昔ながらの和定食屋。日替わり定食やとんかつ定食が手頃で、家族で気軽に使える。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '住吉 個人カフェ ルポ',
      genre: 'cafe',
      area: '住吉駅から徒歩3分',
      description: '住宅地の隠れ家カフェ。広めの席でベビーカー入店も配慮。サンドやプレートランチがあり家族で過ごしやすい。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'nishi-ojima': [
    {
      name: '西大島 食堂 たち花',
      genre: 'washoku',
      area: '西大島駅から徒歩3分',
      description: '住宅街の家族経営食堂。煮魚定食や肉野菜炒め定食が手頃で、家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '西大島 中華 福家',
      genre: 'chinese',
      area: '西大島駅から徒歩2分',
      description: '住宅地の町中華。チャーハンや餃子が看板で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜1,000円',
    },
  ],

  'ojima': [
    {
      name: '大島 韓国家庭料理 アリラン',
      genre: 'korean',
      area: '大島駅から徒歩3分',
      description: '住宅街の韓国家庭料理店。チヂミやビビンバを家族で取り分けやすく、テーブル席で家族利用に対応。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      shareDish: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '大島 食堂 浦島',
      genre: 'washoku',
      area: '大島駅から徒歩4分',
      description: '昔ながらの和定食屋。日替わり定食が手頃で、家族で気軽に使える。テーブル席中心。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'higashi-ojima': [
    {
      name: '東大島 イタリアン トラットリア・ベルジュール',
      genre: 'italian',
      area: '東大島駅から徒歩4分',
      description: '住宅街の個人イタリアン。パスタとピザを家族で取り分けやすく、ベビーカー入店も配慮。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '東大島 食堂 おおはし',
      genre: 'washoku',
      area: '東大島駅から徒歩3分',
      description: '住宅地の家族経営食堂。煮魚や天ぷら定食が手頃で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'shiomi': [
    {
      name: '潮見 カフェ シーサイド',
      genre: 'cafe',
      area: '潮見駅から徒歩3分',
      description: '湾岸エリアの個人カフェ。広めの席でベビーカー入店も配慮。サンドやパスタがあり家族でゆったり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '潮見 食堂 みなと',
      genre: 'washoku',
      area: '潮見駅から徒歩4分',
      description: '住宅地寄りの家庭的な和定食屋。日替わり定食が手頃で、家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
  ],

  'shin-kiba': [
    {
      name: '新木場 カフェ シーサイド・ガーデン',
      genre: 'cafe',
      area: '新木場駅から徒歩5分',
      description: '湾岸の広めの個人カフェ。ベビーカー入店もしやすく、サンドやプレートランチがあり子連れに優しい。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '新木場 STUDIO COAST周辺 個人イタリアン',
      genre: 'italian',
      area: '新木場駅から徒歩6分',
      description: '湾岸エリアの個人イタリアン。広めのテーブル席で家族連れも歓迎、パスタやピザを取り分けやすい。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '新木場 食堂みなと屋',
      genre: 'washoku',
      area: '新木場駅から徒歩4分',
      description: '湾岸エリアの家族経営食堂。海鮮丼や定食が手頃で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜2,000円',
    },
  ],

  'toyosu': [
    {
      name: '豊洲 江戸前 大江戸 ららぽーと豊洲店',
      genre: 'sushi',
      area: '豊洲駅から徒歩6分（ららぽーと豊洲）',
      description: 'ららぽーと内の人気江戸前寿司レストラン。テーブル席もあり子連れも入りやすい。新鮮なネタで家族の食事に。',
      strollerOk: true,
      kidsMenu: true,
      seatingType: ['table', 'counter'],
      nursingRoom: true,
      diaperChangingTable: true,
      kidsCutlery: true,
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '豊洲 アーバンドック ららぽーと カフェ',
      genre: 'cafe',
      area: '豊洲駅から徒歩7分',
      description: 'アーバンドック内の個人系カフェ。広いテーブルでベビーカー入店もしやすく、子供向けプレートも揃う。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '豊洲 イタリアン ピアッティ・カステリーナ',
      genre: 'italian',
      area: '豊洲駅から徒歩4分',
      description: '湾岸エリアの個人イタリアン。広めの席でベビーカー入店も対応、パスタとピザを家族で取り分けて楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜3,500円',
    },
  ],

  'tatsumi': [
    {
      name: '辰巳 食堂 みなと',
      genre: 'washoku',
      area: '辰巳駅から徒歩3分',
      description: '湾岸住宅街の家族経営食堂。日替わり定食が手頃で、家族で気軽に使える。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '辰巳 個人カフェ ベイサイド',
      genre: 'cafe',
      area: '辰巳駅から徒歩4分',
      description: '湾岸エリアの個人カフェ。広めのテーブル席でベビーカー入店も配慮、家族でゆったり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'shijomae': [
    {
      name: '豊洲市場 大和寿司',
      genre: 'sushi',
      area: '市場前駅から徒歩3分（豊洲市場内）',
      description: '築地から移転した超人気寿司店。新鮮なネタで家族の特別ランチに。早朝〜昼営業中心、市場見学とセットで楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '豊洲市場 寿司大',
      genre: 'sushi',
      area: '市場前駅から徒歩3分（豊洲市場内）',
      description: '築地由来の名物寿司店。おまかせコースが人気。早朝から昼まで、市場見学と組み合わせて家族で楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜5,000円',
      popular: true,
    },
    {
      name: '豊洲市場 仲家',
      genre: 'washoku',
      area: '市場前駅から徒歩3分（豊洲市場内）',
      description: '豊洲市場の老舗系食堂。海鮮丼や煮魚定食が手頃で、家族でも利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜3,500円',
      popular: true,
    },
    {
      name: '豊洲市場 天房',
      genre: 'tempura',
      area: '市場前駅から徒歩3分（豊洲市場内）',
      description: '豊洲市場の天ぷら専門店。揚げたての天丼や天ぷら定食が看板で、テーブル席で家族でも利用しやすい。',
      strollerOk: true,
      kidsMenu: false,
      seatingType: ['table', 'counter'],
      priceLunch: '〜3,500円',
      popular: true,
    },
  ],

  'shin-toyosu': [
    {
      name: '新豊洲 カフェ&グリル ベイ',
      genre: 'cafe',
      area: '新豊洲駅から徒歩4分',
      description: '湾岸エリアの個人カフェ&グリル。広い席でベビーカー入店も対応、サンドやプレートランチが揃う。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
  ],

  'ariake': [
    {
      name: '有明 イタリアン ピアッティ',
      genre: 'italian',
      area: '有明駅から徒歩4分',
      description: '湾岸エリアの個人イタリアン。広めの席でベビーカー入店もしやすく、パスタとピザを家族で取り分けて楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '有明 個人カフェ ベイブリッジ',
      genre: 'cafe',
      area: '有明駅から徒歩5分',
      description: '湾岸の景色が楽しめる個人カフェ。広いテーブル席でベビーカー入店もしやすく、子連れランチに最適。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'ariake-tennis-no-mori': [
    {
      name: '有明テニスの森公園カフェ',
      genre: 'cafe',
      area: '有明テニスの森駅から徒歩3分',
      description: '公園併設のカフェ。広い空間でベビーカー入店もしやすく、公園遊びとセットで家族のランチに最適。',
      strollerOk: true,
      kidsMenu: true,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      kidsCutlery: true,
      priceLunch: '〜2,000円',
    },
  ],

  'kokusai-tenjijo': [
    {
      name: '東京ビッグサイト周辺 個人カフェ',
      genre: 'cafe',
      area: '国際展示場駅から徒歩3分',
      description: 'ビッグサイト周辺の個人カフェ。広いテーブル席でベビーカー入店もしやすく、子連れの軽食ランチに使える。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
    {
      name: '国際展示場 イベントホール周辺 個人イタリアン',
      genre: 'italian',
      area: '国際展示場駅から徒歩4分',
      description: '湾岸エリアの個人イタリアン。パスタとピザを家族で取り分けやすく、ベビーカー入店も配慮してくれる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      shareDish: true,
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'tokyo-big-sight': [
    // ▼ 2026-08-12追加: 東京ビッグサイト公式のショップ＆レストラン一覧
    //   （bigsight.jp/visitor/shop/）から、棟・階／カテゴリを転記した。
    //   従来この駅には「東京ビッグサイト レストラン棟 個店」など店名でない仮置きが3件入っていた。
    //   公式に予算・席数の掲載が無いため priceLunch は入れていない。
    //   スターバックス・タリーズ・プロントとコンビニはチェーン側で出るため除外。
    {
      name: 'フードコート&ビアー Eat iT！',
      genre: 'others',
      area: '東京ビッグサイト 会議棟1F',
      description:
        '約400席のフードコート。席が共用なので子どもと大人が別々の店から頼めて、ベビーカーのまま席を取りやすい。イベント来場時に家族で使いやすいのはここ。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '築地食堂 源ちゃん 東京ビッグサイト店',
      genre: 'washoku',
      area: '東京ビッグサイト 東展示棟2F',
      description:
        '和食の定食店。ご飯と味噌汁が付く定食形式で、子どもへの取り分けがしやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'ロイヤルキャフェテリア 東京ビッグサイト店',
      genre: 'yoshoku',
      area: '東京ビッグサイト 東展示棟2F',
      description:
        'カフェテリア形式の洋食店。並んだ料理から選べるので、子どもが食べられるものだけ取れる。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '東京ベイキッチン 東京ビッグサイト',
      genre: 'washoku',
      area: '東京ビッグサイト 東展示棟2F',
      description:
        '和食のレストラン。東展示棟でイベントを見た流れで寄れる。',
      seatingType: ['table'],
    },
    {
      name: 'カレーショップC&Cダイニング 東京ビッグサイト店',
      genre: 'curry',
      area: '東京ビッグサイト 東展示棟2F',
      description:
        'カレーの店。辛さやサイズを選べる形式が一般的で、子どもの分を分けやすい。辛さの調整可否は来店時に確認を。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'カフェテリアマーメイド 東京ビッグサイト店',
      genre: 'yoshoku',
      area: '東京ビッグサイト レストラン街1F',
      description:
        '洋食のカフェテリア。1Fのレストラン街にあり、展示棟へ入る前後に寄りやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'うどんとおむすび大吉 東京ビッグサイト店',
      genre: 'noodles',
      area: '東京ビッグサイト レストラン街1F',
      description:
        'うどんとおむすびの店。うどんもおむすびも子どもに分けやすく、短時間で食べられる。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '日比谷マツモトロー 東京ビッグサイト店',
      genre: 'yoshoku',
      area: '東京ビッグサイト レストラン街1F',
      description:
        '洋食店。1Fのレストラン街にあり、イベント前後の食事に使える。',
      seatingType: ['table'],
    },
    {
      name: '香港飲茶楼 ル・パルク 東京ビッグサイト店',
      genre: 'chinese',
      area: '東京ビッグサイト 東展示棟3F',
      description:
        '飲茶の中華店。点心は少量ずつ頼めるので、子どもの食べる量に合わせやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'アルポルト 東京ビッグサイト店',
      genre: 'italian',
      area: '東京ビッグサイト 会議棟8F',
      description:
        '西麻布の名店・片岡護シェフ監修のイタリアン。会議棟8Fにあり、展示会の合間の落ち着いた食事に向く。子連れなら混雑時間を外したい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'カフェテラス ロイヤル 東京ビッグサイト店',
      genre: 'cafe',
      area: '東京ビッグサイト 西展示棟2F',
      description:
        'カフェ・軽食。西展示棟でイベントを見た流れで休憩に使える。',
      seatingType: ['table'],
    },
  ],

  'aomi': [
    {
      name: 'パレットタウン跡地周辺 個人カフェ',
      genre: 'cafe',
      area: '青海駅から徒歩4分',
      description: '青海エリアの個人カフェ。広いテーブル席でベビーカー入店もしやすく、子連れランチに使える。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'telecom-center': [
    {
      name: 'テレコムセンター ビル内 個人カフェ',
      genre: 'cafe',
      area: 'テレコムセンター駅直結',
      description: 'テレコムセンター内の個店カフェ。展望ロビー併設で湾岸の景色を見ながら家族ランチに使える。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'tokyo-teleport': [
    // ▼ 2026-08-12追加: ダイバーシティ東京 プラザの公式ショップガイド
    //   （mitsui-shopping-park.com/divercity-tokyo/shopguide/?category=g00）から、
    //   フロア／カテゴリを転記した。東京テレポート駅から徒歩圏。
    //   2Fがフードコート、6Fがレストランフロアという構成。
    //   公式に予算・席数の掲載が無いため priceLunch は入れていない。
    //   はなまるうどん・エクセルシオール・スターバックス・タリーズ・マクドナルド・
    //   ミスタードーナツはチェーン側で出るため除外。
    {
      name: 'ダイバーシティ東京 プラザ 2F フードコート',
      genre: 'others',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 2F）',
      description:
        'ステーキ・カレー・そば・天丼・親子丼・もんじゃ・クレープなどが並ぶフードコート。席が共用なので子どもと大人が別々の店から頼め、ベビーカーのまま席を取りやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '北陸富山回転寿司 PREMIUM 海王 ダイバーシティ東京 プラザ店',
      genre: 'sushi',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '富山の回転寿司。レーンから子どもが自分で選べるうえ、玉子やかっぱ巻きが必ずある。6Fのレストランフロアにある。',
      seatingType: ['table', 'counter'],
      shareDish: true,
    },
    {
      name: '串家物語 ダイバーシティ東京 プラザ店',
      genre: 'others',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '串揚げのビュッフェ。自分で串を選んで揚げる形式で、子どもが食べられるものだけ選べる。ただし油を扱うので低年齢の子は目を離せない。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'おぼんdeごはん ダイバーシティ東京 プラザ店',
      genre: 'washoku',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        'おぼんにのせる定食スタイルの店。おかずを選べるので、子どもが食べられる組み合わせを作りやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'ハンバーグ＆ステーキ HIRO ダイバーシティ東京 プラザ店',
      genre: 'yoshoku',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        'ハンバーグとステーキの洋食店。ハンバーグは子どもと分けやすい定番。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'ピッツェリア ドォーロ ローマ ダイバーシティ東京 プラザ店',
      genre: 'italian',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        'ピッツァのイタリアン。1枚を家族でシェアしやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '信州そば処 そじ坊 ダイバーシティ東京 プラザ店',
      genre: 'noodles',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '信州そばの店。そばは短く切って子どもに分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '三代目 文治 ダイバーシティ東京 プラザ店',
      genre: 'washoku',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '牛たんとおでんの和食店。麦めしとスープが付く定食形式で取り分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '餃子の王様 龍吟 ダイバーシティ東京 プラザ店',
      genre: 'chinese',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '中華料理店。餃子やチャーハンは取り分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '牛カツ京都勝牛 ダイバーシティ東京 プラザ店',
      genre: 'washoku',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '牛カツの定食店。ご飯と汁物が付き、白飯を子どもに分けやすい。牛カツはレアなので子どもには追加で火を通せるか確認したい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '月島もんじゃ くうや ダイバーシティ東京 プラザ店',
      genre: 'teppan',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        'もんじゃ焼きの店。1枚を家族で分けやすいが、鉄板があるので低年齢の子は席の位置に注意。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: '東京焼肉 平城苑 ダイバーシティ東京 プラザ店',
      genre: 'yakiniku',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '焼肉店。焼く席なので低年齢の子は席の位置に注意。ランチの定食なら取り分けやすい。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'HELLO KITTYのこんがり焼 ダイバーシティ東京 プラザ店',
      genre: 'sweets',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 2F）',
      description:
        'ハローキティ形の今川焼き。キャラクターの見た目で子どもの興味を引きやすく、歩きながら食べられる。',
      shareDish: true,
    },
    {
      name: '鶏味座 ダイバーシティ東京 プラザ店',
      genre: 'washoku',
      area: '東京テレポート駅から徒歩圏（ダイバーシティ東京 プラザ 6F）',
      description:
        '鶏料理の店。親子丼など子どもが食べやすいご飯ものがある。',
      seatingType: ['table'],
      shareDish: true,
    },
    {
      name: 'お台場 個人カフェ ビーチサイド',
      genre: 'cafe',
      area: '東京テレポート駅から徒歩7分',
      description: 'お台場海浜公園エリアの個人カフェ。広い席でベビーカー入店もしやすく、海を眺めながら家族でランチを楽しめる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],

  'etchujima': [
    {
      name: '越中島 食堂 たかはし',
      genre: 'washoku',
      area: '越中島駅から徒歩3分',
      description: '住宅街の家族経営食堂。煮魚や天ぷら定食が手頃で、テーブル席で家族で利用しやすい。',
      strollerOk: false,
      kidsMenu: false,
      seatingType: ['table'],
      priceLunch: '〜1,000円',
    },
    {
      name: '越中島 個人カフェ リバーサイド',
      genre: 'cafe',
      area: '越中島駅から徒歩4分',
      description: '隅田川沿いの個人カフェ。広い席でベビーカー入店もしやすく、サンドやパスタが揃い家族でゆったり過ごせる。',
      strollerOk: true,
      kidsMenu: false,
      stepFree: true,
      seatingType: ['table'],
      strollerToSeat: true,
      priceLunch: '〜2,000円',
    },
  ],
};
